### ISSUE TITLE
[Bug] links in discription don't work

### ISSUE THREAD

**Issue by VanadiumCoffeecup** [YTVanced/Vanced#788] opened 2021-05-06 23:25 UTC
**Bug description**
When clicking on a link, it says that yt can't open this link

**Variant**
Non-Root

**Vanced version**
16.16.38 - Build - 01.47.00

**Android version**
Android 10

**Device**
Oneplus 8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video
3. Click on a blue link in the video discription 

**Expected behavior**
The link should take me to the designated website

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment] 2021-05-07 01:38
Duplicate of #774

**Closed by milindgoel15** 2021-05-07 01:38 UTC
Labels: bug
