### ISSUE TITLE
[Idea] Option to hide "create, download, and clip" buttons

### ISSUE THREAD

**Issue by FBIAgent05** [YTVanced/Vanced#1495] opened 2021-12-30 13:01 UTC
**Description**
These buttons are bloat and just annoying to accidentally tap at

![Imagepipe_26.jpg](https://user-images.githubusercontent.com/74946397/147754205-2da131d7-236c-4a31-a59b-2afb95d943bb.jpg)

**Comment by milindgoel15** [comment] 2021-12-31 11:05
Duplicate of #1153

**Closed by milindgoel15** 2021-12-31 11:05 UTC
Labels: enhancement
