### ISSUE TITLE
[Idea] Removing the country restriction view flr videos.

### ISSUE THREAD

**Issue by shadowking521** [YTVanced/Vanced#1255] opened 2021-09-11 03:59 UTC
YouTube Vances
**Description**
I'm very sure many people had the same problem as me when watching videos or putting old videos up they start to see country restrictions, such as my simple music Playlist which I used to listen to but now, over 30+ songs have been country restricted. I just wanted to put this idea up, if this idea has been suggested already or impossible just say, hopefully with an explanation please, I personally wanted to look into it and maybe remove it but I do not have the necessary knowledge or resources to do it. 

Yes I do know that a VPN can fix this but VPN may help you see the video at the same time other videos get blocked, also depending on your VPN and its quality. They change your language and how things are in your sites which is annoying and  not helpful.

**Comment by milindgoel15** [comment] 2021-09-11 04:03
Duplicate of #173

**Closed by milindgoel15** 2021-09-11 04:03 UTC
Labels: enhancement
