### ISSUE TITLE
[Bug] Says no connection with connection

### ISSUE THREAD

**Issue by BluFlameBroke** [YTVanced/Vanced#1058] opened 2021-07-06 04:46 UTC
**Bug description**
App opens, but the screen only says I have no connection. Made sure I had connection by using internet and it still didn't work. Restated the phone, still didn't work. Uninstalled and downloaded it again and still the same screen. (This happened with YT music by Vanced as well.)

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
Android 11 

**Device**
Samsung Galaxy S21

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behavior**
App opens and the home screen appears.

**Comment by milindgoel15** [comment] 2021-07-06 05:10
Duplicate of #786

**Closed by milindgoel15** 2021-07-06 05:11 UTC
Labels: bug
