### ISSUE TITLE
[Bug] i can't comment

### ISSUE THREAD

**Issue by pierixAU** [YTVanced/Vanced#1362] opened 2021-10-29 21:11 UTC
**Bug description**
When i try to comment on any video it says this cation isn't allowed

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
Android 9 pie

**Device**
Huawei p smart 2019

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video
3. go to the comment section and type litterally anything
4.when you try to post the comment,a pop up comes and says "this action isn't allowed

**Expected behavior**
i want to be able to comment but when i try a pop up says "this action isn't allowed

Video demonstration:
https://usaupload.com/5enQ/SVID_20211030_003429_1.mp4

**Comment by milindgoel15** [comment] 2021-10-31 06:10
Duplicate of #774

**Closed by milindgoel15** 2021-10-31 06:10 UTC
Labels: bug
