### ISSUE TITLE
[Bug] Distorted buggy videos

### ISSUE THREAD

**Issue by Winter-r** [YTVanced/Vanced#1720] opened 2022-03-05 20:39 UTC
**Bug description:**
Sometimes opening a video makes it go distorted and it sometimes goes away by opening another video then opening it again but that doesnt fix the issue always.

**Have you read vanced guides already? Yes

**Variant:**
Non-Root

**Vanced version:**
17.03.38

https://github.com/YTVanced/VancedManager/releases/latest/download/manager.apk

**Android version:**
Android 10

**Device:**
Huawei nova 7i

**Steps to Reproduce**
Opens video

**Expected behaviour:**
See the normal video

![Screenshot_20220306_003507.jpg](https://user-images.githubusercontent.com/74125949/156899308-565fc67e-f0f8-49a7-9c5d-b57d6a1d6c46.jpg)

**Comment by milindgoel15** [comment] 2022-03-06 03:24
Duplicate of #1664

**Closed by milindgoel15** 2022-03-06 03:24 UTC
Labels: bug
