### ISSUE TITLE
[IDEA] Button to add videos to a queue (not playlist)

### ISSUE THREAD

**Issue by danny5499** [YTVanced/Vanced#1695] opened 2022-02-27 21:14 UTC
I would like to be able to setup a queue for after my current video without having to mess with making a playlist just a quick button to "add to queue" on the fly. maybe a way to see queue

**Comment by milindgoel15** [comment] 2022-02-28 04:30
Duplicate of #333

**Closed by milindgoel15** 2022-02-28 04:30 UTC
