### ISSUE TITLE
[Bug] Casting doesn't work

### ISSUE THREAD

**Issue by Readf0x** [YTVanced/Vanced#761] opened 2021-05-02 01:41 UTC
**Bug description**
When I attempt to cast to anything I get a notification telling me "Youtube Vanced won't work unless google play services is updated," or at least something very similar. When I tap on the notification it open the play store and am stuck on a loading screen. Meanwhile the app enters (for lack of a better term) 'cast mode' and the video is stuck loading.

**Variant**
Non-Root

**Vanced version**
16.16.38 - Build - 

**Android version**
Android 11

**Device**
Google Pixel 2

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'Cast'
3. Select Device to cast to

**Expected behavior**
The app casts to the device

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot](https://user-images.githubusercontent.com/57838054/116799284-a04eed00-aabd-11eb-9fca-85aa06dd90d4.png)

**Comment by Readf0x** [comment] 2021-05-02 01:43
I do not currently know my build version, but will update as soon as I do.

**Comment by KevinX8** [comment] 2021-05-02 01:45
Duplicate of pinned issue and literally mentioned in the changelogs

**Closed by KevinX8** 2021-05-02 01:46 UTC
Labels: bug
