### ISSUE TITLE
[Bug] Chromecast button doesn't go away

### ISSUE THREAD

**Issue by Hyperboraeer** [YTVanced/Vanced#220] opened 2020-11-20 16:09 UTC
**Bug description**
I just realized today that the Chromecast button appeared, and it doesn't go away anymore.  Even tho I have disabled it in Layout Settings. I suppose this is due to a YT update.

**Variant**
NonRoot: Yes
Root: No

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 10

**Device**
ASUS ROG Phone II

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. You will see the Chromecast button, next to the notifications button.
3. Play any video, you will see the Chromecast button there aswell.

**Expected behavior**
Make it possible to remove the Chromecast button again.

![Screenshot_20201120-170421300 (1)](https://user-images.githubusercontent.com/73917917/99822432-7fb85980-2b53-11eb-9b41-9f6e9bbaeca1.png)
![Screenshot_20201120-170355992 (1)](https://user-images.githubusercontent.com/73917917/99822436-8050f000-2b53-11eb-954d-c61d6273b9b1.png)

**Comment by Linxgos** [comment] 2020-11-20 16:14
Already filed at #219

**Comment by Linxgos** [comment] 2020-11-20 16:16
Duplicate of #219

**Closed** 2021-01-18 09:38 UTC
Labels: bug
