### ISSUE TITLE
[Bug] Theme switches back to light after restart

### ISSUE THREAD

**Issue by Martin5001** [YTVanced/Vanced#705] opened 2021-04-27 12:59 UTC
I'm using the light and dark package (not dark and black) (nonroot) and I set the app to dark theme (using the official setting), but whenever I open Vanced settings, it reverts back to light after restart. If I don't open Vanced settings, it stays set to dark correctly.

I'm using Vanced 16.14.34 (but it occurred with the previous version too – I know of at least the one previous release before this one, that's when I started using Vanced)
Android 9.0
Samsung Galaxy J7

**Comment by nekato** [comment] 2021-04-27 14:44
Same problem on a rooted device. But for me it reverts to light whenever I exit and enter the app again.

**Comment by sentix001** [comment] 2021-04-28 07:01
Same for me im using the nonroot version on a rooted device tried both black and dark

**Comment by sentix001** [comment] 2021-04-28 23:08
If you want to reproduce it force stop vanced it happens if i set to dark from general options or from vanced/layout settings

**Comment by gghhkm** [comment] 2021-04-29 02:20
I believe this only affects Android 9.0 user's.
Can you confirm?
@sentix001 @nekato

Nekato can you test if it happens on stock as well.

@Martin5001 sentix001 & nekato 
Would you mind providing [Logcats](https://github.com/Vendicated/Vanced/blob/master/Guides/CreatingALogcat.md)?

This is most likely just a ROM issue but if it's not let's knock this out. 

As for a work around use a dark mode app from the playstore.

**Comment by sentix001** [comment] 2021-04-29 09:53
im using Android 8.1 Xiaomi MIUI ROM ill get u logcat soon

**Comment by gghhkm** [comment] 2021-04-29 09:55
> I'm using Android 8.1 Xiaomi MIUI ROM 
So it effects more devices than I thought. Interesting.

> I'll get u logcat soon
Thanks

**Comment by Destinyg133** [comment] 2021-04-29 12:25
[logcat.txt](https://github.com/YTVanced/Vanced/files/6398471/logcat.txt)


Here you go, hopefully it will help
Device: xiaomi redmi note 5 pro
Rom: xiaomi.eu
Rooted
Latest vanced
Android: 9

**Comment by gghhkm** [comment] 2021-04-29 18:59
@Destinyg133 looks like something in your ROM is denying libc causing stuff to fail. maybe do to MIUI optimization? 🤔
that would explain it for MIUI users, but not the Samsung that Martin5001 has. 🤔
can you check if this happens in stock too? if it doesn't then it's for sure a Vanced issue. 

@Martin5001 a logcat from your device would be appreciated sense you seem to be the odd one out.

**Comment by Martin5001** [comment] 2021-04-29 20:30
Yeah, I'll make a logcat tomorrow.

**Comment by gghhkm** [comment] 2021-04-29 22:30
Hay guys, it's been fixed in the Open Beta.
You can apply and help test it in the [Official Discord](https://discord.gg/vanced)

**Closed by gghhkm** 2021-04-29 22:30 UTC
Labels: bug

**Comment by Martin5001** [comment] 2021-04-30 07:05
> Hay guys, it's been fixed in the Open Beta.
> You can apply and help test it in the [Official Discord](https://discord.gg/vanced)

I was looking for the beta actually, but couldn't find the public-testmonkeys channel anywhere, also most of the channels seem to be locked. Am I missing something? Or how do I get to the beta? (Also it seems that it's only for Discord Booster users, which is paid, isn't it, but you're saying it's public...) Could you please point me in the right direction?
