### ISSUE TITLE
[Idea] Channel blacklist

### ISSUE THREAD

**Issue by OlegLxx** [YTVanced/Vanced#961] opened 2021-06-13 15:58 UTC
A very necessary feature: Channel blacklist.
It is necessary to add channels to the blacklist and exclude them from search, recommendations, explorer.
Who might need it?
-For yourself. People don't want to see annoying content. Less nervous.
-Monitor children who consume any content.
-Control of elderly parents who are susceptible to propaganda.

The standard functionality of the application already has the ability to block a user. This is the only feature that works for commentators. I think that developers can access this list and, based on it, exclude certain channels from the search results.
![block user](https://user-images.githubusercontent.com/73443706/121814253-b1704980-cc78-11eb-8c59-45faf83642ac.jpg)

**Comment by milindgoel15** [comment] 2021-06-14 02:43
Duplicate of #308

Pls stop creating duplicates

**Closed** 2021-06-14 02:43 UTC
Labels: enhancement
