### ISSUE TITLE
[Idea] Add video speed options.

### ISSUE THREAD

**Issue by jonandeva** [YTVanced/Vanced#1141] opened 2021-08-06 11:42 UTC
If possible, I would really appreciate more video speed options. Perhaps up to 3.0x. Maybe there could be an advanced YouTube Vanced setting where your could choose what does options are available to you.

**Comment by milindgoel15** [comment] 2021-08-06 11:46
Duplicate of #82

**Closed** 2021-08-06 11:46 UTC
