### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Cobalttv** [YTVanced/Vanced#1340] opened 2021-10-16 18:52 UTC
**Bug description**
Hello !
When i go on the app now, it writes "No Internet Connection", but my smartphone is connected to Internet...

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
11

**Device**
Samsung Galaxy A32

**Steps to Reproduce**
Steps to reproduce the error
1. Install the app
2. Use it for some weeks, some months
3. The error appears

**Expected behavior**
The Internet connection is on and works on others app ! BUT YouTube Vanced and YTMusic Vanced... not.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by zolexander** [comment] 2021-10-17 00:23
If you change your google password, you have this issue. ( Everything: No Internet Connection) This is tested with more smartphones: Huawei Mate 10 Lite, Xiaomi Redmi Note 9 Pro, Samsung Galaxy S10.
Solution:
You should reinstall first the MicroG after the Youtube Vanced and after it works verry well. This  issue is at last 3 years old.

**Comment by milindgoel15** [comment] 2021-10-17 01:10
Duplicate of #786

**Closed by milindgoel15** 2021-10-17 01:10 UTC
Labels: bug
