### ISSUE TITLE
[Bug] Videos go green

### ISSUE THREAD

**Issue by clawyf** [YTVanced/Vanced#1729] opened 2022-03-07 02:47 UTC
**Bug description:**
I was watching a video and everything turned into green blobs, this was unaffected by orientation and just happened when the video started. It only happened once and closing the app fixed it

**Have you read vanced guides already? (YES/No)**
Yes

**Variant:**
Non-Root

**Vanced version:**
v17.03.38

**Android version:**
Android 12

**Device:**
Google Pixel 6 Pro

**Steps to Reproduce**
I really don't know

**Expected behaviour:**
Videos should look normal

![Screenshot_20220304-151825.png](https://user-images.githubusercontent.com/30278765/156959156-5acdffc5-65c1-4c95-bc74-0234bdab55fc.png)

**Comment by milindgoel15** [comment] 2022-03-07 03:16
If that's only one time it has happened, then ig faulty installation caused it. Just do a fresh reinstall of vanced apps using the [official vanced website](https://vancedapp.com). 

And please fill out every detail asked in the bug report as you completely removed where you got vanced apps from. Closing this issue for now.

**Closed by milindgoel15** 2022-03-07 03:16 UTC
Labels: bug

**Comment by clawyf** [comment] 2022-03-07 03:46
> If that's only one time it has happened, then ig faulty installation caused it. Just do a fresh reinstall of vanced apps using the [official vanced website](https://vancedapp.com). 
> 
> And please fill out every detail asked in the bug report as you completely removed where you got vanced apps from. 
> 
> Edit: and all your other issues #1727 and #1728 are again caused by some faulty installation or you just aren't using official links in the first place. We recommend using reinstallation using the link given above. Closing all these issue for now.

I will do a fresh install, but writing these off as a bad installation seems incredibly lazy to me. Many bugs don't happen often or on all sets of hardware.
I got vanced manager from https://vancedapp.com/. I feel like that section is entirely pointless anyway, the manager installs the app so I have no clue how that would even matter

**Comment by milindgoel15** [comment] 2022-03-07 04:14
>  I feel like that section is entirely pointless anyway, the manager installs the app so I have no clue how that would even matter. 

This section helps us to know if you are downloading vanced from unofficial source or official source. The official source is vancedapp.com so if anyone mentions anything other than this, its considered unofficial and issue get closed straight away.

> Besides, most other open bug reports that include that section don't even link to a site. Why make a fuss over this in my case?

Because at least they mentioned that they got it from vanced manager. Many other issues do mention the actual site And yes, only few of the issues mention "vanced manager", which you removed the whole portion entirely.
And again, if you don't wanna follow the proper template, we will stop providing any sort of help. We would not waste any single minute asking where did u got vanced from.

**Comment by clawyf** [comment] 2022-03-07 04:34
> Because at least they mentioned that they got it from vanced manager. Many other issues do mention the actual site And yes, only few of the issues mention "vanced manager", which you removed the whole portion entirely.
Many don't do that, and yet those were not closed.
See:
#1618
#1641
#1643
#1649
#1666
And these are just what I found in like 2 minutes. It's literally half of all the most recent bug reports that either don't use the template or leave more parts out than I did. And for some reason you seem to have an issue with this specifically
> And again, if you don't wanna follow the proper template, we will stop providing any sort of help. We would not waste any single minute asking where did u got vanced from. 
Then don't, and maybe just focus on the issue. Your time is obviously not important if you are going to leave petty replies instead of allowing the issue to stay open now that you know it is valid

**Comment by milindgoel15** [comment] 2022-03-07 04:50
> Many don't do that, and yet those were not closed.
> See:
> https://github.com/YTVanced/Vanced/issues/1618
> https://github.com/YTVanced/Vanced/issues/1641
> https://github.com/YTVanced/Vanced/issues/1643
> https://github.com/YTVanced/Vanced/issues/1666

you know why? Because such issues were already known before they created these issues on Github. If you want me to show you how we work, then we can as well show every screenshot from our beta testing group and discord server and main telegram chat when these issues were first reported and when these are created in Github. You are wasting your and our time based on these unnecessary arguments.

When we said to create a bug report template fully, you should be just following it for next time instead of making all the fuss about it. But seems like you like to argue over small things. 

> instead of allowing the issue to stay open now that you know it is valid.

So tell me, did you try a clean install? If u did and it still happens, I will open the issue or provide you duplicate issue for it because the distorted video bug exists on even stock 17.03.38. (Duplicate of #1664 )

The only reason I told u to clean install instead of marking it as duplicate in the first place is because:
1. You have a pixel device so i expected such issue to get resolved with your other issue with simple fix
2. Your other issues were simply looked like a bug caused by bad installation

**Comment by clawyf** [comment] 2022-03-07 05:00
> you know why? Because such issues were already known before they created these issues on Github. If you want me to show you how we work, then we can as well show every screenshot from our beta testing group and discord server and main telegram chat when these issues were first reported and when these are created in Github. You are wasting your and our time based on these unnecessary arguments.

So if you report an issue somewhere else first, it doesn't matter where the app was downloaded from? There's no way you made sure ahead of time that all of those people correctly installed the app, or that it came from the right source. And even if you did, the template obviously does not matter much if you don't think the info needs to be included in all cases.

> So tell me, did you try a clean install? If u did and it still happens, I will open the issue or provide you duplicate issue for it because the distorted video bug exists on even stock 17.03.38. (Duplicate of #1664 )

I have to reinstall the app like once a month and I still get all kinds of issues. I'll tell you when it comes back, but it's really unprofessional to pretend it didn't happen until I reinstall and wait a week for it to happen again.

> The only reason I told u to clean install instead of marking it as duplicate in the first place is because:
> 1. You have a pixel device so i expected such issue to get resolved with your other issue with simple fix
> 2. Your other issues were simply looked like a bug caused by bad installation

How am I even supposed to know if my installation is good or not?

**Comment by milindgoel15** [comment] 2022-03-07 05:08
>So if you report an issue somewhere else first, it doesn't matter where the app was downloaded from? There's no way you made sure ahead of time that all of those people correctly installed the app, or that it came from the right source. And even if you did, the template obviously does not matter much if you don't think the info needs to be included in all cases.

Because such issues started appearing before vanced latest even got released. Except for #1618 which was reported after release. 

> How am I even supposed to know if my installation is good or not?
> I have to reinstall the app like once a month and I still get all kinds of issues. I'll tell you when it comes back, but it's really unprofessional to pretend it didn't happen until I reinstall and wait a week for it to happen again.

in that case, you would have to come with logcats and screen recording next time whenever you start facing the same issues again.

**Comment by clawyf** [comment] 2022-03-07 05:16
> Because such issues started appearing before vanced latest even got released. Except for #1618 which was reported after release. 

If vanced has known video rendering errors, then I don't think it's a stretch to believe me when I bring up even more of them.
I don't find your logic here to be consistent.

> in that case, you would have to come with logcats and screen recording next time whenever you start facing the same issues again. 

Does everyone have so much free time that they are fine with reporting issues twice, reinstalling the app, and screen recording everything just to get it known that they exist?
It should not be this much work to simply bring up a problem.

**Comment by milindgoel15** [comment] 2022-03-07 05:41
> Does everyone have so much free time that they are fine with reporting issues twice, reinstalling the app, and screen recording everything just to get it known that they exist?
> It should not be this much work to simply bring up a problem.

So tell me, how do you propose the devs fix your issue when you didn't provide how to reproduce such issues and no screen recording whatsoever as to how did it happen.

From #1727:
> Steps to Reproduce
> I have no idea, it started in the comments of a shorts video

From #1727:
> Steps to Reproduce
> It seems to happen when reentering the app

This is a bit of a step but still a bit vague. 

No one is asking you to create issues again. Just grab the logcat the next time it happens and provide steps to reproduce and screen recording. We will see if we can reproduce this on our end by the time. But you seem to be expecting the dev to fix your issue without reproducing steps and screen recording. Well anyway, I will open the other 2 issues for you and label them as invalid with a reason as to why they are invalid at the same time.

**Comment by clawyf** [comment] 2022-03-07 06:22
> So tell me, how do you propose the devs fix your issue when you didn't provide how to reproduce such issues and no screen recording whatsoever as to how did it happen.

You guys have more insight than I do, considering similar problems do exist or have existed in the past. It's not my job to know what causes the issue, if I did I would fix it myself.
The major problem with video errors is that they appear almost and random, and I don't have the technical knowledge that I would need to diagnose the problem.

> This is a bit of a step but still a bit vague. 
> 
> No one is asking you to create issues again. Just grab the logcat the next time it happens and provide steps to reproduce and screen recording. We will see if we can reproduce this on our end by the time. But you seem to be expecting the dev to fix your issue without reproducing steps and screen recording. Well anyway, I will open the other 2 issues for you and label them as invalid with a reason as to why they are invalid at the same time. 

Most other bug reports do not include recordings, and I seriously doubt footage of the issue actually tells you that much more than a screenshot. The video turns green when you play it, that's literally it.

**Comment by milindgoel15** [comment] 2022-03-07 06:29
> Most other bug reports do not include recordings, and I seriously doubt footage of the issue actually tells you that much more than a screenshot. 

Because not every issue requires us to check screen recording. Your issue is different from others and non-reproducible on our end unless we see a way how it caused on your device then we can try those same steps you were doing to try reproducing the issue.

> The video turns green when you play it, that's literally it.

And we already told it's a stock bug and someone reported it earlier in a different issue. Downgrading to the old build fixes that issue for now until we release a new base update.
