### ISSUE TITLE
[Idea] Option to replace newly added SHORTS tab with EXPLORE (as in the previous version)

### ISSUE THREAD

**Issue by TheAlphaApp** [YTVanced/Vanced#814] opened 2021-05-13 13:59 UTC
**Description**
In the new youtube vanced version 16.16.3 , EXPLORE tab is removed from bottom and SHORTS tab is added. But many people don't like shorts like me and they like it the old way. Please add an option to replace the shorts tab by explore.

![Screenshot_2021-05-13-19-26-05-73.jpg](https://user-images.githubusercontent.com/38341694/118136194-78e31300-b421-11eb-92fe-ac1daa14bc4f.jpg)

**Comment by milindgoel15** [comment] 2021-05-13 18:24
Duplicate of #778

**Closed by milindgoel15** 2021-05-13 18:24 UTC
Labels: enhancement
