### ISSUE TITLE
[Bug] notifications

### ISSUE THREAD

**Issue by Loganavter** [YTVanced/Vanced#1410] opened 2021-11-22 13:12 UTC
**Bug description**
After the notification of a new video arrives, it begins to repeat 6-7 times with a delay every minute, and notifications about 3-4 past notifications about a new video also begin to repeat again. 
This is a rare mistake that I have about once a day. But it really pisses me off and makes me restart my phone.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
Realme 6

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. wait until a new video is released on one of the channels on which I am subscribed.

**Expected behavior**
Usually, the notification of a new video comes only 1 time and does not take 5 more notifications with it.

**Comment by milindgoel15** [comment] 2021-11-22 15:35
Duplicate of #1107

**Closed by milindgoel15** 2021-11-22 15:36 UTC
Labels: bug
