### ISSUE TITLE
Not getting notification when someone likes or replies on my comment.

### ISSUE THREAD

**Issue by Rishibaghel01** [YTVanced/Vanced#1089] opened 2021-07-15 14:12 UTC
**Bug description**
Hello developers👋,
Whenever I comment on any video through YT Vanced , I am not getting any notification when someone likes or replies on my comment. Pls solve that issue 🥺❤️.
Many people replies on my comment and ask variety of queries, but I am unable to reply them...I got to know about those queries when I revisited that specific video after 6-7 month of commenting.

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
 Android 10

**Device**
Redmi note 8 pro , 6/128

**Expected behavior**
I want to get notified when someone likes or replies my comment on YT vanced ❤️ .

**Comment by milindgoel15** [comment] 2021-07-15 15:07
Duplicate of #126

**Closed by milindgoel15** 2021-07-15 15:07 UTC
Labels: bug
