### ISSUE TITLE
[Bug] YT Vanced freezing and crashing

### ISSUE THREAD

**Issue by FlimsyFocus** [YTVanced/Vanced#1054] opened 2021-07-05 19:33 UTC
**Bug description**
After using vanced for a while it starts freezing and stuttering. The stuttering happens when scrolling either through the comments or videos and the video currently playing starts to freeze up. I thought it might be a ram issue because I used vanced for a while and my ram usage showed it was almost full, that is on my old phone LG Stylo 5 which had like 3gb of ram. But the issue still continues to happen on my new phone the S21 so I know it isnt the phone ram thats throttling the app. I uninstalled all vanced apps (microg, manager, vanced music, and youtube vanced) and removed the microg account from settings for a clean install. I reinstalled and turned battery optimization off but the issue continues. It also crashes if I keep using it while it is freezing up, like just keep scrolling in the comments or watch the vid. I found out that if I force stop vanced then it starts working again until I use it for a while and it goes back to the problems. I have the latest vanced but the issues remain and the older versions have the same problem for me. My old phone the LG stylo 5 had android 10 whike my s21 is running Android 11.

**Variant**
Non-Root

**Vanced version**
Vanced version 16.20.35 (latest at time of writing this 07/05/2021)

**Android version**
Android 11 

**Device**
Samsung Galaxy S21 5G

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Use app for a while watching vids 
3. After long periods of use it starts freezing/stuttering 

**Expected behavior**
Expected to use the app like normal but instead it starts freezing up and eventually crashes.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._
![yt](https://user-images.githubusercontent.com/86901213/124512397-419c3d00-dda6-11eb-9ad6-45a6bb5aaea9.jpg)

https://user-images.githubusercontent.com/86901213/124512403-4660f100-dda6-11eb-987d-521408b71188.mp4

**Comment by milindgoel15** [comment] 2021-07-06 03:12
More like device specific issues. Attach logcat of the crash

**Comment by FlimsyFocus** [comment] 2021-07-06 03:17
> More like device specific issues. Attach logcat of the crash

It happened on both my LG Stylo 5 and now my new Galaxy S21 so idk if it's device specific issues but anyways what is a logcat and how do I attach it?

**Comment by XKlarity** [comment] 2021-07-06 05:01
I have the same exact issue with my note 9 and others have this issue too. I reported this issue a few weeks ago saying that I thought it might be a memory leak but the admin closed it saying "It's probably a bug with micro g" so I don't know. It never happened before with the other vanced updates.

**Comment by FlimsyFocus** [comment] 2021-07-06 05:05
> I have the same exact issue with my note 9 and others have this issue too. I reported this issue a few weeks ago saying that I thought it might be a memory leak but the admin closed it saying "It's probably a bug with micro g" so I don't know. It never happened before with the other vanced updates.

Oh so other people have this issue too. Thanks for replying with this info. So I guess that means it's not device specific but something else. Hopefully someone can help find a solution, Thanks in advance.

**Comment by milindgoel15** [comment] 2021-07-06 05:09
> I have the same exact issue with my note 9 and others have this issue too. I reported this issue a few weeks ago saying that I thought it might be a memory leak but the admin closed it saying "It's probably a bug with micro g" so I don't know. It never happened before with the other vanced updates.

Yes, it can be a microG issue indeed. Tbh no one from our beta tester group faced or reported such issue(yet). We are not sure what exactly is causing this but we guess it's microG. Since the microG release v0.2.20 has some certain bugs as well, probably downgrading back to an older version can fix this issue for all of you until further vanced microG update. 

@FlimsyFocus please try it as well. If you are on latest vanced microG release (v0.2.20), give downgrading back to an older build a try. Logcat guides can be found in our [guide app](https://play.google.com/store/apps/details?id=com.vanced.faq)

**Comment by FlimsyFocus** [comment] 2021-07-06 05:15
> > I have the same exact issue with my note 9 and others have this issue too. I reported this issue a few weeks ago saying that I thought it might be a memory leak but the admin closed it saying "It's probably a bug with micro g" so I don't know. It never happened before with the other vanced updates.
> 
> Yes, it can be a microG issue indeed. Tbh no one from our beta tester group faced or reported such issue(yet). We are not sure what exactly is causing this but we guess it's microG. Since the microG release v0.2.20 has some certain bugs as well, probably downgrading back to an older version can fix this issue for all of you until further vanced microG update.
> 
> @FlimsyFocus please try it as well. If you are on latest vanced microG release (v0.2.20), give downgrading back to an older build a try. Logcat guides can be found in our [guide app](https://play.google.com/store/apps/details?id=com.vanced.faq)
> 
> Also edit: here is the link for all vanced microG builds:
> https://github.com/YTVanced/VancedMicroG/releases

I currently have microg version 0.2.18. Do I need to downgrade more?

**Comment by milindgoel15** [comment] 2021-07-06 05:16
Ah, please get the logs then. 

> I currently have microg version 0.2.18. Do I need to downgrade more?

**Comment by FlimsyFocus** [comment] 2021-07-06 05:18
> Ah, please get the logs then.
> 
> > I currently have microg version 0.2.18. Do I need to downgrade more?

Ok I will check out the guide you sent and I'll try to get the logcat

**Comment by FlimsyFocus** [comment] 2021-07-06 18:38
> I have the same exact issue with my note 9 and others have this issue too. I reported this issue a few weeks ago saying that I thought it might be a memory leak but the admin closed it saying "It's probably a bug with micro g" so I don't know. It never happened before with the other vanced updates.

Hey is it possible you could submit the logs since you have the same issue? I just watched the guide and I don't have time rn to do that

**Comment by milindgoel15** [comment] 2021-07-08 15:49
If this issue has not solved yet for you, please try reinstalling all vanced applications. It has been seen that reinstallation every app fixes crashing issue faced by users, might as well fix freezing issue for both of you.

Meanwhile we are closing this issue for now. Please report back to us here if the workaround fix fails.

**Comment by FlimsyFocus** [comment] 2021-07-08 17:56
I already did that before I reported the issue. I deleted every vanced thing I had, YT Vanced, manager, YT Music, Microg and reinstalled everything but it still happens

**Comment by FlimsyFocus** [comment] 2021-07-08 17:56
> If this issue has not solved yet for you, please try reinstalling all vanced applications. It has been seen that reinstallation every app fixes crashing issue faced by users, might as well fix freezing issue for both of you.
> 
> Meanwhile we are closing this issue for now. Please report back to us here if the workaround fix fails.

I already did that before I reported the issue. I deleted every vanced thing I had, YT Vanced, manager, YT Music, Microg and reinstalled everything but it still happens

**Comment by FlimsyFocus** [comment] 2021-07-08 17:58
I used the smart switch app on my S21 to transfer everything from my Stylo 5 so I don't know if that had anything to do with it but idk if I wanna factory reset my s21 and manually move everything over, I'll try to get the logs before I resort to that

**Comment by DILLY-DING** [comment] 2021-07-09 01:46
I have a similar issue, when watching videos using Vanced the videos will sometimes play normally but then they will buffer, and then the sound will continue playing whilst the video is completely frozen. I have tried reinstalling Vanced but have the same issue. I have the same issue on both root and non root.

**Comment by XKlarity** [comment] 2021-07-09 01:54
> > I have the same exact issue with my note 9 and others have this issue too. I reported this issue a few weeks ago saying that I thought it might be a memory leak but the admin closed it saying "It's probably a bug with micro g" so I don't know. It never happened before with the other vanced updates.
> 
> Hey is it possible you could submit the logs since you have the same issue? I just watched the guide and I don't have time rn to do that

Hey! I'm super sorry for the extremely late reply I've been busy. If you haven't got the logcat yet ill try and do it tomorrow. It would be kinda hard to replicate since it happens randomly.

**Comment by FlimsyFocus** [comment] 2021-07-09 02:00
> > > I have the same exact issue with my note 9 and others have this issue too. I reported this issue a few weeks ago saying that I thought it might be a memory leak but the admin closed it saying "It's probably a bug with micro g" so I don't know. It never happened before with the other vanced updates.
> > 
> > 
> > Hey is it possible you could submit the logs since you have the same issue? I just watched the guide and I don't have time rn to do that
> 
> Hey! I'm super sorry for the extremely late reply I've been busy. If you haven't got the logcat yet ill try and do it tomorrow. It would be kinda hard to replicate since it happens randomly.

No worries on the late reply, I haven't gotten the logs yet but it happens more frequently on my phone (probably because I use YouTube more frequently) so if your busy I'll get the logs I just hadn't done it before and it looked like a lot to do at first lol

**Comment by milindgoel15** [comment] 2021-07-23 06:22
sorry for late replies, assuming that the issue is not fixed yet for you, your logs say, it's `Caused by: java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 89672 free bytes and 87KB until OOM, target footprint 536870912, growth limit 536870912; failed due to fragmentation (largest possible contiguous allocation 16252928 bytes)`.

so it could be related to your memory management. One more possibility is the game booster services present in your samsung devices since one of our user found game booster causing huge battery drain with vanced. Please check vanced is not being treated as a game by your device and also try uninstalling those game booster apps(those are system apps so you have to use adb commands to uninstall all that bloatware).

**Comment by FlimsyFocus** [comment] 2021-07-23 21:47
> sorry for late replies, assuming that the issue is not fixed yet for you, your logs say, it's `Caused by: java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 89672 free bytes and 87KB until OOM, target footprint 536870912, growth limit 536870912; failed due to fragmentation (largest possible contiguous allocation 16252928 bytes)`.
> 
> so it could be related to your memory management. One more possibility is the game booster services present in your samsung devices since one of our user found game booster causing huge battery drain with vanced. Please check vanced is not being treated as a game by your device and also try uninstalling those game booster apps(those are system apps so you have to use adb commands to uninstall all that bloatware).

I checked on the game launcher and game booster but it doesn't show YouTube Vanced as a game. You said it could be related to memory management so does that mean it's not enough memory on the phone or how it's handling the memory? If it is related to memory management issue, is there a fix? (I already tried uninstalling and installing all vanced stuff I had).

**Comment by XKlarity** [comment] 2021-09-21 22:51
I still have this issue and its been a really long time now and there hasn't been a fix. Hopefully the devs take a look.

**Closed** 2021-12-06 00:45 UTC
Labels: bug, wontfix
