### ISSUE TITLE
[Bug] Vanced Offline

### ISSUE THREAD

**Issue by saoriiiis** [YTVanced/Vanced#1591] opened 2022-02-09 00:47 UTC
**Bug description:**
Vanced went offline

**Have you read vanced guides already? 
No (about to)

**Variant:**
Root

**Vanced version:**
 v16.29.39

**Link used to download vanced:**
i forgot, i downloaded the vanced from the manager

**Android version:**
 Android 10

**Device:**
Oppo F7

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. instantly go offline

**Expected behaviour:**
Normal Youtube Home, instead of offline screen

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._
![Screenshot_2022-02-09-07-36-21-12_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/99300230/153100526-d8fdd30c-a16a-499c-b080-7ee6589ba0f4.jpg)

**Comment by milindgoel15** [comment] 2022-02-09 02:48
Duplicate of #786

**Closed by milindgoel15** 2022-02-09 02:48 UTC
Labels: bug
