### ISSUE TITLE
[Bug] Can't play/pause/go-to-next/go-to-previous video using media keys on bluetooth keyboards.

### ISSUE THREAD

**Issue by xhiloh** [YTVanced/Vanced#873] opened 2021-05-26 01:31 UTC
**Bug description**
When connected to a bluetooth keyboard(e.g., Logitech K780) which has media control keys(play/pause, next song, previous song, volume up, volume down), Youtube Vanced doesn't respond to play/pause, next song and previous song keys, but volume up/down. Other video players such as nPlayer or the official Youtube app on the same device responds to those keys.

* Same as #848, but this time, tested and reproduced on Samsung Galaxy S8.

**Variant**
Non-Root

**Vanced version**
16.16.38 - Build - 01.51.00

**Android version**
Android 9 -Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
1. Connect a bluetooth keyboard (e.g., Logitech K780 or Satechi bluetooth media button) which has media control keys (play/pause, next song, previous song) to the device.
2. Open Youtube Vanced and play any video.
3. Press "play/pause", "next song" or "previous song" key on the connected bluetooth keyboard.

**Expected behavior**
Player should change the play/pause status, start playing the next song or playing the previous song according to the pressed key.

**Comment by milindgoel15** [comment] 2021-05-26 03:30
Please test your issue on official YouTube app of same vanced version. In other words, youtube app must be of v16.16.38 when checking such issue. Any version before or after this is not accepted for testing bugs out. Tho you haven't mentioned anything about the version of official yt. Please cross-check with it again.

Moreover, I just let this issue run by some of our beta testers and it's stock yt bug for sure. It will happen on both vanced and official so please wait for future updates. This bug is likely to be caused by notification controls.

**Comment by xhiloh** [comment] 2021-05-26 14:05
I have downloaded and installed version 16.16.38 from apkmirror.com, and the official YouTube app correctly responds to these media keys. In other words, the official YouTube app doesn't have this issue.

I will wait for the future updates. Thank you.

**Comment by milindgoel15** [comment] 2021-05-26 16:35
Btw could you tell if the seekbar works on latest 16.19 version of official YouTube? Just play one of the videos. You might need android 10 device for this to test with YouTube premium subscription. If you can't test, then it's okay.
![20210526_215725.jpg](https://user-images.githubusercontent.com/45682747/119697841-41875400-be6e-11eb-8aac-e51f1408440a.jpg)

**Comment by xhiloh** [comment] 2021-05-27 03:17
The devices I have at the moment are using Android 9 and 5. For Samsung Galaxy S8 where I can install Android 10 through TWRP and custom rom, I have a reason to keep Samsung KNOX not broken. I'm afraid I can't test you mentioned. Sorry.

**Comment by milindgoel15** [comment] 2021-06-03 09:28
About this issue, this is apparently a stock bug. The newer vanced releases will fix this issue till that time we are closing this issue.

**Closed by milindgoel15** 2021-06-03 09:28 UTC
Labels: bug
