### ISSUE TITLE
[Idea] Remove create Short button when watching videos

### ISSUE THREAD

**Issue by TheMemeSniper** [YTVanced/Vanced#1226] opened 2021-08-29 12:54 UTC
The create Short button is so easy to accidentally press, causing an annoyance or accidentally uploading something you didn't want to upload to YouTube. Removing it would benefit those of us with clumsy fingers or those who sleep while watching YouTube.

**Comment by milindgoel15** [comment] 2021-08-29 13:29
Duplicate of #1153

**Closed by milindgoel15** 2021-08-29 13:29 UTC
