### ISSUE TITLE
[Bug] Internet Connection Problem 

### ISSUE THREAD

**Issue by KingAnge978** [YTVanced/Vanced#941] opened 2021-06-09 02:38 UTC
**Bug description**
Whenever I open vanced, the app is loading then says "You're Offline. Check Your Connection" 
**Variant**
Non-Root

**Vanced version**
v16.16.38

**Android version**
 Android Pie 9

**Device**
Sony Xperia xa2 ultra 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Wait For It to load
3. "Check your Connection

**Expected behavior**
I expected to load in to app after updating the app for not using it in 2 months.

**Comment by milindgoel15** [comment] 2021-06-09 03:49
Duplicate of #786

**Closed by milindgoel15** 2021-06-09 03:49 UTC
Labels: bug
