### ISSUE TITLE
New Youtube vanced function

### ISSUE THREAD

**Issue by DJMH2403** [YTVanced/Vanced#1288] opened 2021-09-24 06:49 UTC
![Screenshot_20210920_132956_com vanced android youtube_edit_190785485230784](https://user-images.githubusercontent.com/91309413/134630684-2fb00cf2-9d73-4db5-9fe5-8efcb74446b9.jpg)

Hello, my suggestion is this, in this image that I attach, what is in red could be configured?, for example, if I want to hide that bar, or if I want to add other accesses such as the history directly, or add more or less access , in the blue circle it could be configured to hide or to make it visible, and in the yellow it can be configured, to choose if the bar is up or down?  It is that now the phones are bigger and it costs more to reach it, that would be clear are small suggestions, I say it because I use it every day

**Comment by milindgoel15** [comment] 2021-09-24 09:11
Duplicate of #1287

**Closed by milindgoel15** 2021-09-24 09:11 UTC
Labels: enhancement
