### ISSUE TITLE
[Idea] allow more (or customizable) speed settings like 1.1x or 1.2x

### ISSUE THREAD

**Issue by khall187** [YTVanced/Vanced#1533] opened 2022-01-17 03:33 UTC
As the title says, often times 1.25 is just a hair too fast for podcasts. Frequent donator for what it's worth. 

Thank you!

**Comment by milindgoel15** [comment] 2022-01-17 05:20
Duplicate of #82

**Closed by milindgoel15** 2022-01-17 05:20 UTC
