### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by VarunBanka** [YTVanced/Vanced#1485] opened 2021-12-22 08:26 UTC
Ads 

**Bug description:**
Ads are coming in homepage of YouTube vanced
**Have you read vanced guides already? 
YES

**Variant:**
Non-Root

**Vanced version:**
v16.29.39

**Link used to download vanced:**
Vanced manager

**Android version:**
Android 11 

**Device:**
Samsung Galaxy M12

**Steps to Reproduce**
Idk

**Expected behaviour:**
Ads should be blocked
![Screenshot_20211222-134911](https://user-images.githubusercontent.com/88031057/147060457-3c06cba0-2ce7-413e-b28d-141abe3c8c14.jpg)

**Comment by milindgoel15** [comment] 2021-12-22 08:33
Duplicate of #1314

**Closed by milindgoel15** 2021-12-22 08:33 UTC
Labels: bug
