### ISSUE TITLE
[Bug] Community posts blocked when old comment location is used

### ISSUE THREAD

**Issue by jack980517** [YTVanced/Vanced#1023] opened 2021-06-27 18:22 UTC
**Bug description**
When the option to revert to the old comment location (at the bottom, instead of before the recommendations) is enabled, it seems that the device is masqueraded as a tablet entirely. Community posts can no longer be viewed, as if viewing from a tablet. ("Sorry, Community posts are only available on your computer and the latest version of the YouTube app on mobile phones right now.")
As a side note, the "category buttons" (buttons of categories / video topics that YouTube thinks the user is interested in) that normally appear at the top on the home page (phones only) also don't appear any more when the option is enabled. This does not bother me (I'd rather prefer it to be this way), but if you can control this separately from the location of the comment section, maybe this could be a separate toggle?
I hope there's a way to masquerade the device as a tablet only in the "window" that plays videos and not anywhere else.
As another side note, I have tested and confirmed that the "Tablet miniplayer" toggle is not related to this problem.

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
Android 11
RQ3A.210605.005
LineageOS Nightly 20210621

**Device**
Essential Phone
PH-1
mata

**Steps to Reproduce**
Settings
Vanced Settings
Layout Settings
Comments location (Alpha) -> Enable
Refresh and restart? Yes

**Expected behavior**
Nothing else should change other than the location of the comment section.

**Comment by milindgoel15** [comment] 2021-06-28 09:00
Duplicate of #911

**Closed by milindgoel15** 2021-06-28 09:00 UTC
Labels: bug
