### ISSUE TITLE
[Bug] Sponsorblock skips shorts according to the timestamps on currently open video

### ISSUE THREAD

**Issue by Ghibranalj** [YTVanced/Vanced#1716] opened 2022-03-04 21:07 UTC
**Bug description:**
When opening a video and shorts at the same time sponsorblock would skip the short according to the timestamps on the currently open video.

**Have you read vanced guides already? (YES/No)**
YES. 

**Variant:**
Non-Root

**Vanced version:**
17.03.38

**Link used to download vanced:**
https://www.google.com/url?sa=t&source=web&rct=j&url=https://vancedapp.com/&ved=2ahUKEwifupLdra32AhXlSfEDHYY6ALwQFnoECAgQAQ&usg=AOvVaw0Q0FqQt24ZeKZb5VGq5Nv5

**Android version:**
Android 11 

**Device:**
Xiaomi redmi note 10s

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Open a video with sposoblocks segment (skips) within the first minute
3. Open a youtube short.
5. The short will start being skipped based on the timestamps on the video

**Expected behaviour:**
Shorts should not be skipped

*Video demonstration pending*

**Comment by milindgoel15** [comment] 2022-03-05 03:17
Duplicate of https://github.com/YTVanced/Integrations/issues/76

**Closed by milindgoel15** 2022-03-05 03:17 UTC
Labels: bug
