### ISSUE TITLE
[Idea] Open shorts on normal, fully-featured player

### ISSUE THREAD

**Issue by JapanYoshi** [YTVanced/Vanced#1714] opened 2022-03-04 05:50 UTC
**Description**
I've had the issue where I've had Shorts show up on search results, and want to play it in the fully-featured player instead of the less-featured TikTok plagiarism that replays in the background unless I manually stop it.

I've also seen links in the format `www.youtube.com/shorts/VideoIDhere`, and I would like the app to open it as if it were a link in the format `www.youtube.com/watch?v=VideoIDhere`, so that it opens in the normal player. I've done this manually by copying it into a text editor before, but it would be nice to automate it.

Kind of related to #334, which is about the "Shorts" button on the bottom toolbar.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment] 2022-03-04 09:01
Duplicate of #316

**Closed by milindgoel15** 2022-03-04 09:01 UTC
Labels: enhancement
