### ISSUE TITLE
[Idea] avoid youtube redirects and open links directly

### ISSUE THREAD

**Issue by Fogapod** [YTVanced/Vanced#1306] opened 2021-10-01 12:13 UTC
**Description**
Youtube replaces all links with their redirects the only purpose of which is to track you and they also add latency when opening website.

Redirects look like this:
https://www.youtube.com/redirect?q=https%3A%2F%2Fexample.com

I omitted other irrelevant query parameters.

Note that this particular example prompts you to leave youtube, actual urls with tracking info do not have any prompt.

The important parameter is q which is actual urlencoded address. It can be extracted from there or maybe you have internal access to address variable or something, I don't know how vanced works.

**Comment by milindgoel15** [comment] 2021-10-01 12:17
Duplicate of #1012

**Closed by milindgoel15** 2021-10-01 12:17 UTC
Labels: enhancement

**Comment by Fogapod** [comment] 2021-10-01 12:56
@milindgoel15 I don't think these are exactly the same. I am talking about youtube redirects specifically, mentioned issue suggests using ClearURL project and apply it to all links.

ClearURL thing can be implemented on top of this to strip referral links and other trash, but users might choose to support creator/get some benefit by using this link. Youtube redirects, on the other hand, must be force disabled because they are strictly harmful, there is 0 benefit for user.

Implementation could look like `raw url -> strip youtube redirect (this issue) -> ClearURL (optionally) (#1012) -> send to user`

**Comment by milindgoel15** [comment] 2021-10-01 13:08
Basic idea is the same.
