### ISSUE TITLE
[Bug] Not updating the history of watched videos

### ISSUE THREAD

**Issue by cocus** [YTVanced/Vanced#1526] opened 2022-01-13 05:59 UTC
**Bug description:**
While using the current version of Vanced, I noticed that the videos I watch on my phone don't get added to the account history of watched videos. It only shows the ones I've watched on my PC. 

**Have you read vanced guides already? (YES/No)**
Yes. 

**Variant:**
Root

**Vanced version:**
v16.29.39

**Link used to download vanced:**
From vanced manager:
https://github.com/YTVanced/VancedManager/releases/latest/download/manager.apk 

**Android version:**
Android 10

**Device:**
Xiaomi Mi Mix 2s

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app, have an account logged
2. Watch a video, stop it
3. Go to your videos, History and not seeing that video

**Expected behaviour:**
Well, the videos I watch should appear on the history. This is important so I know which ones I already saw or not.

**Comment by milindgoel15** [comment] 2022-01-13 06:22
Duplicate of #301

**Closed by milindgoel15** 2022-01-13 06:22 UTC
Labels: bug
