### ISSUE TITLE
[Idea] playback of age restricted content

### ISSUE THREAD

**Issue by crazyboys0993** [YTVanced/Vanced#1496] opened 2021-12-30 17:34 UTC
Hello,

Youtube is weird. They age restrict content that has no reason being restricted and you have to scan your id to unlock. Who doesn't hate that?
If possible by the server side, it would be great to see that feature added because everyone has that problem and it is not easy to bypass by todays methods.

**Comment by Mesum-Hussain** [comment] 2021-12-30 20:34
> Hello,
> 
> Youtube is weird. They age restrict content that has no reason being restricted and you have to scan your id to unlock. Who doesn't hate that?
> If possible by the server side, it would be great to see that feature added because everyone has that problem and it is not easy to bypass by todays methods. 
> 

I think NewPipe can solve your problem. They don't rely on YouTube for their videos.

**Comment by milindgoel15** [comment] 2021-12-31 11:12
Duplicate of #173

**Closed by milindgoel15** 2021-12-31 11:12 UTC
Labels: enhancement
