### ISSUE TITLE
[Bug] replacemeot connected to internet

### ISSUE THREAD

**Issue by JKDBadger** [YTVanced/Vanced#931] opened 2021-06-07 10:54 UTC
**Bug description**
Hello, since few days ago, youtube vanced doesn't work correctly, neither in 5G or wifi, it says "not connected to the internet"
Of course  my phone is connected :)

**Variant**
Non-Root

**Vanced version**
v16.16.38

**Android version**
MIUI12.0.5.0

**Device**
Poco F3

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Not connected to the internet

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

**Comment by milindgoel15** [comment] 2021-06-07 10:55
Duplicate of #786

**Closed by milindgoel15** 2021-06-07 10:55 UTC
Labels: bug
