### ISSUE TITLE
[Bug] YouTube vanced doesn't recognize wi-fi connection

### ISSUE THREAD

**Issue by AccordionLover** [YTVanced/Vanced#1382] opened 2021-11-13 09:51 UTC
**Bug description**
YouTube vanced doesn't see that my phone's connected to WiFi and doesn't load, i even uninstalled and reinstalled, and it's still bugged.

**Variant**
Non-Root

**Vanced version**
V16.29.39

**Android version**
Android 10

**Device**
Huawei p30 lite

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behavior**
I expected it should load and work properly, but it doesn't work acts like there's no WiFi

![Screenshot_20211113_115039_com vanced android youtube](https://user-images.githubusercontent.com/94220969/141614292-26d0791b-b4bd-4baf-a794-938387ac384e.jpg)

**Comment by milindgoel15** [comment] 2021-11-13 10:11
Duplicate of #786

**Closed by milindgoel15** 2021-11-13 10:11 UTC
Labels: bug
