### ISSUE TITLE
In picture in picture mode miniplayer the window looks dual like and odd

### ISSUE THREAD

**Issue by surajkumarbehera09** [YTVanced/Vanced#260] opened 2020-12-09 12:49 UTC
![Screenshot_20201209-180839_One UI Home](https://user-images.githubusercontent.com/75734796/101631826-007bbe80-3a4b-11eb-9efa-30d820d8b91f.jpg)

**Comment by Jonius7** [comment] 2020-12-18 07:49
I have this, and also if I switch from landscape to portrait, the picture-in-picture goes out of alignment and the video shifts about 200 pixels to the right)

**Comment by surajkumarbehera09** [comment] 2020-12-18 10:56
Yes

**Comment by milindgoel15** [comment] 2021-04-30 12:25
PIP is system side. please don't report pip-related issues.
duplicate of #253

**Closed by milindgoel15** 2021-04-30 12:25 UTC
Labels: wontfix
