### ISSUE TITLE
[Idea] Custom Share 

### ISSUE THREAD

**Issue by madgoatz** [YTVanced/Vanced#1195] opened 2021-08-18 11:05 UTC
**Description**
Since YouTube's share menu does not allow pinning of frequently used apps, replacing the new create button under videos with another share button that allows us to share a YouTube video to one custom predefined app which users are allow to set.

![unnamed](https://user-images.githubusercontent.com/88365986/129886976-f9d642c3-2d18-4cc0-b696-fe4df0136078.png)

**Comment by milindgoel15** [comment] 2021-08-18 16:52
Duplicate of #776

**Closed by milindgoel15** 2021-08-18 16:52 UTC
Labels: enhancement

**Comment by madgoatz** [comment] 2021-08-19 01:57
> Duplicate of #776

not a duplicate. has same heading (title) but the description is different.

**Comment by milindgoel15** [comment] 2021-08-19 02:55
It's one and the same thing. Add a new share or rewrite the existing share button just to get the same result in the end.

Even if it's for a new share, how do you propose we add it when there's no code in the first place?

**Comment by madgoatz** [comment] 2021-08-19 03:51
> It's one and the same thing. Add a new share or rewrite the existing share button just to get the same result in the end.
> 
> Even if it's for a new share, how do you propose we add it when there's no code in the first place? You should note, YouTube is not open source and we do not own YouTube. It's google problem to deal with!

How do i propose u add it? add a option in vanced settings where users can select a specific app for which vanced stores that app's package name. clicking the new share button/option will just share the video link directly to the selected app without showing a share menu. 

Share option code is available on the internet & it can be implemented just like how repeat, sponsor block & swipe control was added. (assuming they were not disabled code already within youtube).

I know youtube is not open source & that u guys do not own it, I just thought you guys could make any useful modifications without google intervening as long as it is not pertaining to downloading video/audio. 

But ok, i understand, it's google's problem to deal with.
