### ISSUE TITLE
YTVanced shows no internet despite full bars of 5g and regular YouTube app works "normal"

### ISSUE THREAD

**Issue by JonnyFlash3** [YTVanced/Vanced#1564] opened 2022-01-30 19:44 UTC
Yesterday the app worked fine with no issues, but this morning it says " your offline. Check your connection."  But the regular youtube app is working "normally" (still has adds in the middle if videos but I know that how it works now).

**Comment by milindgoel15** [comment] 2022-01-30 19:46
Duplicate of #786

**Closed** 2022-01-30 19:46 UTC
