### ISSUE TITLE
[Bug] network connection error

### ISSUE THREAD

**Issue by Aldmors** [YTVanced/Vanced#957] opened 2021-06-13 08:35 UTC
**Bug description**
After adding a google account to the application, when logging in to it, it shows an internet connection error

**Variant**
Non-Root

**Vanced version**
 v16.16.38

**Android version**
7.1.1

**Device**
ZTE Nubia Z17 Lite

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on sign in
3. Click on the google account

https://user-images.githubusercontent.com/48130167/121800568-012c2200-cc33-11eb-919b-0f4891a537cd.mp4

**Expected behavior**
connection error

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment] 2021-06-13 08:36
Duplicate of #786

**Closed by milindgoel15** 2021-06-13 08:36 UTC
Labels: bug
