### ISSUE TITLE
[Bug] Can't Use Picture in Picture Mode

### ISSUE THREAD

**Issue by Sharprake04** [YTVanced/Vanced#1363] opened 2021-10-30 06:40 UTC
**Bug description**
Whenever I try to go to my home screen,  the PIP image does not show up and barley shows when I have my keyboard open.

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
Android 11 

**Device**
Motorola Moto G Stylus 2020

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video, making sure PIP is on
3. Press the home button

**Expected behavior**
I expected that the video would play in PIP mode but it didn't show anything. It only showed up when my keyboard was up.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment] 2021-10-31 06:09
Duplicate of #197

**Closed by milindgoel15** 2021-10-31 06:09 UTC
Labels: bug
