### ISSUE TITLE
[Bug] No connection to internet 

### ISSUE THREAD

**Issue by XsWimj** [YTVanced/Vanced#847] opened 2021-05-21 15:08 UTC
When I enter YouTube vanced it appears that I have no connection to the Internet and I do have an Internet connection

**Comment by milindgoel15** [comment] 2021-05-21 17:10
Duplicate of #786


Just for god's sake. Find your issues in already existing issues on this repository before creating a duplicate

**Closed by milindgoel15** 2021-05-21 17:10 UTC
