### ISSUE TITLE
Vanced keeps spamming notifications

### ISSUE THREAD

**Issue by GitHubUser2110** [YTVanced/Vanced#1161] opened 2021-08-09 22:53 UTC
Since yesterday YouTube Vanced started spamming the same notifications over and over. I got about 20500 notifications from Vanced alone (see attached screenshot) on August 9.
I already received about 2000 notifications and at the time of posting this August 10 is only 50 minutes old.
Restating the device didn't help.
I just updated the app from 16.29.35 to 16.29.39 but it's still the same problem.
microG is on version 0.2.21.212417.
My device is a Samsung Galaxy Tab A 10.1 2019 with Android 11.
![Screenshot_20210810-001736_Digital Wellbeing](https://user-images.githubusercontent.com/44068135/128783461-39ab9ef1-b7ad-4e56-a705-ab0939483a69.jpg)

**Comment by TakuikaNinja** [comment] 2021-08-10 02:33
I've been having the same issue since updating YT Vanced to 16.29.39. I keep receiving the same subscription notification. 
microG is on version 0.2.21.212417. My devive is a Redmi Note 9 (Android 11) running MIUI Global 12.0.1.

**Comment by milindgoel15** [comment] 2021-08-10 03:28
Duplicate of #1107

**Closed by milindgoel15** 2021-08-10 03:28 UTC
