### ISSUE TITLE
[Idea] Option to remove the "shorts" tab at the bottom

### ISSUE THREAD

**Issue by GeneralAeon** [YTVanced/Vanced#1090] opened 2021-07-16 07:26 UTC
**Description**
In one of the recent updates, it would be nice to have the option to remove the button via settings

![Vanced](https://user-images.githubusercontent.com/87518060/125909003-8a3f34f4-a177-4579-b859-faf1e624838d.jpg)

**Comment by milindgoel15** [comment] 2021-07-16 07:50
Duplicate of #334

**Closed by milindgoel15** 2021-07-16 07:50 UTC
Labels: enhancement
