### ISSUE TITLE
[Idea] Settings Search

### ISSUE THREAD

**Issue by MuhammetEminCakir** [YTVanced/Vanced#1667] opened 2022-02-22 12:08 UTC
Can you add an option for searching settings. Because there are a lots of YouTube settings. Also YouTube Vanced have lots of Vanced settings. If we search settings, it would be a great convenience.
 
Newpipe have this option with v0.22.0
![IMG_20220222_150644](https://user-images.githubusercontent.com/64583157/155129208-92d72929-7838-43af-ba3e-a37dddca1e88.jpg)

**Comment by milindgoel15** [comment] 2022-02-22 12:55
Duplicate of #767

**Closed by milindgoel15** 2022-02-22 12:55 UTC
Labels: enhancement
