### ISSUE TITLE
[Bug] Install error because of downgrade version

### ISSUE THREAD

**Issue by entr0pia** [YTVanced/Vanced#1435] opened 2021-12-02 07:29 UTC
**Bug description**
Install error because of downgrade version.

**Variant**
Root

The latest VancedTube version is ```16.29.39```, while the stocked version in my device is ```16.32.34``` after OTA update. Please release a new version VancedTube, or set the version code to a sufficiently large fake value.

**Comment by milindgoel15** [comment] 2021-12-02 07:46
Duplicate of #1427

**Closed by milindgoel15** 2021-12-02 07:46 UTC
Labels: bug
