### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by gildark09** [YTVanced/Vanced#1423] opened 2021-11-28 07:53 UTC
**Bug description**
It said not compatible 

**Variant**
Non-Root

**Vanced version**
Replace me with the exact version of vanced you are using. It is mandatory to report issues from the latest available versions only. For example, v16.16.38

**Android version**
Replace me with the version of Android your device have. For example, Android 11 

**Device**
Replace with the name of the device on which you faced the bug. For example, Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

![Screenshot_2021-11-28-15-46-52-18_664cadb1c148e0d90475ca0f494fbf83](https://user-images.githubusercontent.com/95162775/143734336-9a03e0d9-87b4-4c9d-850d-e4bca2b4cc59.jpg)

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment] 2021-11-29 02:01
Duplicate of #330

**Closed** 2021-11-29 02:02 UTC
Labels: bug
