### ISSUE TITLE
[Idea] Add dislike count via returnyoutubedislike.com

### ISSUE THREAD

**Issue by aequabit** [YTVanced/Vanced#1443] opened 2021-12-05 00:19 UTC
returnyoutubedislike.com provides an API to fetch dislike counts from the YouTube Data API. Although the `dislike` field will be removed on December 13th, I am certain their browser extension will gain traction and that the estimates they will provide will be way better than nothing. An option to show them in the app would be awesome.

I thought about implementing it myself, but realized there was not source code available, so I'm just requesting it here.

https://returnyoutubedislike.com
https://github.com/Anarios/return-youtube-dislike

**Comment by milindgoel15** [comment] 2021-12-05 02:16
Duplicate of #1394

**Closed by milindgoel15** 2021-12-05 02:16 UTC
Labels: enhancement
