### ISSUE TITLE
Account isn't staying signed in upon launch

### ISSUE THREAD

**Issue by Fehr0** [YTVanced/Vanced#982] opened 2021-06-17 07:32 UTC
When I open YT Vanced I'm greeted with a "You're offline. Check your connection" message. Clicking retry does nothing. My connection is working everywhere else.

Clicking on my account icon in the top right corner, clicking on the account drop down, hitting add account, and cancelling out of the vanced sign in screen resets the app and loads my account.

**Comment by milindgoel15** [comment] 2021-06-17 09:33
Duplicate of #786

**Closed by milindgoel15** 2021-06-17 09:33 UTC
