### ISSUE TITLE
Option to disable YouTube shorts.

### ISSUE THREAD

**Issue by clicky6** [YTVanced/Vanced#1436] opened 2021-12-02 07:35 UTC
Please Add an option to disable YouTube Shorts in Vanced settings because I go to YouTube to watch videos but end up clicking on Shorts and scrolling-scrolling till I realize that I wasted my time and it is a vicious cycle.
I don't know If this is a problem for me only or everybody else but an option to disable shorts in Vanced settings would definitely be useful.
Thank You.

**Comment by milindgoel15** [comment] 2021-12-02 07:49
Duplicate of #334

**Closed by milindgoel15** 2021-12-02 07:49 UTC
Labels: enhancement
