### ISSUE TITLE
[Idea] Adding a option to get back the old video quality menu

### ISSUE THREAD

**Issue by Xandar-YT** [YTVanced/Vanced#829] opened 2021-05-17 09:23 UTC
**Description**
It would be good to have a option in layout settings to revert change to video quality menu for people who know to manually set a resolution.

**Comment by Harmonie666** [comment] 2021-05-17 10:20
This would be one of the kindest acts Vanced team could do. I hate the new resolution menu.

**Comment by milindgoel15** [comment] 2021-05-17 13:18
Duplicate of #790

**Closed by milindgoel15** 2021-05-17 13:18 UTC
Labels: enhancement
