### ISSUE TITLE
"Youtube vanced won't run unless you update google play services"

### ISSUE THREAD

**Issue by awilliansd** [YTVanced/Vanced#1184] opened 2021-08-16 15:25 UTC
**Bug description**
I've received a message: "Youtube vanced won't run unless you update google play services" when I try to cast video to my chromecast or tv box. It happens with 16.16.38 version onwards. Doesn't works this feature.

**Variant**
Non-Root

**Vanced version**
v16.16.38

**Android version**
Android 10

**Device**
Samsung Galaxy S9

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment] 2021-08-16 17:30
Duplicate of #688

**Closed by milindgoel15** 2021-08-16 17:30 UTC
Labels: bug
