### ISSUE TITLE
Yt music vanced pause location based recomendation not working

### ISSUE THREAD

**Issue by vihaan-Dev** [YTVanced/Vanced#1065] opened 2021-07-08 08:25 UTC
Yt Music Vanced 

**Variant**
Non-Root

**Vanced version**
v4.30.51

**Android version**
 Android 11 

**Device**
 Samsung Galaxy A21s

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on settings
3. Go yo privacy and location 
4. Pause location based recomendation

**Expected behavior**
When clicked on pause location based recomendation it should stop recommending music depending on your location.  

![Screenshot_20210708-112413_YouTube Music.jpg](https://user-images.githubusercontent.com/69802401/124888817-1575fb80-dff4-11eb-91df-82d07ba95b86.jpg)

**Comment by milindgoel15** [comment] 2021-07-08 08:28
Edit your current issue instead of creating another one.

**Comment by milindgoel15** [comment] 2021-07-08 08:28
Duplicate of #1064

**Closed by milindgoel15** 2021-07-08 08:28 UTC
Labels: bug
