### ISSUE TITLE
[Bug] notification

### ISSUE THREAD

**Issue by jackcooper7274** [YTVanced/Vanced#1055] opened 2021-07-05 21:57 UTC
Bug description 
Everything was working fine with the notification but it stopped showing notification and i don't know why i already tried vanced guide and saw the video about it i check my notification setting in YouTube vanced and deactivated battery optimization for microG

Variant
Non-Root

Vanced version
v16.20.35

Android version
8.0.0

Device
Samsung galaxy s7

**Comment by milindgoel15** [comment] 2021-07-06 03:13
Duplicate of #126

**Closed by milindgoel15** 2021-07-06 03:13 UTC
Labels: bug
