### ISSUE TITLE
[Idea] Age Restriction Bypass

### ISSUE THREAD

**Issue by kineci** [YTVanced/Vanced#1140] opened 2021-08-06 04:43 UTC
There's a useful script called "Simple YouTube Age Restriction Bypass" that allows you to bypass age restriction when using YouTube on a web browser. Is it possible to implement a feature like this into YouTube Vanced the same way you've implemented Sponsorblock into YouTube Vanced?

**Comment by milindgoel15** [comment] 2021-08-06 04:48
Disgusting, stop creating duplicates for god's sake

Duplicate of #173

**Closed by milindgoel15** 2021-08-06 04:48 UTC
Labels: enhancement

**Comment by kineci** [comment] 2021-08-06 04:57
Why not even bother explaining why the feature won't be implemented? Apparently this issue had been marked as stale in the past because "it has not had recent activity",
while a whole continent has the problem and many user have been showing a lot of interest in this feature. If you could at least explain why you're not working on it instead of closing every request.

**Comment by sudo-nautilus** [comment] 2021-08-06 07:00
Why you need the same,
[spoiler]It won't be nice to kids[/spoiler]

**Comment by sudo-nautilus** [comment] 2021-08-06 07:00
Bruh thought this was community :trollface:
