### ISSUE TITLE
[Idea] Speed up videos faster than 2x speed and video default speed options

### ISSUE THREAD

**Issue by kobe4521** [YTVanced/Vanced#861] opened 2021-05-23 23:38 UTC
What I would like is to watch videos faster than 2x speed. The new max speed cap could be 4x speed. The option for this could be added to the already existing option of "playback speed." Just like how you can speed up a video from 1x speed to 2x speed by increments of .25 speeds, the same could be done with speeds higher than 2x speeds. For example, 2x, 2.25x, 2.5x, 2.75x, 3x, etc. You can make the video playback speed cap as high as you want, but I will be content if you could make it as high as 4x.

You could also add an option for the youtube Vance settings named as "playback speed" or something along those lines. With this you can toggle what speed settings you want to view when changing the speed of a video. For example, when I click on playback speed on a video, the only options available to me are 1x, 1.5x, and 2x since I toggled of the options lower than 1x, 1.25x, and 1.75x speeds. This would be great to get rid of the slower options available since I don't use them. 
An additional setting you could add under the same options "playback speed" is the default video speed. I always watch my videos on 2x speed, and everytime I open youtube I have to toggle that option for almost every video. With the video default speed option, I would no longer have to manually change the speed of a video for almost every video I watch. For example, I change the default video speed to 2x speed, so no matter what genre of videos I watch it will always be played at 2x speed. 

(I made a github account just to submit my suggestion).

**Comment by milindgoel15** [comment] 2021-05-24 03:12
Duplicate of #82

**Closed by milindgoel15** 2021-05-24 03:12 UTC
Labels: enhancement

**Comment by kobe4521** [comment] 2021-05-24 03:29
What about the video default speed? I'm pretty sure that it is an original
idea.

**Comment by milindgoel15** [comment] 2021-05-24 04:15
It is already there.
![Screenshot_20210524-094332_YouTube.png](https://user-images.githubusercontent.com/45682747/119295552-b131ef00-bc74-11eb-8f54-fb8de799a349.png)

**Comment by kobe4521** [comment] 2021-05-24 04:47
Thanks for telling me that this was already in the app. I completely
overlooked the fact that I could tap on "Vanced settings" on the bottom of
the page. Took me a while to find it.
I hope that there will come a day when it is possible to watch videos
faster than 2x speed.

Thank you for your time.

**Comment by jonandeva** [comment] 2021-08-06 11:52
I had those same ideas. Hope it gets implemented.
