### ISSUE TITLE
[Bug] Status bar hidden in light mode

### ISSUE THREAD

**Issue by Canvas02** [YTVanced/Vanced#1417] opened 2021-11-24 17:46 UTC
**Bug description**
On my device when on light mode and in portrait the status bar (the bar on the top) is hiddeb

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
Samsung Galaxy A21s

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Open a video
3. the status bar is hidden

**Expected behavior**
The status bar is there

Light mode:
![Screenshot_20211124-193948](https://user-images.githubusercontent.com/73031433/143288945-29c62694-2e8d-4d07-b99c-423b45091861.jpg)

Dark(Amoled) mode:
![Screenshot_20211124-194532](https://user-images.githubusercontent.com/73031433/143289149-84cc464c-3bbe-49e5-9d9a-19827aa01ea8.jpg)

**Comment by milindgoel15** [comment] 2021-11-25 02:57
Duplicate of #1280

**Closed by milindgoel15** 2021-11-25 02:57 UTC
Labels: bug
