### ISSUE TITLE
[Bug] notification

### ISSUE THREAD

**Issue by Acivev** [YTVanced/Vanced#1361] opened 2021-10-28 16:23 UTC
**Bug description**
I become always notification of reminds, has uploaded and new videos. I already cleared the notifications but it comes back and back.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 9

**Device**
Xiaomi Mi Mix 3 5G

**Steps to Reproduce**
Clearing the notification

**Expected behavior**
It should be not come back again and again

![Screenshot_2021-10-28-18-22-43-474_com android chrome](https://user-images.githubusercontent.com/37246611/139296457-7cac5e55-9fca-4886-a141-20daf849c610.jpg)

**Comment by milindgoel15** [comment] 2021-10-31 06:09
Duplicate of #1107

**Closed by milindgoel15** 2021-10-31 06:09 UTC
Labels: bug
