### ISSUE TITLE
[Bug] Notifications resending after removing them from my notification bar sometimes.

### ISSUE THREAD

**Issue by jacobh12349** [YTVanced/Vanced#1422] opened 2021-11-28 02:14 UTC
**Bug description**
I don't know if this is a bug with Vanced or if it's actually just a bug with the actual youtube app, but some days after I would get youtube notifications about comment replies and new videos from channels that I'm subscribed to and other notifications from the app, when I would swipe them away on my notification bar to remove them, they will sometimes come back right after removing them and then sometimes it will either:

-  keep resending those notifications every minute until I turn off notifications for the app in my phone's settings, and then when I turn the notifications back a few hours or so later, it won't be sending the notifications anymore.
- or some other times when i remove the notifications, then they will come back right away removing them, but they wont keep resending every single minute, and they only came back once everytime after removing them, and the only way to stop that is turning off notifications for the app in my phone's settings for a few hours like the first way.

This only happens every few days or so, and once I turn off the notifications for a few hours and turn them back on, if I get any other notifications from the app on the same day that the bug happened, then those notifications can be removed normally and don't do this anymore until either the next day or a few days after.

Again, I don't know if this a bug with Vanced or if it's only a bug with the normal youtube app that this app is based on, so I'm sorry for wasting your time if you guys try to find and fix this bug and find out that it's just a bug with the normal youtube app and that you guys can't fix because of that.

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
Android 11

**Device**
Samsung Galaxy S20+ 5G

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Sign in
3. Subscribe to some channels and turn on notifications for them
4. Wait until you get a notification or a few from the app and try to remove them

**Expected behavior**
I should be able to remove the notifications without them resending.

**Comment by milindgoel15** [comment] 2021-11-28 03:54
Duplicate of #1107

**Closed** 2021-11-28 03:55 UTC
Labels: bug

**Comment by jacobh12349** [comment] 2021-11-28 06:35
oh sorry, i tried to make sure that nobody reported this yet before reporting but i didnt see any other reports of this because i was only searching open issues.
