### ISSUE TITLE
[Bug] Youtube Vanced always rollback to stock Youtube apk

### ISSUE THREAD

**Issue by czerwinski76** [YTVanced/Vanced#1670] opened 2022-02-22 19:21 UTC
**Bug description:**
Youtube Vanced always rollback to stock Youtube apk.
I don't know why it does always do that. 
Removing Youtube Vanced every 3 days and reinstalling it does the trick. 

**Have you read vanced guides already?**
Yes

**Variant:**
Rooted mobile

**Vanced version:**
v17.03.38 (latest) 

**Link used to download vanced:**
Official YouTube Vanced Manager app. 

**Android version:**
Android 11 

**Device:**
Samsung Galaxy S20 FE
One UI 3.1

**Steps to Reproduce**
Normal usage of the smartphone. 
I don't know why it happends.

**Comment by milindgoel15** [comment] 2022-02-23 10:38
Duplicate of #303

**Closed by milindgoel15** 2022-02-23 10:38 UTC
Labels: bug
