### ISSUE TITLE
[Bug] Youtube can't open this link 

### ISSUE THREAD

**Issue by Bilestormglass** [YTVanced/Vanced#1035] opened 2021-06-30 19:10 UTC
** Vanced cannot or will not open any URL links, i get pop up message that says youtube cannot open this link, on any URL on youtube site

**Variant**
Non Rooted
![Screenshot_20210630-145542](https://user-images.githubusercontent.com/86742357/124016694-ef2cdc00-d9b3-11eb-8b86-a85c888a0e82.jpg)

**Vanced version**
16.20.35 - Build - 01.53.00

**Android version**
 Android 11 

**Device**
Samsung Galaxy Note 20 Ultra 
SM-N986U1
**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any url link
3. I get popup error message

**Expected behavior**
Should ipen link in program, or launch appropriate program to run link 

Everytime i click on a url in vanced i get a pop up error message

**Comment by milindgoel15** [comment] 2021-07-01 04:51
Duplicate of #1030

**Closed by milindgoel15** 2021-07-01 04:51 UTC
Labels: bug
