### ISSUE TITLE
Reload bug

### ISSUE THREAD

**Issue by hansolo2048** [YTVanced/Vanced#859] opened 2021-05-23 12:37 UTC
Vanced 16.16.38, non-root

Android 11

Galaxy A51 5g

When I try to reload on vanced app for new video suggestions, this doesn't work all the time. Surprisingly just sometimes works. Would like this issue fixed, thanks.

**Comment by milindgoel15** [comment] 2021-05-23 13:38
Duplicate of #252

**Closed by milindgoel15** 2021-05-23 13:39 UTC
Labels: bug
