### ISSUE TITLE
[Bug] internet connection problem

### ISSUE THREAD

**Issue by mrbooshehri** [YTVanced/Vanced#1228] opened 2021-08-29 14:13 UTC
**Bug description**
App is in no internet access state, the device connected to the internet though.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
Oppo Reno 2 z

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. In every pages app shows 'connect device to the internet'

**Expected behavior**
Work normally

![Screenshot_2021-08-29-17-08-17-40_7a4090f09f6554852d748ee9fd6f40d3.jpg](https://user-images.githubusercontent.com/36568540/131253326-5a8c3799-43d6-4274-b0b8-467993c7b21c.jpg)

![Screenshot_2021-08-29-17-12-14-57_7a4090f09f6554852d748ee9fd6f40d3.jpg](https://user-images.githubusercontent.com/36568540/131253422-9dd17683-1968-4cea-a657-7bb86b930086.jpg)

**Comment by milindgoel15** [comment] 2021-08-29 14:14
Duplicate of #786

**Closed by milindgoel15** 2021-08-29 14:14 UTC
Labels: bug
