### ISSUE TITLE
[Idea] When you share a video it will also grab the current timecode

### ISSUE THREAD

**Issue by Lear62** [YTVanced/Vanced#284] opened 2020-12-23 09:00 UTC
**Description**
I use youtube and vanced between my PC and phone alot so i like to throw long videos back and forth sometimes. It would be super useful if the share grabbed my current playhead/timecode whatever you wanna call it when i shared a video. Maybe a checkbox for enabling the current timecode aswell. Although if there is a checkbox please let me set its default state in the settings. Thanks!

**Comment by VancedOfficial** [comment] 2020-12-23 12:25
I already did these two new buttons you can enable from the settings. One just copies the link, the other one copies the link with the timestamp from the current position in the video. These will be in the next version when that comes.

![copy_buttons](https://user-images.githubusercontent.com/61597887/102995761-675ca580-452a-11eb-9f1d-4c4fd0944654.png)

**Comment by shivasagarrao** [comment] 2020-12-24 21:04
Duplicate of #206

**Comment by Vendicated** [comment] 2021-01-28 18:36
Added. Make sure to enable it in Vanced Settings > Misc

**Closed by Vendicated** 2021-01-28 18:36 UTC
Labels: enhancement
