### ISSUE TITLE
[Bug] When I open YT Vanced with my internet on it says that my Internet is off. 

### ISSUE THREAD

**Issue by Littl3Dev** [YTVanced/Vanced#1013] opened 2021-06-25 07:30 UTC
**Bug description**
When I open YT Vanced with my internet on it says that my Internet is off.
**Variant**
Non-Root

**Vanced version**

16.20.35

**Android version**
Android 8 (O) 

**Device**
Huawei MediaPad T5

**Comment by milindgoel15** [comment] 2021-06-25 13:06
Duplicate of #786

**Closed by milindgoel15** 2021-06-25 13:06 UTC
Labels: bug
