### ISSUE TITLE
YouTube Community Tab Broken

### ISSUE THREAD

**Issue by KingOwnageXV** [YTVanced/Vanced#717] opened 2021-04-28 13:01 UTC
Vanced is on the left side, normal youtube is on the right. My community post don't appear on my channel so I can't check the votes and what not unless I go to the normal YouTube app

![PicsArt_04-28-08 59 05](https://user-images.githubusercontent.com/22395918/116407920-41108480-a800-11eb-8015-4a7e04330751.jpg)

**Comment by KevinX8** [comment] 2021-04-28 21:09
duplicate of #678

**Closed by KevinX8** 2021-04-28 21:09 UTC
