### ISSUE TITLE
[Bug] Can't Reload or Shuffle the Home Feed when layout ads are turned off

### ISSUE THREAD

**Issue by fire17** [YTVanced/Vanced#1688] opened 2022-02-25 06:02 UTC
**Bug description:**
Normally I used to be able to pull up the home tab with my finger all the way and it will show a reload icon and give me new videos in the home feed. 

**Have you read vanced guides already?**
I've searched but I couldn't find any fix for this

**Variant:**
Non-Root

**Vanced version:**
v17.03.38

**Android version:**
Android 10 

**Device:**
Samsung Galaxy Note 9

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on Settings - Vanced Settings
3. In Ad Settings , the second toggle "General Layout Ad Removal" turned on 

**Expected behaviour:**
thankfully when enabled it does remove the ads from the home tab (love you guys) but for some reason it doesn't let me pull up and reload new videos into the home feed. when disabled, I get back the reload functionality aswell as the layout ads.
I'd like to mention that this bug goes way back for me, since many vanced versions ago.

also would like to thank you guys so so much for this project I've gifted events to so many friends over the time and they are all incredibly happy and grateful 
Keep up the incredible work ! 🙏💛🚀

**Comment by milindgoel15** [comment] 2022-02-25 06:04
Duplicate of #252

**Closed by milindgoel15** 2022-02-25 06:04 UTC
Labels: bug
