### ISSUE TITLE
Looping notifications

### ISSUE THREAD

**Issue by PokemasterDude** [YTVanced/Vanced#1229] opened 2021-08-29 15:28 UTC
Occasionally, I'll have a bug where about every 30 seconds I get flooded with the SAME NOTIFICATIONS. It makes my device unusable. I've tried redownloading Vanced/MicroG, and that's only a temporary fix. I COMPLETELY SHUT OFF NOTIFICATIONS AND IT'S STILL HAPPENING. PLEASE FIX SOON IVE BEEN HAVING THIS PROBLEM SINCE THE LATEST UPDATE AND I DONT KNOW HOW TO DOWNGRADE

**Comment by milindgoel15** [comment] 2021-08-29 15:52
Duplicate of #1107

**Closed by milindgoel15** 2021-08-29 15:52 UTC
