### ISSUE TITLE
[Idea] Remove "News" !

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#909] opened 2021-06-01 19:31 UTC
Devs please rid us of this forced plandemic propaganda. It's terribly annoying, and I'm starting to get a headache from seeing this stuff in one of my most used apps. 
No matter how many times I dismiss this crap, it's always coming back. Some sort of news, mostly health related news.
Remove news please!
![Screenshot_20210601-202735627 (1)](https://user-images.githubusercontent.com/73917917/120379750-7e48c480-c320-11eb-911d-927776186982.png)

There have been many requests in the subreddit to remove news,with many upvotes, but they've been ignored. This is mine that I posted recently:
https://www.reddit.com/r/Vanced/comments/nq0x71/fuck_this_devs_please_rid_us_of_this_forced/?utm_medium=android_app&utm_source=share

**Comment by milindgoel15** [comment] 2021-06-02 02:49
Duplicate of #234

Creating duplicates ain't gonna make anyone implement this anytime soon but will only flood our repository.

**Closed by milindgoel15** 2021-06-02 02:49 UTC
Labels: enhancement
