### ISSUE TITLE
[Question] replaceme

### ISSUE THREAD

**Issue by unzoid** [YTVanced/Vanced#852] opened 2021-05-22 07:35 UTC
**Description**
When i try to open a link from a description of a video it says "youtube can't open this link"
This could be because of my phone but i'm not sure since no one has put this in as bug.

_Attach images/videos if possible. These can be helpful in figuring out what the question is about._

**Comment by milindgoel15** [comment] 2021-05-22 08:53
Duplicate of #774

**Closed by milindgoel15** 2021-05-22 08:53 UTC
Labels: question
