### ISSUE TITLE
[Bug] YouTube Vanced bugs when account password changes

### ISSUE THREAD

**Issue by thecowmilk** [YTVanced/Vanced#1412] opened 2021-11-22 20:22 UTC
**Bug description**
I just changed my email's password and it wouldn't let me in again. I would clear the data but the same thing. I try to add this account again but it tells me that it is already on the device.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
9

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. change email password
2. Click on 'youtube vanced'
3. cannot remove or add the same account back

**Expected behavior**
it should let me sign in again with updated password

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by TheAmazingBen100** [comment] 2021-11-22 21:50
If you've recently changed your Google account password, please follow these steps to fix connection issues:

To remove an account:
Go to Device Settings > Accounts
Find the MicroG Account and remove it

Then go back to MicroG and re-add your account.

**Comment by milindgoel15** [comment] 2021-11-23 04:08
Duplicate of #786

**Closed by milindgoel15** 2021-11-23 04:08 UTC
Labels: bug

**Comment by thecowmilk** [comment] 2021-11-23 10:57
Probably before marking it as duplicate which will redirect me to "trobleshooting yt vanced", i think you need to know that original youtube doesn't have to be troubleshooted as it will add the account again.

**Comment by milindgoel15** [comment] 2021-11-23 11:12
Because the official YouTube app doesn't use vanced microG for logging into your Google account. **It straight up uses the built-in google play services** and because of package name. **Vanced non-root variant uses a different package name** which requires vanced microG and vanced microG is a fork of microG to provide functionality to vanced applications for logins. The **microG doesn't support the logins** very well and therefore whenever you change your account password, you need to add your account in microG again by removing it first.

The **root variant of vanced will use the built-in google play services just like official YouTube app does and hence it will not require another logins** after any password change. 

**Please for the sake of God, do your research properly before complaining your bullshit here. It has been explained tons of times over every vanced forums(XDA, telegram, discord, reddit, etc.......**

**Comment by thecowmilk** [comment] 2021-11-23 22:52
That's because of your terrible way of explaining things, probably you got bored of these things but that's not my problem. I asked why it is like that and you could have explained it like the other guy.

People will treat you how you treat em. Don't expect me to understand everything out of thin air. If you know how to communicate your day will be much better.

**Comment by thecowmilk** [comment] 2021-11-23 22:58
To add a solution to this problem just uninstall microg and reinstall it again. This will erase your signed in accounts and will be empty when reinstalled

**Comment by milindgoel15** [comment] 2021-11-24 02:08
Lmao blind idiot
