### ISSUE TITLE
[Bug] can't connect to internet

### ISSUE THREAD

**Issue by svttc** [YTVanced/Vanced#819] opened 2021-05-14 13:37 UTC
**Bug description**
when i try to connect to the app it appears the attempting to reconnect error

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 10 

**Device**
Huawei y9 s

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
**Expected behavior**
i connect to vanced and see videos, as i normally should

![Screenshot_20210514_091844_com vanced android youtube](https://user-images.githubusercontent.com/84188239/118278343-e9c51200-b497-11eb-8c54-30fc410503f2.jpg)

**Comment by Bulamadim** [comment] 2021-05-14 15:14
https://youtu.be/S5sTXRTrD5Y 😃👍

**Comment by milindgoel15** [comment] 2021-05-15 02:55
Duplicate of #786

**Closed by milindgoel15** 2021-05-15 02:55 UTC
Labels: bug
