### ISSUE TITLE
[Bug] Subtitles dissappear eventually no matter what 

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1002] opened 2021-06-23 23:19 UTC
**Bug description**
Subtitles dissappear eventually no matter what, after closing and re-opening the map it gets subtitles back. 

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
Android 12

**Device**
 Samsung Galaxy S10 Plus 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Keep it open for some time
3. Subtitles won't work anymore 

**Expected behavior**
Subtitles should still work but they stop

**Comment by milindgoel15** [comment] 2021-06-24 12:59
Check stock yt if it does the same

**Comment by Mimicthis** [comment] 2021-06-24 14:11
I've been on it for hours. It doesn't.

**Comment by milindgoel15** [comment] 2021-06-27 10:40
None can reproduce it.

**Comment by Mimicthis** [comment] 2021-06-27 11:42
Well I'm so sorry. I don't know how to help.

**Comment by milindgoel15** [comment] 2021-07-08 15:47
Duplicate of #1057

**Closed by milindgoel15** 2021-07-08 15:47 UTC
Labels: bug
