### ISSUE TITLE
[Idea] Fixed audio volume for all videos

### ISSUE THREAD

**Issue by Biasio** [YTVanced/Vanced#1367] opened 2021-11-02 10:26 UTC
A very annoying thing while listening to music on both youtube and youtube music is the difference of volume between videos, like there are videos with very low volume and others with high. A fix could be by make videos volume fixed to a standard volume regulated by the app volume. To make the experience like other music stream apps like spotify. This is extremely noticeable with headphones and at low volumes.
Maybe it is a feature that will be more usefull in youtube music, maybe google itself will implement it.

Hope you will do earlier guys😌.
Thank you

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by TheAmazingBen100** [comment] 2021-11-02 13:30
Go to Google instead.

**Comment by Biasio** [comment] 2021-11-02 14:38
What a useless comment...

**Comment by milindgoel15** [comment] 2021-11-02 14:47
Duplicate of #1143

**Closed by milindgoel15** 2021-11-02 14:47 UTC
Labels: enhancement
