### ISSUE TITLE
[idea] Submission to F-droid?

### ISSUE THREAD

**Issue by BenjaminHCCarr** [YTVanced/Vanced#1745] opened 2022-03-11 16:47 UTC
I know your recently delivered VanceManager, but it's there any chance we could get this added to the F-Droid repository? Would make updates for users smoother.

**Comment by RealKasumi** [comment] 2022-03-11 16:52
[Duplicate of a similar issue in the Manager Github.](https://github.com/YTVanced/VancedManager/issues/124)

F-Droid focuses on open-source and FOSS apps.
Vanced is not open source or free as in libre.
So nope.

**Closed** 2022-03-11 16:54 UTC
