### ISSUE TITLE
[Bug] replaceme I can't install youtube vanced on my Galaxy A31

### ISSUE THREAD

**Issue by Felipe19981** [YTVanced/Vanced#1101] opened 2021-07-22 14:11 UTC
I can't install youtube vanced on my Galaxy A31, when I try to install an error appears on the screen as I show on a printscreen.
android 11
I don't have root
please reply me on my email: dipaz993@gmail.com
sorry for the english, i'm brazilian and i speak portuguese
![Screenshot_20210722-095405_Vanced Manager](https://user-images.githubusercontent.com/87817763/126653371-82e3a6da-d470-4e2a-ab9e-23cbd2f77956.jpg)
![Screenshot_20210722-095412_Vanced Manager](https://user-images.githubusercontent.com/87817763/126653378-87f20038-a542-4624-9764-6ace9f0c1afc.jpg)
![Screenshot_20210722-095504_Settings](https://user-images.githubusercontent.com/87817763/126653384-cdeb03fc-e299-4e5a-ba62-896a06b4614c.jpg)

**Comment by milindgoel15** [comment] 2021-07-22 14:21
Duplicate of #330

**Closed by milindgoel15** 2021-07-22 14:21 UTC
Labels: bug
