### ISSUE TITLE
[Idea] I need the dislike button back. I believe in you youtuba vanced my hero

### ISSUE THREAD

**Issue by joewilliams007** [YTVanced/Vanced#1414] opened 2021-11-24 00:14 UTC
**Description**
You sit to ur pc, open notepad++ add the dislike button and tap: pushh on github app

**Comment by milindgoel15** [comment] 2021-11-24 02:06
Jesus Christ, go cry to your mama, not here.

**Comment by milindgoel15** [comment] 2021-11-24 02:07
Duplicate of #1394

**Closed by milindgoel15** 2021-11-24 02:07 UTC
Labels: enhancement
