### ISSUE TITLE
[Idea] Custom Playback Speed faster than 2x (2.25x / 2.5x / 2.75x / 3x)

### ISSUE THREAD

**Issue by AbdulMalikDev** [YTVanced/Vanced#1187] opened 2021-08-17 05:11 UTC
**Description**
Ability / Feature to Increase playback speed upto 3x. Current maximum is only 2x. 

In desktop version this can be handled by using an extension but there have been multiple issues for this that have been closed even though there is massive support for this feature.

**Comment by milindgoel15** [comment] 2021-08-17 10:29
Duplicate of #82

**Closed by milindgoel15** 2021-08-17 10:30 UTC
Labels: enhancement

**Comment by AbdulMalikDev** [comment] 2021-08-17 11:48
> Duplicate of #82

This issue is closed thats why i opened a new one
