### ISSUE TITLE
[Idea] don't redirect links to YouTube's tracker

### ISSUE THREAD

**Issue by betseg** [YTVanced/Vanced#1259] opened 2021-09-13 21:03 UTC
**Description**

If there's a Twitter link in a video description for example, it opens it in the browser because YouTube links it to their click/link tracker. This is both a privacy and a UX issue.

**Comment by milindgoel15** [comment] 2021-09-14 04:34
duplicate of #1012

**Closed by milindgoel15** 2021-09-14 04:34 UTC
Labels: enhancement
