### ISSUE TITLE
[Bug] notifications

### ISSUE THREAD

**Issue by VarunBanka** [YTVanced/Vanced#1368] opened 2021-11-03 15:27 UTC
**Bug description**
 even after cleaning the notification i m reviving it again even after i watch the video, i have tried all the troubleshooting methode

**Variant**
Non-Root

**Vanced version**
 v16.29.39 of YouTube vanced

**Android version**
Android 11 , Stock one ui 3 ROM

**Device**
Samsung Galaxy M12

**Steps to Reproduce**
Steps to reproduce the error:
1.even after cleaning the notification i m reviving it again even after i watch the video, i have tried all the troubleshooting methode. Also i asked in XDA general telegram group they said it may be a bug and i tried all the methods on Google as well as yt vanced site to fix it...

**Expected behavior**
I expect the notification on the video i have already clicked and watched won't come again.

**Comment by TheAmazingBen100** [comment] 2021-11-03 16:19
There are two ways to solve this:
1: Downgrade MicroG from the Github Repo [https://github.com/YTVanced/VancedMicroG/releases](https://github.com/YTVanced/VancedMicroG/releases)  AND reinstall Vanced
2: Disable all Vanced notifications

**Comment by milindgoel15** [comment] 2021-11-03 16:22
Duplicate of #1107

**Closed by milindgoel15** 2021-11-03 16:22 UTC
Labels: bug
