### ISSUE TITLE
[Bug] notification bar disappears in video

### ISSUE THREAD

**Issue by HardFur** [YTVanced/Vanced#1379] opened 2021-11-12 04:56 UTC
**Bug description**
Like a screenshot, the bar disappears even though it's not a full screen.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
 Android 11 one ui 3.1

**Device**
Samsung Galaxy A32 5G

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. go to any vidio
3. ....

**Expected behavior**
appear the notification bar but it disappeared

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._
![Screenshot_20211112-134312](https://user-images.githubusercontent.com/60815464/141411998-19ccbd4b-b8b5-4fb8-b03f-457962fab7ea.jpg)

**Comment by milindgoel15** [comment] 2021-11-12 05:25
Duplicate of #1280

**Closed by milindgoel15** 2021-11-12 05:25 UTC
Labels: bug
