### ISSUE TITLE
[Bug] Youtube does not collect the history of viewed videos

### ISSUE THREAD

**Issue by oumuamuax** [YTVanced/Vanced#1275] opened 2021-09-19 22:17 UTC
YouTube Vanced

**Bug description**
YouTube Vanced playback history is not working, the videos I watch are not being saved. It's like I've never played them.
However when I view them from the web browser, youtube picks them up and even the timestamp. As seen in the screenshot.

**Variant**
Root - I use magisk and the installation of YouTube Vanced becomes infinite (Other bug)

**Vanced version**
YouTube Vanced 16.29.39

**Android version**
Android 11, MIUI 12.5.1

**Device**
Xiaomi Redmi Note 9

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

![image](https://user-images.githubusercontent.com/19560107/133944677-2f15aed6-2f98-403d-b264-59799b357e8f.png)

**Comment by Audition-CSBlock** [comment] 2021-09-19 23:43
Had the same issue, if you're using any sort of root/hosts adblock, disable it for vanced as in some blocklists, it blocks YouTube's history.

**Comment by milindgoel15** [comment] 2021-09-20 03:12
Duplicate of #301

**Closed** 2021-09-20 03:12 UTC
Labels: bug
