### ISSUE TITLE
[Bug] after the last update,went to very wrong... 

### ISSUE THREAD

**Issue by MarianCoca37** [YTVanced/Vanced#960] opened 2021-06-13 14:23 UTC
**Bug description**
I own an iHunt Titan p800 Pro,with Android 10,issues started a week ago when Vanced no longer connects to the internet,during a strong internet connection to a wifi router or mobile data in strong signal area,went to get the latest manager and latest microg to update them after uninstall the previous version and i stall clean the newest...big bad surprise,Vanced does not open...once connected to internet,displays the recommentation page and when all loaded,Vanced shuts down itself whatever i would do...noroot Android 10,aswell as the Blackview a60Pro i have on spare,with the pre last version installed and working great,the same version that on iHunt Titan p8000 Pro cuts the internet connection...what and whi this?! 

**Variant**
Non-Root

**Vanced version**
Version v2.6.0-crimson

**Android version**
Android 10

**Device**
iHunt Titan p8000 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
Shuts down as soon as the reccomandation page load with no error notification.

**Expected behavior**
Expected to behave at least like youtube with no adds on videos

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._
Unble to screenshot the issue due it's nature,i am too unexperienced to find the catlogs to show...

**Comment by milindgoel15** [comment] 2021-06-13 17:44
duplicate of #954

**Closed by milindgoel15** 2021-06-13 17:44 UTC
Labels: bug
