### ISSUE TITLE
[Bug] Vanced will occasionally be overwerwritten by original YouTube

### ISSUE THREAD

**Issue by MarkoTodoricNTNX** [YTVanced/Vanced#866] opened 2021-05-24 12:35 UTC
**Bug description**
On occasion (seems random) Vanced YT App will be replaced by original YT app. Only workaround at that point is to Uninstall then Install from Vanced Manager.

**Variant**
Root (i guess... root variant is selected but i never see Magisk notification that root access is denied, it does have root permissions in magisk, though and notifications are not blocked)

**Vanced version**
16.16.38

**Android version**
Android 10 / MIUI Global 12.0.7 Stable

**Device**
Xiaomi Redmi Note 8 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Watch/Use YT Vanced
2. Resume my life
3. After sometime when i open YT again, it will open regular YT app (there are Vanced specific settings missing)

**Expected behavior**
When i open YouTube, Vanced should be normally started.

So far I've tried to Detach YT App from Market by following "Workaround 3" (I don't want to install yet another app so used W3 as i already have Magisk Manager)
I've also tried to set Root Script Sleep time to 2.

**Comment by milindgoel15** [comment] 2021-05-24 12:44
Duplicate of #501

**Closed by milindgoel15** 2021-05-24 12:44 UTC
Labels: bug

**Comment by milindgoel15** [comment] 2021-05-24 12:46
Duplicate of #303

**Comment by maretodoric** [comment] 2021-05-30 12:10
Sorry for commenting on closed thread, i just want to shed some light. I made some changes and I've been monitoring the vanced ever since this thread is closed and i no longer have issues with vanced being replaced. I've used it regularly, opening it via YT link from other apps/websites, and using it in Android Auto with help of Screen2Auto and for now, no issues! Previously vanced would be replaced in a matter of day, 2max. Here are the steps that worked for me:
- Remove vanced
- Remove "detach" packet
- reboot the phone
- opt out of play store beta (i honestly think this was most important as probably beta version has some safety implementation)
- reboot again
- install vancee
- perform workadound 3 but use "cronjob" scheduling instead of djs

And enjoy!
Hope this may help someone

**Comment by milindgoel15** [comment] 2021-05-30 14:07
So where can a user find cronjob?

**Comment by maretodoric** [comment] 2021-05-30 14:13
When you perform workaround 3 and when you get to part where user must type "su -c detach -t", using crond is one of the options (and recommended one for me).

![Screenshot_2021-05-30-16-13-03-822_com termux](https://user-images.githubusercontent.com/42638763/120107604-f7e68400-c161-11eb-9d14-b1b9a88bf378.jpg)

**Comment by milindgoel15** [comment] 2021-05-30 14:59
Ah ok
