### ISSUE TITLE
[Bug] Pop up video player is not working.

### ISSUE THREAD

**Issue by DiodE-ui** [YTVanced/Vanced#1603] opened 2022-02-14 20:51 UTC
**Bug description:**
the pup up video player feature is not working for me, when I exit the app -not close it-, I can't find the pup up video, I can't find the app in Recently Used Apps and I can't find the notification indicating that Vanced is playing audio. All I get is audio in the background. The pop up window appears when Keyboard is on, but disappears once I click on it or try to move it around.

**Have you read vanced guides already? (YES/No)**
yes.

**Variant:**
Non-Root

**Vanced version:**
v16.29.39

**Link used to download vanced:**
[official Vanced website](https://vancedapp.com/)

**Android version:**
Android 11 

**Device:**
Xiaomi Redmi Note 8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on random video
3. exit app

**Expected behaviour:**
video still playing in a small pop up window.

**Actual behaviour:**
Audio playing in the background and Pop up window and audio player features not accessible.

https://user-images.githubusercontent.com/79374535/153944074-b4f5499a-825e-4986-9e0b-d4692d410ef5.mp4

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._

**Comment by milindgoel15** [comment] 2022-02-15 02:20
Duplicate of #197

**Closed by milindgoel15** 2022-02-15 02:20 UTC
Labels: bug

**Comment by DiodE-ui** [comment] 2022-02-15 11:03
> Duplicate of #197

>The OP fails to mention that it only happens when using gestures instead of 3 buttons at the bottom of the screen (Android/MIUI setting).

judging by what that guy said it is not the same problem. Also..

> The way PiP works is controlled by your operating system. If it's broken, there's nothing we can do, so please don't report PiP related issues.

How? it worked just fine before. And I haven't updated/changed a crucial setting of my phone.

**Comment by milindgoel15** [comment] 2022-02-15 11:12
We don't deal with any pip issue as it's not related to vanced. Read troubleshooting next time beforehand.
