### ISSUE TITLE
[Bug] Feed refresh doesn't work

### ISSUE THREAD

**Issue by ceejey** [YTVanced/Vanced#1236] opened 2021-09-01 17:57 UTC
**Bug description**
Hello everybody,

the swipe down action on the personal feed of yt does work a few times when opening the app and then just don't show the loading circle anymore while swiping down but still the "swipe shadow". I have to switch the screen and go back to the feed to be able to refresh again a few times until it happens again.

BR

**Variant**
Non Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
Samsung Galaxy S20+

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Swipe down to refresh
3. Repeat 2. a few times
4. The refresh doesn't work anymore (doesn't show the loading circle coming from the top to bottom while swiping and does not refresh)

**Expected behavior**
The refresh should wirk reliable just like in the official youtube app

**Comment by milindgoel15** [comment] 2021-09-02 04:12
Duplicate of #252

**Closed by milindgoel15** 2021-09-02 04:12 UTC
Labels: bug
