### ISSUE TITLE
[Bug] Scrolling Comments in Landscape mode causes Vanced Swipe Controls(Volume) to get triggered.

### ISSUE THREAD

**Issue by HybridShivam** [YTVanced/Vanced#1669] opened 2022-02-22 16:25 UTC
**Bug description:**
Scrolling Comments in Landscape mode causes Vanced Swipe Controls(Sound) to get triggered resulting in unintended volume modification.

**Variant:**
Non-Root

**Vanced version:**
 v17.03.38

**Link used to download vanced:**
Official Website/ Vanced Manager

**Android version:**
 Android 9

**Device:**
ASUS Max pro m2

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Play any video in landscape mode.
3. Toggle comments 'On'
4. Swipe comments section.

**Expected behaviour:**
Swipe Controls not get triggered.

**Comment by milindgoel15** [comment] 2022-02-23 10:37
Duplicate of #889

**Closed by milindgoel15** 2022-02-23 10:37 UTC
Labels: bug
