### ISSUE TITLE
[Bug] No Internet bug

### ISSUE THREAD

**Issue by Hellohi3654** [YTVanced/Vanced#1123] opened 2021-07-28 06:39 UTC
**Bug description**
When opening the app it just says no internet even though I am connected to the internet 
Normal Youtube works fine.
I have tried restarting, turning off ad guard, everything.

**Variant**
Non-Root

**Vanced version**
Latest: v16.20.35

**Android version**
Android 11 

**Device**
OnePlus 7t pro oxygen os 11.0.1.1.HD01AA

**Steps to Reproduce**
Steps to reproduce the error:
1. Open YouTube vanced
2. See no internet bug

**Comment by Hellohi3654** [comment] 2021-07-28 06:43
![Screenshot_20210728-163817.jpg](https://user-images.githubusercontent.com/57390764/127276290-59a7d949-267c-4e97-a56a-ff5a70dc149e.jpg)
![Screenshot_20210728-163831.jpg](https://user-images.githubusercontent.com/57390764/127276302-df3f4ffd-3683-4086-96ef-eda300cc6481.jpg)

**Comment by milindgoel15** [comment] 2021-07-28 08:12
Duplicate of #786

**Closed by milindgoel15** 2021-07-28 08:12 UTC
Labels: bug
