### ISSUE TITLE
 [Bug] 16.16.38 Won't cast to Chromecast

### ISSUE THREAD

**Issue by JDMorris81** [YTVanced/Vanced#732] opened 2021-04-30 11:48 UTC
**Bug description**
After pushing cast button and selecting Chromecast, device does not connect and a notification prompts to update Google Play Services. Clicking this link results in an endless spinner

**Variant**
Non-Root/Root

**Vanced version**
16.16. 38

**Android version**
Android 11 

**Device**
Samsung Galaxy S20 5G

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'cast.'
3. Select Chromecast

**Expected behavior**
Selecting Chromecast from available devices should connect to device

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_20210430-043802](https://user-images.githubusercontent.com/72824463/116691089-2f012400-a96f-11eb-8f47-2c22219f1a31.jpg)

**Comment by KevinX8** [comment] 2021-04-30 11:49
Duplicate of #688

**Closed** 2021-04-30 11:49 UTC
Labels: bug

**Comment by JDMorris81** [comment] 2021-04-30 12:09
This is a newer version plus there is an issue now with play services. I don't know why you would link to the other issue.

**Comment by sam-cross** [comment] 2021-05-07 07:07
Getting this on 16.16.38 when attempting to cast to a Nest Hub Max.

Official YouTube app works. Vanced doesn't.

**This issue should be reopened as it refers to a different problem**, even if it is similar to the other. Rename this issue to "Play Services update required when initiating casting" or something.

**Comment by bersbersbers** [comment] 2021-05-07 07:17
@sam-cross has a point - I downgraded from 16.16.38 to 16.14.34 and casting works again. That is not to say, however, that just deleting and reinstalling 16.16.38 couldn't have solved that problem too.
