### ISSUE TITLE
[Bug] Can't load videos, not connected to internet

### ISSUE THREAD

**Issue by Lucas559-noob** [YTVanced/Vanced#989] opened 2021-06-20 02:52 UTC
**Bug description**
It happened a time ago, then I thought was already know so I waited to an update and the update did not fix it, so when I open YTVanced it try to load videos in home page but after some seconds it say that I'm offline and ask to connect, but I receive notifications.

**Variant**
Non-Root

**Vanced version**
16.20.35 Build 01.53.00

**Android version**
Android 10 

**Device**
LG K40S

**Steps to Reproduce**
Steps to reproduce the error:
1. Open YTVanced
2. Wait for load
3. No connection error

**Expected behavior**
Load videos, and stuff without problems and under 5 seconds.

![Screenshot_20210619-225323](https://user-images.githubusercontent.com/54007604/122659763-6c08bc00-d151-11eb-9dc8-2a6356b83efd.png)
Logcat(need to wait for my phone decide show the confirmation to allow my pc... and idk when it want to do it)

**Comment by MisterMustache** [comment] 2021-06-20 09:58
Had the same issue. 
What solved It for me was uninstalling Vanced MicroG, clearing cache and data of Youtube Vanced and reinstalling Vanced MicroG.
Hope this helps.

**Comment by milindgoel15** [comment] 2021-06-20 11:34
Duplicate of #786

**Closed by milindgoel15** 2021-06-20 11:34 UTC
Labels: bug
