### ISSUE TITLE
[Bug] You're offline, Device Infinix Hot 10

### ISSUE THREAD

**Issue by SyedTahseen** [YTVanced/Vanced#894] opened 2021-05-30 10:04 UTC
**Description**
I've tried my all best to install, reinstall, update, clear storage etc, but I'm failed to use YoutubeVanced on my device. It always shows error that "You're offline". When I reinstall MicroG, and YoutubeVanced app, it works fine for first time, but after that it shows me error that "You're offline". My internet and everything is working fine.
Kindly, fix it.

**Variant**
Non-Root

**Vanced version**
16.16.38 

**Android version**
Android 10

**Device**
Infinix Hot 10

Error Image:
![Screenshot_20210530-144431](https://user-images.githubusercontent.com/53108646/120099925-8dc8e180-c157-11eb-92fc-f2bfc0963c33.png)

**Comment by milindgoel15** [comment] 2021-05-30 14:00
Duplicate of #786

**Closed by milindgoel15** 2021-05-30 14:00 UTC
Labels: bug
