### ISSUE TITLE
READ THIS IF VANCED/MUSIC ISNT LOADING OR YOU CANT LOGIN

### ISSUE THREAD

**Issue by Vendicated** [YTVanced/Vanced#396] opened 2021-01-28 18:18 UTC
READ THIS IF YOU EITHER CAN'T LOGIN TO YTMUSIC OR VANCED IS LOADING INDEFINITELY

This is a bug with microg. To solve it, follow [this guide](https://github.com/Vendicated/Vanced/blob/master/Guides/VancedLoadingFix.md)

**Comment by ackr-8** [comment] 2021-01-29 13:42
Fix not working in android 11

**Comment by milindgoel15** [comment] 2021-01-30 06:57
> Fix not working in android 11. 
> Tested on Lineage OS 18.1.

Are you using root version on microG core based los?

**Comment by Vendicated** [comment] 2021-01-30 08:25
> > Fix not working in android 11.
> > Tested on Lineage OS 18.1.
> 
> Are you using root version on microG core based los?

I'm using system microg and Root vanced works fine with it as long as you do the same fix as you would do with nonroot. He probably did something wrong 😅

**Comment by milindgoel15** [comment] 2021-01-30 08:29
> I'm using system microg and Root vanced works fine with it as long as you do the same fix as you would do with nonroot. He probably did something wrong 😅

Actually root yt vanced works but root yt music doesn't.

**Comment by ackr-8** [comment] 2021-01-30 11:05
I'm using non root vanced MicroG

**Comment by ackr-8** [comment] 2021-01-30 11:17
The problem is account switching is not working. All the accounts are still present as just downgrading to 15.43 fixes the issue.

**Comment by milindgoel15** [comment] 2021-01-30 11:35
Yes that's known

**Comment by ackr-8** [comment] 2021-01-31 08:53
Will it be fixed or is there a workaround ??

**Comment by milindgoel15** [comment] 2021-01-31 08:56
> Will it be fixed or is there a workaround ??

There's no fix for it. It's an upstream microG bug and only developers of microG can fix it. You can find the issue above if you want to contribute by fixing the problem. Everyone will appreciate it 

Otherwise be patient 👍

**Comment by ackr-8** [comment] 2021-01-31 12:50
Ok thanks for the prompt reply. 👍

**Comment by AdiPathak97** [comment] 2021-02-12 10:12
> READ THIS IF YOU EITHER CAN'T LOGIN TO YTMUSIC OR VANCED IS LOADING INDEFINITELY
> 
> This is a bug with microg. To solve it, follow [this guide](https://github.com/YTVanced/Vanced/blob/master/Guides/VancedLoadingFix.md)

Guide link is a 404. Any help with this issue?

**Comment by Radder124** [comment] 2021-02-12 10:44
See https://github.com/YTVanced/VancedMicroG/issues/87#issuecomment-770277776

**Comment by AdiPathak97** [comment] 2021-02-12 11:02
> See [YTVanced/VancedMicroG#87 (comment)](https://github.com/YTVanced/VancedMicroG/issues/87#issuecomment-770277776)

thanks @Radder124, the solution there worked

**Comment by VancedOfficial** [comment] 2021-02-24 18:55
Regarding the accounts list being empty. It's caused by this issue: https://github.com/microg/GmsCore/issues/1373

**Comment by LaurenceBarnes** [comment] 2021-04-23 11:43
I also encountered that issue and downgrading to YouTube Vanced 15.43.32 solved it.

**Comment by KevinX8** [comment] 2021-04-26 20:03
fixed in v16.14.34

**Closed by KevinX8** 2021-04-26 20:03 UTC
Labels: documentation
