### ISSUE TITLE
[Bug] Black notification bar and black line at the bottom when playing a video.

### ISSUE THREAD

**Issue by DolanD2** [YTVanced/Vanced#1529] opened 2022-01-15 16:34 UTC
![Screenshot_20220109-125128](https://user-images.githubusercontent.com/84463839/149629699-f8931878-d443-4f16-8a10-98f238350142.png)

Not a huge issue, but still, it stings my eyes. That occurs only in white mode.
Samsung Galaxy A30s android 11, One UI 3.1

**Comment by milindgoel15** [comment] 2022-01-15 17:40
Duplicate of #1280

**Comment by milindgoel15** [comment] 2022-01-15 17:40
The second one is surely a OneUI bug or its just google being google again.

**Closed by milindgoel15** 2022-01-15 17:40 UTC
