### ISSUE TITLE
[Bug]: Ads have started displaying in Youtube Vanced 

### ISSUE THREAD

**Issue by immanuelgracious** [YTVanced/Vanced#1376] opened 2021-11-10 08:16 UTC
**Bug description**
Ads have somehow managed to pop up on the app and not only the one below and numerous more in areas like under the video, Home screen just like normal YouTube but not in the video itself though 

**Variant**
Non-Root

**Vanced version**
V16.29.39

**Android version**
Android 10 go edition

**Device**
Device: Infinix Hot 9 play
Operating System:  XOS Dolphin V6.2.0

**Steps to Reproduce**
 No particular steps 

**Expected behavior**

Ads have somehow managed to pop up on the app and not only the one below and numerous more in areas like under the video, Home screen just like normal YouTube but not in the video itself though 

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

![Screenshot_20211110-110323](https://user-images.githubusercontent.com/91005503/141075471-a955f506-7e3d-4efb-9eab-7f66dcaa4221.png)

**Comment by milindgoel15** [comment] 2021-11-10 12:32
Duplicate of #1314

**Closed by milindgoel15** 2021-11-10 12:32 UTC
Labels: bug
