### ISSUE TITLE
[Bug] Minimize/Maximize window disappears on full-screen

### ISSUE THREAD

**Issue by antisocrates** [YTVanced/Vanced#1408] opened 2021-11-21 14:40 UTC
**Bug description**
When I make a video full screen the little icon on bottom right corner for maximizing window disappears (which I also use to minimize) 

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
Android 11 - MIUI 12.5.4 stable

**Device**
Redmi note 9 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click full screen button, at button right corner of video 
3. .notice it disappears in full screen 

**Expected behavior**
The maximize/minimize button should be there as is in normal YouTube. 

**Images**

![Screenshot_2021-11-21-16-34-16-863_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/69071420/142766423-b0420cbf-d1fa-4327-8523-f8ef037c9454.jpg)

![Screenshot_2021-11-21-16-34-08-838_com.vanced.android.youtube.jpg](https://user-images.githubusercontent.com/69071420/142766428-f9b40839-6f8b-46f1-8fff-a02184a204d5.jpg)

**Comment by figos33** [comment] 2021-11-21 14:47
I am missing that fullscreen button as well, makes unmaxing the window awkward.

**Comment by Loganavter** [comment] 2021-11-22 13:16
You can remove this icon altogether along the way

Settings -> Advanced Settings -> Appearance Settings
And then click on the "Watermark"

**Comment by antisocrates** [comment] 2021-11-22 20:05
> You can remove this icon altogether along the way
> 
> Settings -> settings Vanced -> Appearance Settings (or Interface Settings. I do not know how it is properly called in the English interface, but I think you will understand.)
> And then click on the "Watermark"

I don't want to remove it. The opposite. I want to see it in full screen also.

**Comment by milindgoel15** [comment] 2021-11-23 04:05
Try reinstalling vanced and see if it resolves your issue. Meanwhile, we are closing this issue.

If you are still facing this issue, feel free to report back here.

**Closed by milindgoel15** 2021-11-23 04:05 UTC
Labels: bug

**Comment by huskarlx** [comment] 2021-11-23 08:56
> Try reinstalling vanced and see if it resolves your issue. Meanwhile, we are closing this issue.
> 
> If you are still facing this issue, feel free to report back here.

I am facing the same issue on the latest version, using miui. Why are you closing the bug before investigating it?

**Comment by milindgoel15** [comment] 2021-11-23 09:02
I am not saying if u are facing this on the latest version. I am telling you to reinstall vanced again freshly and then check if the issue persists. 

> Why are you closing the bug before investigating it?

Because the bug exists only on your end, not in vanced. The full-screen button appears and works fine for us.

**Comment by antisocrates** [comment] 2021-11-27 03:12
> I am not saying if u are facing this on the latest version. I am telling you to reinstall vanced again freshly and then check if the issue persists. 
> 
> > Why are you closing the bug before investigating it?
> 
> Because the bug exists only on your end, not in vanced. The full-screen button appears and works fine for us. 
> 
> ![Screenshot_2021-11-23-14-31-06-38.jpg](https://user-images.githubusercontent.com/45682747/142996135-b4400212-f886-4ac0-97a9-8f7a45ffdae1.jpg)
> 
> ![Screenshot_2021-11-23-14-31-14-99.jpg](https://user-images.githubusercontent.com/45682747/142996153-a1466662-3dea-4bb6-a4fd-f950bc408de3.jpg)

 I did as you said and more. 

Cleared data, uninstalled vanced manager, music, YouTube. Rebooted, re-downloaded manager and installed everything.
MIUI optimizations are of and still on full-screen the little icon on the bottom right corner is invisible.

It's a bug on your end, that arises when certain conditions are met. Investigate it and fix it.

**Comment by milindgoel15** [comment] 2021-11-27 03:15
Can't help if we can't reproduce it in the first place.

**Comment by antisocrates** [comment] 2021-11-27 10:45
> Can't help if we can't reproduce it in the first place. 

Isn't there some debug output this thing produces? Something obviously doesn't load or its themed weirdly.

**Comment by antisocrates** [comment] 2021-11-29 06:29
Update 2: After rebooting again, the icon disappeared again...
