### ISSUE TITLE
[YTvanced features minimalist and simple for productivity]

### ISSUE THREAD

**Issue by LMWH03** [YTVanced/Vanced#1067] opened 2021-07-08 16:18 UTC
**Description**
this can be a little tricky, but a remove recommendations function would be nice and remove the explore button, or at least the trending ones.

Something like this chrome extension: 

https://chrome.google.com/webstore/detail/unhook-remove-youtube-rec/khncfooichmfjbepaaaebmommgaepoid?hl=en

**Comment by milindgoel15** [comment] 2021-07-08 16:32
Duplicate of #334

**Closed by milindgoel15** 2021-07-08 16:32 UTC
Labels: enhancement
