### ISSUE TITLE
[Bug] here segregation is needed

### ISSUE THREAD

**Issue by Tarburt** [YTVanced/Vanced#1707] opened 2022-03-02 23:42 UTC
**Bug description:**
I think it is not a bug but more like a feature, your App cannot segregate between when I want to control the volume and when I want to scroll through the live comments. 

**Have you read vanced guides already? (YES/No)** YES
If your answer is no, please consider reading before creating this issue. The guides can be found in the readme section of this repository. 

**Variant:**
Non Root

**Vanced version:**
Latest for 3 March 2022

**Link used to download vanced:**
Vanced manager lastest

**Android version:**
Android 11 

**Device:**
Realme 8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Your settings should be able to increase or decrease volume by screen itself
3. Open a video which is being live telecast now try to open live comment section and as your volume option is on, if you touch your screen and basically cannot segregate between whether or not you are scrolling down( right hand side of the screen) for live comment section or, for volume.

**Expected behaviour:**
when I open a live comment section the screen volume feature should be auto disabled. And when I stop the live comments it should be back on. 

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._
![Screenshot_2022-03-03-05-03-34-45.jpg](https://user-images.githubusercontent.com/100755979/156467558-d6de51f6-f499-462d-b2ca-39c749c12386.jpg)

**Comment by milindgoel15** [comment] 2022-03-03 03:14
Duplicate of #889

**Closed by milindgoel15** 2022-03-03 03:14 UTC
Labels: bug
