### ISSUE TITLE
[Bug] YouTube won't run without Google Play services, which are not supported by your device

### ISSUE THREAD

**Issue by jedenastka** [YTVanced/Vanced#854] opened 2021-05-22 15:21 UTC
**Bug description**
This issue is the same as #201, which was closed for no reason.

Versions newer than 15.33.34 show an error on Android 11:

> YouTube won't run without Google Play services, which are not supported by your device.
> **OK**

Closing the message via clicking **OK** closes Vanced.

You can see the video on top autoplaying, so it's probably an artifical error made by Google and should be fixable. @puuuuh suggested that:
> Its because https://developer.android.com/about/versions/11/privacy/package-visibility, com.android.vending is not visible by default, need to add it to app manifest

Only happens on the root variant (mentioned by @imprezzion, not tested). Downgrading to 15.33.34 is a possible temporary workaround.

**Variant**
Root

**Vanced version**
15.38.35 - 16.16.38 (latest)

**Android version**
LineageOS 18.1 - Android 11

**Device**
Samsung Galaxy S5 (SM-G900F, klte)

**Steps to Reproduce**
1. Open the app

**Expected behavior**
No error, Vanced works as usual.

![Screenshot_20210522-171904_YouTube](https://user-images.githubusercontent.com/33988779/119231635-28a33980-bb22-11eb-90b5-e0c9685147ff.png)

(I cleaned app data before I took this screenshot, don't judge me. It's just what typically is on the Polish main page).

**Comment by milindgoel15** [comment] 2021-05-22 15:30
Because it's not vanced issue. Kindly use a better ROM or better gapps. We suggest using nikgapps if you are using a ROM without prebuilt gapps. Pls search your issues first before laying it out on vanced.

Duplicate of many issues. Pls do your homework properly

**Closed by milindgoel15** 2021-05-22 15:30 UTC
Labels: bug

**Comment by milindgoel15** [comment] 2021-05-22 15:31
![Screenshot_20210522-210023_YouTube.png](https://user-images.githubusercontent.com/45682747/119231933-cd347400-bb40-11eb-8c10-bf566138f1a9.png)
![Screenshot_20210522-210036_Settings.png](https://user-images.githubusercontent.com/45682747/119231940-d1609180-bb40-11eb-8ef2-7370ac070073.png)

**Comment by jedenastka** [comment] 2021-05-22 16:12
> Pls search your issues first before laying it out on vanced.
> Duplicate of many issues. Pls do your homework properly

I don't wanna be rude, but #201 is the only issue I was able to find:

![image](https://user-images.githubusercontent.com/33988779/119233269-8b97cf00-bb28-11eb-8690-7a22a7d0d14a.png)

And I searched A LOT, not only in this repo. I was trying to solve this for a week before creating this issue.

> Kindly use a better ROM or better gapps.

I don't use GApps, only MicroG, so that might be the problem.

Is there any particular reason you can't just delete this message? It would probably work, as I mentioned:
> You can see the video on top autoplaying, so it's probably an artifical error made by Google and should be fixable.
Or maybe you tried that and it didn't work?

**Comment by milindgoel15** [comment] 2021-05-22 16:33
>And I searched A LOT, not only in this repo. I was trying to solve this for a week before creating this issue. I found people experiencing the same problem, but no explanation nor a fix.
You look like you can actually read but ig you never bothered to search on our official discord or telegram or XDA.

>I don't use GApps, only MicroG, so that might be the problem.
yes, vanced wasn't made to run with microG. please upgrade to atleast pico gapps to use vanced or even official yt. I just wonder why u are here assuming you never checked official yt. The issue with google play services started with android 11 yes. but it was also fixed in the month of january on both parts (vanced team and gapps developers out there, one being nikgapps). the vanced team included the fix in vanced manager since it was a problem which occurs on installation, not in vanced. The play store force query had to forced while installing vanced. On the other hand, the same fix was submitted and given to all gapps developers. 

the issue is on your end and has to be fixed by you only by switching to gapps. Make sure u are using latest vanced manager from [official site](https://vancedapp.com). we already did our part long ago and mentioned the same in changelogs(perhaps u never read them)

>EDIT: Also, why can't I reopen my issue?
because it doesnt need to be opened again as its not vanced side issue.

**Comment by jedenastka** [comment] 2021-05-22 16:51
> You look like you can actually read but ig you never bothered to search on our official discord or telegram or XDA.

You are rude just for the sake of being rude.

I'm switching to NewPipe, at least their devs don't offend people for reporting an issue.

Thanks for the explanation anyways.

**Comment by milindgoel15** [comment] 2021-05-22 16:56
we are rude for saying its not vanced issue and that you never bothered to search our discord or tg or xda or read changelogs. what are u expecting us to do with your issue? make ur device magically work with yt vanced? damn lmao

yes go ahead to newpipe. u deserve it.

**Comment by jedenastka** [comment] 2021-05-23 09:43
I just wanted to point out that the person above is not only uncultured, but also incompetent:
> yes, vanced wasn't made to run with microG. please upgrade to atleast pico gapps to use vanced or even official yt. I just wonder why u are here assuming you never checked official yt.

![Screenshot_20210523-114149_YouTube](https://user-images.githubusercontent.com/33988779/119255414-03630980-bbbc-11eb-896c-b07f6a20119e.png)

It's funny to me that this is indeed an issue with Vanced.

**Comment by jedenastka** [comment] 2021-05-23 09:47
I made a comment right here, but I deleted it - I realized there is no sense in continuing this discussion.

This is for anybody that got an email because of it.
