### ISSUE TITLE
[Bug] No se puede instalar en dispositivos samsung

### ISSUE THREAD

**Issue by Jhoans104** [YTVanced/Vanced#1223] opened 2021-08-28 13:05 UTC
![Screenshot_20210828-075801_Vanced Manager](https://user-images.githubusercontent.com/89693252/131218899-be8369d4-33b7-44a3-aa49-f6ad1091383d.jpg)

**Comment by milindgoel15** [comment] 2021-08-28 14:14
Duplicate of #330

**Closed by milindgoel15** 2021-08-28 14:14 UTC
Labels: bug
