### ISSUE TITLE
[Idea] Increase playback speed to 3×

### ISSUE THREAD

**Issue by Isssuemaker** [YTVanced/Vanced#1109] opened 2021-07-25 10:54 UTC
Please increase playback speed to 3×

**Comment by milindgoel15** [comment] 2021-07-25 11:43
Duplicate of #82

**Closed by milindgoel15** 2021-07-25 11:43 UTC
Labels: enhancement

**Comment by Isssuemaker** [comment] 2021-07-25 15:39
> Duplicate of #82

The issue is already closed by a bot please reopen it
