### ISSUE TITLE
[Bug] Can't use the app

### ISSUE THREAD

**Issue by SweChiHD** [YTVanced/Vanced#787] opened 2021-05-06 22:07 UTC
**Bug description**
I was about to watch some videos but as soon as I started the app it said that I apperantly don't have any internet, so I decided to restart my phone and wifi but it still won't work, the regular YouTube app still works for me tho. 
BTW same goes for YouTube music vanced 

**Variant**
Non-Root
![Screenshot_20210506_235916_com vanced android youtube](https://user-images.githubusercontent.com/83790921/117371422-286f3100-aec8-11eb-93da-c578833c35af.jpg)

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Huawei p30 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment] 2021-05-07 01:39
Duplicate of #786

**Closed by milindgoel15** 2021-05-07 01:39 UTC
Labels: bug
