### ISSUE TITLE
[Idea] On/Off Toggle for Download video icon

### ISSUE THREAD

**Issue by dracula99gr** [YTVanced/Vanced#924] opened 2021-06-06 19:06 UTC
**Description**
I will never pay for youtube premium to download a video so I don't care to use that feature at all so I wouldn't like the icon to take up space so I have to scroll to share a video that allows you to share clips off it.
![20210606_220536](https://user-images.githubusercontent.com/20153526/120936951-5a67f300-c713-11eb-9bb7-d5666993b791.png)

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment] 2021-06-07 02:41
Duplicate of #178

**Closed by milindgoel15** 2021-06-07 02:41 UTC
Labels: enhancement
