### ISSUE TITLE
[Bug] App does not recognise Internet connection 

### ISSUE THREAD

**Issue by nearlySplat** [YTVanced/Vanced#1257] opened 2021-09-12 13:26 UTC
**Bug description**
Vanced shows a "connect to the Internet" prompt even when connected to a Wi-Fi network. Stock YouTube app (latest, non-Beta, downloaded from Google Play) does not have this issue.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
Samsung Galaxy Tab A

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Observe

**Expected behavior**
Vanced shows a normal front page populated by recommended or trending videos

**Image**
![Network is not recognised by Vanced but is present in status bar](https://user-images.githubusercontent.com/67709748/132989431-7ff03314-dece-4e4d-9d0c-3f77ac12e23d.jpg)

The network is available, as shown in the status bar in the image above, but Vanced does not recognise it.

**Comment by milindgoel15** [comment] 2021-09-12 13:31
Duplicate of #786

**Closed by milindgoel15** 2021-09-12 13:31 UTC
Labels: bug
