### ISSUE TITLE
Implement open source "Return Youtube Dislike" extention in Youtube Vanced

### ISSUE THREAD

**Issue by natanael9o** [YTVanced/Vanced#1428] opened 2021-11-30 12:30 UTC
There is an extention for chromium and firefox that is called Return YouTube Dislike (https://github.com/Anarios/return-youtube-dislike) (https://www.returnyoutubedislike.com) and that makes the dislike count visable again. You have integrated sponsorblock in the past and this is now needed when Youtube have hidden the count if you don't have this extention.

I would like it to be implemented becasue I feel it is a very important tool to find what might not be a good video accoring to the majority.

**Comment by milindgoel15** [comment] 2021-11-30 12:31
Yea we know. Just stop making duplicates now.

**Comment by milindgoel15** [comment] 2021-11-30 12:31
Duplicate of #1394

**Closed** 2021-11-30 12:32 UTC
Labels: enhancement
