### ISSUE TITLE
[Bug] Full screen reverting 

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1725] opened 2022-03-06 11:55 UTC
**Bug description:**

Whenever I use slide up gesture to get the YouTube video to full screen it just reverts it to vertical one and it's so annoying that I have to do it again. 

**Have you read vanced guides already? Yes

**Variant:**
Non-Root

**Vanced version:**
17.03.38

**Link used to download vanced:**
 https://vancedapp.com/

**Android version:**
Android 12

**Device:**
Google Pixel 6 XL

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video
3. Use slide up gesture (quickly slide finger from video to the top of the screen) 

**Expected behaviour:**

It should open YouTube in the horizontal view and stay there without automatically returning to vertical view. 

https://user-images.githubusercontent.com/29215437/156921945-5710ef5a-2525-4bcc-b9d5-5bb7704af591.mp4

**Comment by milindgoel15** [comment] 2022-03-06 16:27
First, that's not pixel 6 in any form lol
Second, duplicate of #1560

**Closed by milindgoel15** 2022-03-06 16:27 UTC
Labels: bug
