### ISSUE TITLE
[Bug] No Connection 

### ISSUE THREAD

**Issue by ES1806** [YTVanced/Vanced#1177] opened 2021-08-14 08:45 UTC
**Bug description**
When I open the app it only says "no connection". 

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
Android 10

**Device**
Huawei P Smart 2019

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behavior**
I expect the app to open normally and show me the YouTube content, but I can only see "no connection". 
This is not a result of a missing internet connection. The standard YouTube app works without problems.

**Comment by milindgoel15** [comment] 2021-08-15 17:32
duplicate of #786

**Closed by milindgoel15** 2021-08-15 17:32 UTC
Labels: bug
