### ISSUE TITLE
[Idea] Backup/restore settings

### ISSUE THREAD

**Issue by zheka006** [YTVanced/Vanced#353] opened 2021-01-18 17:08 UTC
**Description**
Allow the users to create backup vanced settings to fast set up. In my opinion it will be useful for ROM devs or people who often change ROMs. Maybe you can also add a dialog what you want to backup (codec, video, ads, layout, misc, exoplayer buffer settings)

Something similar is in newpipe's content settings
![Screenshot_20210118-190651_NewPipe~2](https://user-images.githubusercontent.com/58698398/104944829-72d3ad00-59c0-11eb-800b-b15ce0ba1093.png)

**Comment by Vendicated** [comment] 2021-01-28 18:37
Duplicate of https://github.com/YTVanced/Vanced/issues/347

**Closed by Vendicated** 2021-01-28 18:37 UTC
Labels: enhancement
