### ISSUE TITLE
[Bug] Chromecast casting

### ISSUE THREAD

**Issue by titan9064** [YTVanced/Vanced#757] opened 2021-05-01 18:08 UTC
**Bug description**
Whenever I trying to connect to Chromecast, Vanced telling me to update Google Services

**Variant**
Non-Root/

**Vanced version**
16.16.38 - Build - 02.18.210500

**Android version**
Android 10

**Device**
Xiaomi Mi Max 3

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Open any video
3. Try to cast any video

**Expected behavior**
It should start casting on a TV (Chromecast)

**Comment by milindgoel15** [comment] 2021-05-02 03:09
Duplicate of #688

**Closed by milindgoel15** 2021-05-02 03:09 UTC
Labels: bug
