### ISSUE TITLE
[Idea] Bypassing age restrictions mpv-style

### ISSUE THREAD

**Issue by VictorGamerLOL** [YTVanced/Vanced#1289] opened 2021-09-24 16:04 UTC
**Description**
So I think we all know about the new age verification Google put in place for YouTube where they either demand your credit card or ID.
I suggest implementing a 3rd button when you stumble upon an age restricted video in the prompt that says cancel or verify age, that button being "Play in external player".
What would this do is basically use youtube-dl to fetch the video and play it. I do not know on what you play it, maybe do some magic to make it look like the youtube player or just straight up fork MPV, but please make it so I do not have to hand over my credit card or ID (definetely existent) to Google because, well, it's Google.
Or the second option is somehow getting tampermonkey working and use one of the scripts for that.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment] 2021-09-24 17:02
Duplicate of #173

**Closed by milindgoel15** 2021-09-24 17:02 UTC
Labels: enhancement

**Comment by VictorGamerLOL** [comment] 2021-09-24 17:11
It is literally so easy to get it done with youtube-dl
literally grab the link, run it through youtube-dl and bam you got a video downloaded. Delete it after watching and its like it never happened. So do not rush to just refer this as a duplicate and have a listen please :<

**Comment by milindgoel15** [comment] 2021-09-24 17:14
You are missing one major and IMPORTANT point. As soon as you implement anything similar to youtube downloader for any sort of feature even if that bypasses age verification, google is gonna put guns on your head and vanced team. Do you want that? We don't want it so please do your research before recommending things like this...

**Comment by VictorGamerLOL** [comment] 2021-09-24 17:15
So that is why youtube-dl is constantly being legally chased? Surprised MPV isn't :/
