### ISSUE TITLE
[Bug] YT Vanced keeps showing that I have no internet connection even when I do. I tried watching a recently watched video and it works just fine but at the home screen and in subscription, it says that I am offline.

### ISSUE THREAD

**Issue by Kitty769** [YTVanced/Vanced#1419] opened 2021-11-26 02:59 UTC
**Bug description**
It says that I am offline even when I have internet connection in every other app. It would allow me to watch recently watched videos but won't let me search, view home page and subscribe page

**Variant**
Non-Root/Root

**Vanced version**
16.29.39

**Android version**
Android 11 

**Device**
Samsung Galaxy S10 5g

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Be able to use the app in online mode but showed that I was offline instead

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._
![Screenshot_20211126-105057](https://user-images.githubusercontent.com/95062313/143520074-229814e3-6dba-4138-99a6-65da6e172afb.jpg)

**Comment by milindgoel15** [comment] 2021-11-26 09:31
Duplicate of #786

**Closed by milindgoel15** 2021-11-26 09:31 UTC
Labels: bug
