### ISSUE TITLE
[Idea] enhancing/customising the YouTube share menu

### ISSUE THREAD

**Issue by iam-Ameena** [YTVanced/Vanced#936] opened 2021-06-08 05:59 UTC
**Description**
there should be a feature to customize the share menu in the app, so I don't have to scroll through many apps to find an app(like newpipe) to select. Like pinning and hiding the app form the menu.

_Unlike most other apps YouTube share menu is exclusively to YouTube app and it doesn't use the default share menu of os, so it is unrelated to os or rom._

[Sharedr](https://play.google.com/store/apps/details?id=com.rejh.sharedr) is an example of how you can implement it, but it doesn't work on YouTube app.

I would like this to be implemented in both yt vanced and ytmusic vanced, if possible.

Thanks.

**Comment by milindgoel15** [comment] 2021-06-08 09:24
Duplicate of #776

**Closed by milindgoel15** 2021-06-08 09:24 UTC
Labels: enhancement
