### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by Mik39907** [YTVanced/Vanced#1045] opened 2021-07-03 08:36 UTC
**Description**
Anyone else app says its Offline?

**Comment by milindgoel15** [comment] 2021-07-03 09:21
Duplicate of #786

Start reading guides instead of creating duplicates

**Closed by milindgoel15** 2021-07-03 09:21 UTC
Labels: question

**Comment by Mik39907** [comment] 2021-07-03 09:40
> Duplicate of #786
> 
> Start reading guides instead of creating duplicates

yea the problem is there was no update and it worked fine yesterday and before that and before that etc.. but sure ill reinstall it
