### ISSUE TITLE
[Bug] It keeps pushing the same notifications 

### ISSUE THREAD

**Issue by Sneffel** [YTVanced/Vanced#1113] opened 2021-07-26 18:28 UTC
<-- MANAGER/MICROG/VANCED MUSIC ISSUES DO NOT BELONG HERE, READ THE README FOR MORE INFO -->

**Bug description**
It keeps pushing the same notifications. I wiped them, I restarted the phone, cleared the cache, reinstalled the latest version form the manager. 

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
Android 10

**Device**
moto g(9) play

**Steps to Reproduce**
Steps to reproduce the error:
1. Leave it open
2. Every minute or so the same notifications keep popping up
3. ....
4. Fix it please?

**Expected behavior**
once deleted they should NOT appear again

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._
Oh god I'm so pissed right now

**Comment by milindgoel15** [comment] 2021-07-27 06:16
Duplicate of #1107

**Closed by milindgoel15** 2021-07-27 06:16 UTC
Labels: bug
