### ISSUE TITLE
[Idea] share video with timestamp

### ISSUE THREAD

**Issue by eldon97** [YTVanced/Vanced#299] opened 2020-12-30 08:26 UTC
add an option to share(copy link) with a timestamp. I mostly watch youtube at my phone and often I want to share the link with a timestamp to my friend via chatting app. it will be annoying if i need to go to my pc only for getting the link, I know we can add this " ?t=#m##s" to the link, but it will be more convenient if vanced add the option copy link with the current timestamp, maybe in the share dialogue. thank you

**Comment by AinzTheSupremeOne** [comment] 2020-12-30 08:39
Implemented in beta, wait for an update.

**Comment by shivasagarrao** [comment] 2020-12-31 16:47
Duplicate of #206 
@VancedOfficial commented [here](https://github.com/YTVanced/Vanced/issues/284#issuecomment-750256619) regarding this issue.

**Comment by Vendicated** [comment] 2021-01-28 18:35
Added. Make sure to enable it in Vanced Settings > Misc

**Closed by Vendicated** 2021-01-28 18:35 UTC
Labels: enhancement
