### ISSUE TITLE
[Bug] YouTube vanced acting like it has no connection 

### ISSUE THREAD

**Issue by Kn07-1** [YTVanced/Vanced#1063] opened 2021-07-07 20:10 UTC
**Bug description**
Youtube vanced won't connect to server? It's like there's no internet connection yet there is I've tried reinstalling to no avail can reproduce on 2 devices after reboot and cach clearing 

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
8 and 11

**Device**
 BlackBerry key2 and Samsung tab s6lite

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behavior**
Able to access online videos

**Comment by sudo-nautilus** [comment] 2021-07-08 01:41
Bruh

**Comment by sudo-nautilus** [comment] 2021-07-08 01:41
Check #396

**Comment by milindgoel15** [comment] 2021-07-08 03:44
Duplicate of #786

**Closed by milindgoel15** 2021-07-08 03:44 UTC
Labels: bug
