### ISSUE TITLE
[Idea] Option to open shorts as regular videos

### ISSUE THREAD

**Issue by dinmukhamedm** [YTVanced/Vanced#1149] opened 2021-08-08 08:33 UTC
**Description**
If a video is a YouTube shorts (for example, found from the search menu), then a user can click the three dots button to select "open as a regular video" in order not to open it in the ugly useless TikTok-style player. The proposed location of the button can be seen in the screenshot below. As far as I know, this can be achieved by simply changing the request URL from `youtube.com/shorts/[videoID]` to `youtube.com/watch?v=[videoID]`.

![image](https://user-images.githubusercontent.com/47117969/128626144-92e3e94e-af84-48e8-86e5-9a67b6bc3c27.png)

_Option to do that by default_
Ideally, I would love to see a setting toggle in the Settings menu that would allow to open shorts as usual videos by default. It could possibly be the Android style 1 out of 3 setting of "Open as shorts", "Open as video", "Always ask", although it seems like that would go against the "on/off toggle" style for most other Vanced features

**Comment by milindgoel15** [comment] 2021-08-08 09:40
Duplicate of #316

**Closed by milindgoel15** 2021-08-08 09:40 UTC
Labels: enhancement
