### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by jpelneko** [YTVanced/Vanced#853] opened 2021-05-22 07:59 UTC
**Bug description**
Vanced won't allow itself to cast onto my TV, claims my Google Play isn't up to date but I have made sure it was. Both MicroG and Vanced are up to date as well. 

**Variant**
Non-Root/Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S21 Ultra

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on Cast button on the app
3. Met with error message saying to update Play Store.

**Expected behavior**
This happened yesterday and I uninstalled the program and reinstalled both to be sure, it worked all the way til just now after getting home from work tonight.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment] 2021-05-22 08:54
Duplicate of #688

**Closed by milindgoel15** 2021-05-22 08:54 UTC
Labels: bug
