### ISSUE TITLE
[Idea] Use system share dialog

### ISSUE THREAD

**Issue by opekope2** [YTVanced/Vanced#1676] opened 2022-02-23 22:21 UTC
**Description**
When I try to share something to discord for example, it is always located at the bottom or is randomly moved around, and is not easy to find. Using the system share dialog instead of YouTube's custom one would be easier to use, it would provide the same sharing user experience for every application. It also prioritizes most common apps for quick access and offers more features.

**Comment by milindgoel15** [comment] 2022-02-24 03:15
Duplicate of #776

**Closed by milindgoel15** 2022-02-24 03:15 UTC
Labels: enhancement
