### ISSUE TITLE
[Bug]YT/YT Music is not working after update on Android 12

### ISSUE THREAD

**Issue by Sadowskyy** [YTVanced/Vanced#1575] opened 2022-02-03 21:51 UTC
**Bug description:**
Yesterdat I updated my phone to android 12, after that I wanted to listen to music or watch something on YT. When I tried to open app it cannot connect to network ;/

**Have you read vanced guides already? (YES/No)**
Yes, no solution.

**Variant:**
Non-Root

**Vanced version:**
Replace me with the exact version of vanced you are using. It is mandatory to report issues from the latest available versions only. For example, v16.49.37

**Link used to download vanced:**
[Replace here with the source/link you used to download and install on your device. 
](https://vancedapp.com/)

**Android version:**
Android 12

**Device:**
Samsung Galaxy S20 FE with snapdragon CPU

**Steps to Reproduce**
1. Open Youtube vanced or Youtube Music.
2. When I want do anything application cannot get network connection.

**Expected behaviour:**
I only want to watch videos/listen to music.

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._

https://user-images.githubusercontent.com/58751887/152434960-672b4bd8-369e-4031-a5ab-08023327d6b5.mp4

**Comment by milindgoel15** [comment] 2022-02-04 03:41
Duplicate of #786

**Closed by milindgoel15** 2022-02-04 03:41 UTC
Labels: bug
