### ISSUE TITLE
[Idea] Copy YouTube comments

### ISSUE THREAD

**Issue by FBIAgent05** [YTVanced/Vanced#965] opened 2021-06-14 08:50 UTC
**Description**
Ability to copy YouTube comments, that's it

**Comment by WeMayNeverKnow** [comment] 2021-06-15 08:49
Description too would be nice

**Comment by oSumAtrIX** [comment] 2021-07-24 18:06
I would add an app wide copy text support to this idea so you are not limited in being able to select-copy comments

**Comment by milindgoel15** [comment] 2021-07-25 04:03
Duplicate of #642

**Closed by milindgoel15** 2021-07-25 04:03 UTC
Labels: enhancement
