### ISSUE TITLE
[Bug] Application crashes 

### ISSUE THREAD

**Issue by Aldmors** [YTVanced/Vanced#958] opened 2021-06-13 08:38 UTC
**Variant**
Non-Root

**Vanced version**
v16.16.38

**Android version**
7.1.1

**Device**
ZTE Nubia Z17 Lite

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app

**Expected behavior**

The application closes after launch

https://user-images.githubusercontent.com/48130167/121800621-549e7000-cc33-11eb-8112-ba4ab3e995e9.mp4

**Comment by milindgoel15** [comment] 2021-06-13 08:41
Duplicate of #954

**Closed by milindgoel15** 2021-06-13 08:41 UTC
Labels: bug
