### ISSUE TITLE
[Bug] yt shows no connection

### ISSUE THREAD

**Issue by AnD418** [YTVanced/Vanced#846] opened 2021-05-21 10:05 UTC
**Bug description**
Sometimes ytvanced shows no connection even when the internet is on and working reopening the app fixes it but it happens everytime after opening

**Variant**
Non-Root

**Vanced version**
16.16.38- Build - 01.51

**Android version**
Android 11- R

**Device**
Xiaomi A3

**Steps to Reproduce**
Steps to reproduce the error:
Almost every time when app is opened

**Expected behavior**
YouTube should load but it shows no connection

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_20210521-153159](https://user-images.githubusercontent.com/69518879/119120668-29689c80-ba4a-11eb-9d27-5366a582400e.png)

**Comment by milindgoel15** [comment] 2021-05-21 12:12
Duplicate of #786

**Closed by milindgoel15** 2021-05-21 12:12 UTC
Labels: bug
