### ISSUE TITLE
[Bug] Swiping down to reload the home feed does not work

### ISSUE THREAD

**Issue by very-lame-username** [YTVanced/Vanced#1156] opened 2021-08-09 05:57 UTC
**Bug description**
On the official YT app, you can swipe down from the top of the home tab in order to reload the feed with new videos. On YT Vanced, this does not work, however it does work in the subscriptions and library tabs.

Interestingly, when signed into incognito/signed out this bug does not occur.

**Variant**
Non-Root

**Vanced version**
16.29.39

**Android version**
Android 11

**Device**
Google Pixel 4

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Ensure you are signed in
3. Swipe down from just below the menu containing the 'explore' button
4. The overscroll indicator (faint semicircle) appears, but the page does not refresh

**Expected behavior**
- Reload circle indicator appears as you swipe down
- The page reloads

**Comment by milindgoel15** [comment] 2021-08-09 06:07
**Start reading changelogs!!**

duplicate of #252

**Closed by milindgoel15** 2021-08-09 06:07 UTC
Labels: bug
