### ISSUE TITLE
[Idea] Option to disable autoplay in playlists

### ISSUE THREAD

**Issue by supernoodled** [YTVanced/Vanced#1273] opened 2021-09-19 09:54 UTC
Let's say you are using a playlist to play videos. As soon as the previous video ends, it will automatically autoplay the next one. 

This is good for music playlists obviously, but when it's about regular videos, such as a video series, or just some random content, especially when using SponsorBlock can end up making you skip right to the next video in the list instantly (that you may have already seen before, and or don't want to watch etc) without you even having the time to pause the video, make a comment, etc.

So, I'd like there to be an optional toggle button like the autoplay button if possible during playlists, where you can disable a playlist from autoplaying the next video (or at least do like a 5 sec timer how the normal autoplay button functions when not using a playlist).

**Comment by madgoatz** [comment] 2021-09-19 15:35
duplicate of #1079

**Closed** 2021-09-20 03:13 UTC
Labels: enhancement
