### ISSUE TITLE
[Idea] YouTube Vanced for Android TV

### ISSUE THREAD

**Issue by moesadah** [YTVanced/Vanced#448] opened 2021-02-10 18:09 UTC
**Description**
First off, thanks for the Vanced team for their fantastic app which I have recommended to everyone I know who owns an Android device. 

Now back to the topic, I recently bought an Android TV Box (the Nvidia Shield TV Pro) and I was surprised that YouTube Vanced apps don't work on android TV. There's a modified YouTube app called Smart YouTube TV which blocks ads on YouTube, but it has many bugs and it's nowhere near as good as YouTube Vanced. Therefore, could you please add support for Android TV? I don't mind paying for it. I really hope you consider my suggestion because we need a YouTube Vanced app on TV as there's nothing that blocks ads and works well at the moment. 

Thanks!

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by andrewpros** [comment] 2021-02-17 21:38
I have it installed on android tv and it works.

**Comment by moesadah** [comment] 2021-02-18 03:17
You can install it but it is not useable because as you said you can't scroll as it is not designed to be working on Android TV which is what this post is about, to get it working on Android TV.

**Comment by gghhkm** [comment] 2021-02-18 08:04
This isn't going to happen. It's already been started by Xinto that they won't be doing this.
Just use blokada or something.

**Comment by gghhkm** [comment] 2021-02-18 08:07
> I have it installed on android tv and it works.
> 
> The only issue is, remote control up/down is not scrolling the video list.

Use a mouse.

**Comment by andrewpros** [comment] 2021-02-18 15:04
I was answering to OP that vanced do WORK 100% on android tv as he stated it is not working, thats not true.

It is not entirely true its not designed for android tv, well the UI design yes, but vanced has great UI that is universal i would say.

Its not the looks i care, its really fine.

I already have and use air mouse remote control so it is not that huge issue, but man, it would be  so much easier if those up/down buttons worked on the main video list.

They only issue is up/down buttons and only them.

Android by design supports automatically remote controls, the keys are send to the app without doing anything in the app, this is described in google documentation, it works out of the box and they are send to vanced.

Vanced supports remote controls, play/pause works, up/down WORKS...

THE ISSUE IS

Up/down keys dont works as intended only on the main video list for unknown reason

IT WORKS, sometimes it needs to the get focus with the mouse pointer, sometimes be in the right spot, but it works on:

- the side related movies on player page
- search page
- channel account main tab and videos tab
- also in some degree on the discovery tab

BUT IT DOESN'T WANT TO WORK IN MAIN APP TAB and i dont know why

Its like something is preventing it from scrolling to the next row of videos, i did detailed tests, u can hear the button pressed sound so it is receiving it, u can see it tries to scroll, the view moves some pixel up/down if the is some uneven room let, but wont scroll to the next row.

If u scroll on purpose so the view shows some part of the videos in the next row then pressing down will scroll fully to the next videos row, this works both directions, but then it stops again.

So i would say this is a BUG, the whole app supports the remote buttons in many places, but the main app video list is just bugged.

I think vanced devs could really investigate it, something is not right.

If i can help in any way to fix it then tell me how, with this fixed it would be the prefect app, way better than any ATV yt app.

**Comment by gghhkm** [comment] 2021-02-18 15:05
> I was answering to OP that vanced do WORK 100% on android tv as he stated it is not working, thats not true.
> 
> It is not entirely true its not designed for android tv, well the UI design yes, but vanced has great UI that is universal i would say.
> 
> Its not the looks i care, its really fine.
> 
> I already have and use air mouse remote control so it is not that huge issue, but man, it would be so much easier if those up/down buttons worked on the main video list.
> 
> They only issue is up/down buttons and only them.
> 
> Android by design supports automatically remote controls, the keys are send to the app without doing anything in the app, this is described in google documentation, it works out of the box and they are send to vanced.
> 
> Vanced supports remote controls, play/pause works, up/down WORKS...
> 
> THE ISSUE IS
> 
> Up/down keys dont works as intended only on the main video list for unknown reason
> 
> IT WORKS, sometimes it needs to the get focus with the mouse pointer, sometimes be in the right spot, but it works on:
> 
> * the side related movies on player page
> * search page
> * channel account main tab and videos tab
> * also in some degree on the discovery tab
> 
> BUT IT DOESN'T WANT TO WORK IN MAIN APP TAB and i dont know why
> 
> Its like something is preventing it from scrolling to the next row of videos, i did detailed tests, u can hear the button pressed sound so it is receiving it, u can see it tries to scroll, the view moves some pixel up/down if the is some uneven room let, but wont scroll to the next row.
> 
> If u scroll on purpose so the view shows some part of the videos in the next row then pressing down will scroll fully to the next videos row, this works both directions, but then it stops again.
> 
> So i would say this is a BUG, the whole app supports the remote buttons in many places, but the main app video list is just bugged.
> 
> I think vanced devs could really investigate it, something is not right.
> 
> If i can help in any way to fix it then tell me how, with this fixed it would be the prefect app, way better than any ATV yt app.

You wrote out this whole thing and I couldn't care less. 😐

**Comment by andrewpros** [comment] 2021-02-18 15:10
@gghhkm Why are u so rude man, this is childish, im a professional, its a github page for resolving issues, if you dont care about this BUG then fine, but then why do you comment, you are not helping at all, its pointless.

I really encourage everyone to test the vanced app on android tv if they have air mouse remote control according to the things i wrote, do you see the same results?

**Comment by gghhkm** [comment] 2021-02-18 15:12
> @gghhkm Why are u so rude man, this is childish, im a professional, its a github page for resolving issues, if you dont care about this BUG then fine, but then why do you comment, you are not helping at all, its pointless.
> 
> I really encourage everyone to test the vanced app on android tv if they have air mouse remote control according to the things i wrote, do you see the same results?

I thought you were just talking crap at first as meany who write out whole paragraphs do. As you can see it's deleted. 😐

**Comment by moesadah** [comment] 2021-02-18 15:23
> I was answering to OP that **vanced do WORK 100% on android tv** as he stated it is not working, thats not true.
> 
> It is not entirely true its not designed for android tv, well the UI design yes, but vanced has great UI that is universal i would say.
> 
> Its not the looks i care, its really fine.
> 
> I already have and use air mouse remote control so it is not that huge issue, but man, it would be so much easier if those up/down buttons worked on the main video list.
> 
> They only issue is up/down buttons and only them.
> 
> **Android by design supports automatically remote controls, the keys are send to the app without doing anything in the app, this is described in google documentation, it works out of the box and they are send to vanced.**
> 
> **Vanced supports remote controls**, play/pause works, up/down WORKS...
> 
> **THE ISSUE IS**
> 
> Up/down keys dont works as intended only on the main video list for **unknown reason**
> 
> **IT WORKS**, sometimes it needs to the get focus with the mouse pointer, sometimes be in the right spot, but it works on:
> 
> * the side related movies on player page
> * search page
> * channel account main tab and videos tab
> * also in some degree on the discovery tab
> 
> **BUT IT DOESN'T WANT TO WORK IN MAIN APP TAB and i dont know why**
> 
> Its like something is preventing it from scrolling to the next row of videos, **i did detailed tests, u can hear the button pressed sound so it is receiving it, u can see it tries to scroll, the view moves some pixel up/down if there is some uneven room left, but wont scroll to the next row.**
> 
> **If u scroll on purpose so the view shows some part of the videos in the next row then pressing down will scroll fully to the next videos row, this works both directions, but then it stops again.**
> 
> So i would say this is a **BUG**, the whole app supports the remote buttons in many places, but the main app video list is just bugged.
> 
> I think vanced devs could really investigate it, something is not right.
> 
> If i can help in any way to fix it then tell me how, with this fixed it would be the prefect app, way better than any ATV yt app.

Yes the app runs on Android TV because it is Android. what I meant is that it needs some work to fully support ATV. The mouse solves the scrolling problem partially but it still bugs sometimes. The videos in general suffer from delays. I noticed that when I played a video clip of a song, where I could see that the song itself is a little bit ahead of the video itself. As I said, it is designed to be working on Android touch devices (phones and tablets) but not ATV. Therefore it needs more optimization and tweaks to have it fully running on ATV, as good as it runs on Android touch devices if that makes sense. Which is the whole point of this post.

**Comment by gghhkm** [comment] 2021-02-18 15:29
> If i can help in any way to fix it then tell me how, with this fixed it would be the prefect app, way better than any ATV yt app.

It's a problem with stock not Vanced itself, and it's never going to be fixed because stock was never created with Android TV in mind so google in turn doesn't care.
And adding device support/functionality isn't exactly possible without the source code which the Vanced Dev team will never have access to.
The Dev team would have to modify the Android TV version of YouTube, and as I've said above they don't want to do that. Why? Because they would have to rewrite ***everything*** and create a whole new mod app.

**Comment by gghhkm** [comment] 2021-02-24 04:24
Use these alternatives instead.
[SmartYouTubeTV](https://github.com/yuliskov/SmartYouTubeTV)
[SmartTubeNext](https://github.com/yuliskov/SmartTubeNext)

**Closed by gghhkm** 2021-02-24 04:24 UTC
Labels: enhancement

**Comment by andrewpros** [comment] 2021-02-26 15:02
@gghhkm 

Sorry man, but how on earth you become a contributor if u know nothing about how vanced is created? Do you have even any knowledge about creating android apps or mods? Cuz i do.
You did even admit, you dont read what ppl write as is it crap... i get it, most dont know anything, but this is not an attitude a contributor should have.

But your arguments are totally invalid.

First it has nothing to do with android tv or not, android tv is just android with different look, i dont care about the looks or view design, im fine with vanced on my atv and it looks and works great, the remote control buttons are passed to any app on android automatically, it has nothing to do with android tv, its just ppl use remote control only with android tv, but it still works everywhere and it also works in stock YT app on which vanced is based, it has nothing to do with how it looks.

Second, vanced app is an modified yt stock app, so vanced team is modifying the stock app already, and yes, they have kind of "source", no need to get into specifics here, so your arguments are also false here, you dont know how it works, they can change many many things, they already changed A LOT, they even added a Sponsor Block functionality which is very advanced and isn't in the stock app at all (duh), it is way more advanced to add something like this than some simple fixes they can also do.

This is a proof your "Source code" info is irrelevant to the case.

There is no need for any kind of new device support or functionality like Sponsor Block, they functionality is already there, remote controls are supported out of the box, it has only one small BUG on the main fragment, but works on any other fragments.

Third, no, they dont need to modify android TV app, why would they, this is again false statement, the android tv official app is terrible, thats why i use vanced on my tv, cuz it is so much better.

So do not propose other software that is inferior, its not needed and i know all of them, dont want them.

But i need to correct that i was only answering to the OP in his false information that vanced is not working on ATV, its just simply not true, its works fine, almost perfect, maybe i shouldn't bring this issue here at all, instead make a separate issue for a BUG fix.

Either way, sorry, but the amount of misinformation and false arguments you provide make me think you shouldn't be a contributor at all, your are not right, not a single time, if you cant provide accurate information or dont know how it all works then what's the point, why a person without technical expertise is closing technical discussions? (yeah maybe in this case it was understandable, but i write overall) 

Is there a manager here? I need to take this higher i guess.

**Comment by gghhkm** [comment] 2021-02-26 15:13
> @gghhkm
> 
> Sorry man, but how on earth you become a contributor if u know nothing about how vanced is created? Do you have even any knowledge about creating android apps or mods? Cuz i do.
> You did even admit, you dont read what ppl write as is it crap... i get it, most dont know anything, but this is not an attitude a contributor should have.
> 
> But your arguments are totally invalid.
> 
> First it has nothing to do with android tv or not, android tv is just android with different look, i dont care about the looks or view design, im fine with vanced on my atv and it looks and works great, the remote control buttons are passed to any app on android automatically, it has nothing to do with android tv, its just ppl use remote control only with android tv, but it still works everywhere and it also works in stock YT app on which vanced is based, it has nothing to do with how it looks.
> 
> Second, vanced app is an modified yt stock app, so vanced team is modifying the stock app already, and yes, they have kind of "source", no need to get into specifics here, so your arguments are also false here, you dont know how it works, they can change many many things, they already changed A LOT, they even added a Sponsor Block functionality which is very advanced and isn't in the stock app at all (duh), it is way more advanced to add something like this than some simple fixes they can also do.
> 
> This is a proof your "Source code" info is irrelevant to the case.
> 
> There is no need for any kind of new device support or functionality like Sponsor Block, they functionality is already there, remote controls are supported out of the box, it has only one small BUG on the main fragment, but works on any other fragments.
> 
> Third, no, they dont need to modify android TV app, why would they, this is again false statement, the android tv official app is terrible, thats why i use vanced on my tv, cuz it is so much better.
> 
> So do not propose other software that is inferior, its not needed and i know all of them, dont want them.
> 
> But i need to correct that i was only answering to the OP in his false information that vanced is not working on ATV, its just simply not true, its works fine, almost perfect, maybe i shouldn't bring this issue here at all, instead make a separate issue for a BUG fix.
> 
> Either way, sorry, but the amount of misinformation and false arguments you provide make me think you shouldn't be a contributor at all, your are not right, not a single time, if you cant provide accurate information or dont know how it all works then what's the point, why a person without technical expertise is closing technical discussions? (yeah maybe in this case it was understandable, but i write overall)
> 
> Is there a manager here? I need to take this higher i guess.

I'm sorry but you got a lot of stuff wrong here man, like for 1 sponsor block is an API that has the ability to increase the time to skip segments that's it, most of it's code is off site and handled by the sponsor block team. Vanced team does not have the original source code for YouTube. Chasing stuff in a way to make it so that remote controls gain more functionality within the app requires access to the source code or at least heavy reverse engineering.

Don't believe me talk to @KevinX8

**Comment by andrewpros** [comment] 2021-03-02 16:21
No, im not wrong, everything i wrote is true, you twist my words man. But i told you,  its not the place for such things so i will be short.
- SponsorBlock, i know all about it, so yeah, but you need to integrate it into vanced and that means modding app so it will use the the api, will use the api when u watch a video to check if this video is in db and have ads segments to skip, this is not in the yt stock app right, needs mod, but someone like you could say that adding something like this "requires access to the source code" and the stock dont have it thus not possible to make, and yet, surprise, there it is, a functionality in vanced not existing in stock, your wording is misleading
- i never said anyone has original yt source code, thats why i use "source", as no one besides g has it, but your words are again misleading and not true, as we all know what the "source" here is, its a smali mod and reverse engineered stock app, this is how mods are done and vanced, so you have (also with tools to decompile to java to at least find things easier) some kind of "source" that you can work with, modify and then compile it back into a modded apk. SO dont write to me that you need "access to the source code" to change something and then that "isn't exactly possible without the source code which the Vanced Dev team will never have access to." as it is irrelevant to the fact how those mods are created, all without original source code and yet they are created anyway as the "source" is available and is modified, just at a different level, but technically, even if it is way harder, cuz it is, you still can change/fix/add whatever you want if u know how, this is the truth, without original source code.

So just dont write misleading things of how it works, in know its easier to give a simple answer to get rid of ppl asking about complex things they dont understand, but dont treat everybody like complete idiots, its rude.

As for the obvious question why i dont do it myself, its simple, knowing things is not always the same as being able to do it, in this case, finding where exactly the bug sits isn't easy, finding the right place is like 90% of job done, i never said its easy, but that's why vanced team have advantage here, they work with this for years, by now they probably know the app structure very well and where exactly to look for this kind of issue, they know what views are used and where, activates, the app flow, they have experience with internals of the app, so they could at a minimum check much more efficiently than others if this is even possible to fix or not, cuz maybe its is just a single small change, u never know till you find it, and doing a small change for something like this is worth the effort.

**Comment by gghhkm** [comment] 2021-03-02 16:26
> No, im not wrong.

Bruh, just stop talking. I have direct contact with the devs and have spent years here, so you can just stop trying.
Honestly you're just a waist of everyone's time.

**Comment by andrewpros** [comment] 2021-03-02 16:45
As is expected, everything i said about you is true. I have proved beyond doubt how you are misleading ppl, so now you change the attitude as u dont have anything left, not a single viable argument. Direct contact, lol funny, doesn't mean anything, its about you and your knowledge, not who you talk with, and u just spread lies and false information to ppl to get rid of them as they dont have the technical expertise to know this. But yeah its a waste time talking with you, you wont change, u are a disgrace to this project. U dont respect ppl so dont expect being respected. Bye.

**Comment by gghhkm** [comment] 2021-03-02 16:47
> As is expected, everything i said about you is true. I have proved beyond doubt how you are misleading ppl, so now you change the attitude as u dont have anything left, not a single viable argument. Direct contact, lol funny, doesn't mean anything, its about you and your knowledge, not who you talk with, and u just spread lies and false information to ppl to get rid of them as they dont have the technical expertise to know this. But yeah its a waste time talking with you, you wont change, u are a disgrace to this project. U dont respect ppl so dont expect being respected. Bye.

Oh, really? Ok then.

**Comment by gghhkm** [comment] 2021-03-02 17:29
Oh, btw for anyone wondering.
Fixing a bug created by Vanced itself is easy af, sense we have the source code to the patcher, but a bug created by google in the stock version is nearly impossible for use to fix for obvious reasons. The fact that Vanced team has never fix a stock bug once in its entire life span is proof enough of this. It's a very basic concept that this man's doesn't seem to be able to grabs or should I say he can but he just trying to waste my and your time with his bs if his claims of his background are even true, which just by digging into his account you'll realize he doesn't actually contribute anything. All he does is write issue pages and fork other people's projects, not a single line of code written by him. He acts all high and mighty but really it's just a sham, and I believe anyone who's patient enough to do some digging or already have (real) experience with this type of thing can easily cut through his bs.

**Comment by samaparr** [comment] 2021-03-23 13:24
Hi.

I ended up here from Google and wanted to just say that you both look like utter morons arguing with each other over nothing and patting yourselves on the back at how great you both are.

Thanks for wasting my time when trying to research a problem I'm having.

If you are as smart as you think you are then you wouldn't be here in the first place.

Sincerely, 

Sam

**Comment by DraconicNEO** [comment] 2021-03-24 00:22
> 
> 
> Hi.
> 
> I ended up here from Google and wanted to just say that you both look like utter morons arguing with each other over nothing and patting yourselves on the back at how great you both are.
> 
> Thanks for wasting my time when trying to research a problem I'm having.
> 
> If you are as smart as you think you are then you wouldn't be here in the first place.
> 
> Sincerely,
> 
> Sam

I'm Glad someone here is smart enough to see it.

**Comment by gghhkm** [comment] 2021-03-29 01:00
> Hi.
> 
> I ended up here from Google and wanted to just say that you both look like utter morons arguing with each other over nothing and patting yourselves on the back at how great you both are.
> 
> Thanks for wasting my time when trying to research a problem I'm having.
> 
> If you are as smart as you think you are then you wouldn't be here in the first place.
> 
> Sincerely,
> 
> Sam

I was just trying to help, and explain why we can't do anything about the issue and why it was closed. Then andrew came here trying to discredit me like he's some sort of genius who knows everything. I've put plenty of effort into Vanced and won't have some random spreading false information and disrespect me at the same time.

**Comment by gghhkm** [comment] 2021-03-29 01:04
> 
> I'm Glad someone here is smart enough to understand that that type of behavior isn't smart or professional.

You say that like all of the Vanced team including the devs aren't just volunteers, xfile could have just never made it public in the first place. We're not employees and you use Vanced for free, we're not some corporate company mate.

**Comment by 2ndquest** [comment] 2021-06-27 19:56
> > I'm Glad someone here is smart enough to understand that that type of behavior isn't smart or professional.
> 
> You say that like all of the Vanced team including the devs aren't just volunteers
> Just be thankful that we care enough to provide anything. 

Since you're all volunteers there is no reason for us to be thankful to assholes as you would be readily replaced by someone disgusted by your actions if you decided to leave.

As someone else said, you morons made researching a solution more work than necessary just so you could wave your dick at someone who "disrespected" you. 

I hope you leave the team, I wouldn't miss you and neither would the project.

**Comment by KevinX8** [comment] 2021-06-27 20:14
Issue locked due to unproductive comments constantly being left on this repo, there is no interest from the vanced team in making an Android TV version and any bugs in vanced on a TV are caused by stock YouTube/Google and not us so don't request them to be fixed either, Google is unlikely to fix them however as they expect you to use the android TV version of the app. If Google fixes the bugs themselves then we have no problem providing new versions of the app that work better on an Android TV but we will not be making a new standalone modded app.
