### ISSUE TITLE
[Idea] Options to disable Feed and Video Suggestions

### ISSUE THREAD

**Issue by AB285** [YTVanced/Vanced#988] opened 2021-06-19 21:00 UTC
Can you make options for disabling the feed and the video suggestions? I think those features would be really useful because so many people are stuck in a loop of mindless scrolling so many times, so if they could just disable those it would make a big change in productivity and they would be more mindful about what they search. Thanks in advance 👍

New Pipe has these features

newpipe.net

**Comment by milindgoel15** [comment] 2021-06-20 11:35
Duplicate of #334

**Closed by milindgoel15** 2021-06-20 11:35 UTC
Labels: enhancement
