### ISSUE TITLE
[Bug] unable to refresh recommendations page

### ISSUE THREAD

**Issue by Toxiccumblast** [YTVanced/Vanced#840] opened 2021-05-19 17:56 UTC
**Bug description**
I am unable to refresh the recommendations page, I cant swipe down to refresh, it works when viewing a YouTube channels page but not in the recommendations, please see attached video for visual representation.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11

 **Device**
Samsung Galaxy S21 ultra

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Swipe down to refresh recommendation page
3. ....

**Expected behavior**
Swiping down won't refresh the page, nor show the loading animation of the page refreshing.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment] 2021-05-19 18:11
Duplicate of #252

**Closed by milindgoel15** 2021-05-19 18:11 UTC
Labels: bug
