### ISSUE TITLE
Big comment box

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1400] opened 2021-11-18 11:39 UTC
Hi,

When I'm typing a comment and press on the text this happnes:
![Screenshot_20211118-122644](https://user-images.githubusercontent.com/29215437/142408440-bada6518-180d-40b9-a3cf-6d2134fc059f.jpg)

Sam's with the white theme. 

It's been an issue before in the normal YouTube app but it has been fixed.

**Comment by milindgoel15** [comment] 2021-11-18 12:28
Duplicate of #1050

**Closed by milindgoel15** 2021-11-18 12:28 UTC
