### ISSUE TITLE
[Bug] The copy/paste menu covered large chunk of screen

### ISSUE THREAD

**Issue by YuyukoSS** [YTVanced/Vanced#1200] opened 2021-08-19 16:53 UTC
**Bug description**
The copy/paste menu covered a large chunk of screen, make it impossible to edit a large portion of text in the comment box.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 11 

**Device**
Samsung Galaxy A50 (2019)

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app.
2. Click on comment section of any video.
3. Write a few lines of random gibberish and hold.

**Expected behavior**
As demonstrated in 1st image.

**Additional media**
Expected behaviour:
![Screenshot_20210819-234602_Brave](https://user-images.githubusercontent.com/50669582/130110194-ee4e667b-d8d4-4c30-867d-fdcdbe63b924.png)
What the bug has done, visually demonstrated:
![Screenshot_20210819-233945](https://user-images.githubusercontent.com/50669582/130110204-8dc89d28-427e-4327-a191-5edf78b3df44.png)

**Post script**
I hope to seeing replies from the developers in the near future.

**Comment by milindgoel15** [comment] 2021-08-19 18:36
duplicate of #1050

**Closed by milindgoel15** 2021-08-19 18:36 UTC
Labels: bug
