### ISSUE TITLE
[Bug] Links Not Opening

### ISSUE THREAD

**Issue by bwinnirmal** [YTVanced/Vanced#963] opened 2021-06-14 04:01 UTC
**Bug description**
Cant Able To Open Links Whenever Ill Click On Links In The Discription It Will show Error Youtube Cant Able To Open Links.

**Variant**
Non-Root

**Vanced version**

16.20.35

**Android version**

Android 11 

**Device**
Realme 6 Pro

Screen Shot

https://ibb.co/nPKbBvT

**Comment by milindgoel15** [comment] 2021-06-14 05:44
Duplicate of #774

**Closed by milindgoel15** 2021-06-14 05:45 UTC
Labels: bug
