### ISSUE TITLE
[Bug] Chromecast problem

### ISSUE THREAD

**Issue by FAIL04** [YTVanced/Vanced#758] opened 2021-05-01 18:39 UTC
**Bug description**
Whenever I try to cast to my 2019 nVidia shield or Smart tv I get a message to update Google Play Services. When I try to open it's just a loading screen in Play Store.

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 10

**Device**
Honor 20

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on Chromecast to tv
3. A message will pop up telling to update Google Play Services

**Expected behavior**
YouTube should start casting to tv

_Attach images/videos if possible. These can be helpful in solving the issue._
![Screenshot_20210501_203707_com vanced android youtube](https://user-images.githubusercontent.com/83513582/116791817-1868e300-aabd-11eb-88db-3aab23105725.jpg)

**Comment by milindgoel15** [comment] 2021-05-02 03:09
Duplicate of #688

**Closed by milindgoel15** 2021-05-02 03:09 UTC
Labels: bug
