### ISSUE TITLE
[Bug] Desired brightness changes when switching back and forth from Landscape mode and Portrait mode.

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#766] opened 2021-05-03 00:14 UTC
**Bug description**
I noticed that Vanced doesn't save the set brightness in landscape mode(full screen) anymore. If I lower the brightness in landscape mode, leave landscape mode, and open it again, the brightness goes up on it's own. It doesn't save the brightness that I set before leaving landscape mode.
This is really annoying and uncomfortable, especially at night it's hurting my eyes.

**Variant**
Non-Root

**Vanced version**
Version 16.16.38

**Android version**
Android 10

**Device**
ROG Phone 2

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Open any video in landscape mode, set a desired brightness with swiping gestures
3. Leave Landscape mode
4. Open Landscape mode, your desired brightness has gone up.

I recorded the behavior for you. In earlier versions this didn't happen:
[Brightness bug in landscape mode](http://imgur.com/a/JE0gPVc)

**Comment by Harmonie666** [comment] 2021-05-03 00:20
A redditor posted the bug in the subreddit aswell:
https://www.reddit.com/r/Vanced/comments/n3hjdu/question_brightness_resets_everytime_full_screen/?utm_medium=android_app&utm_source=share

**Comment by Swichtden** [comment] 2021-05-03 05:12
Same problem
Vanced version
Version 16.16.38 (Root)

**Comment by Darkaeluz** [comment] 2021-05-03 06:05
Same problem

**Variant**
Root

**Vanced Version**
16.16.38

**Android Version**
Android 11

**Device**
Xiaomi MI6

**Comment by milindgoel15** [comment] 2021-05-03 13:29
Don't create duplicate issues again and again please
Duplicate of #752

**Closed by milindgoel15** 2021-05-03 13:29 UTC
Labels: bug

**Comment by Harmonie666** [comment] 2021-05-03 13:31
> Don't create duplicate issues again and again please
> Duplicate of #752

I'm sorry. I wasn't aware of a existing post.

**Comment by milindgoel15** [comment] 2021-05-03 13:32
It's okay. Just search previous issues before creating a new one for any issue
