### ISSUE TITLE
[Bug] youtube vanced will be uninstalled automatically once a phone is restarted

### ISSUE THREAD

**Issue by likhithdc** [YTVanced/Vanced#239] opened 2020-11-29 02:51 UTC
**Bug description**
I installed the youtube vanced using vanced manager.
I did use the phone some days, and I happened restart the phone for some reason so I did restart the phone.
I could not see the ytvanced after restart. Looks like automatically uninstalled from the phone.
I tried to reproduce and I can see that once phone restarted ytvanced will be removed from the phone.

**Variant**
NonRoot: No
Root: Yes
I did root using magisk v20.4
**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Redmi note 5 pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'install' on YouTube vanced tab.
3. The YouTube vanced app will be downloaded and installed a couple of minutes.
4. Restart the phone.
5. YouTube vanced will be automatically uninstalled and you can't able to yt vanced anywhere in the phone and to confirm uninstalled you can open the vanced manger and see 'install' button shown YouTube vanced tab instead of reinstall.

**Expected behavior**
YouTube vanced should not be removed if the phone is restarted.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by david-lev** [comment] 2020-12-05 16:29
That's because you're in a country that supports a language other than the language you set when you downloaded YouTube Vanced. When you restart the phone, Google Play Store detects you're missing a language file and downloads config.XX.apk and breaking the app.
To the best of my knowledge this is the problem and does not help disable automatic updates to YouTube via Google Play because it is not an update but a language file that the Store automatically downloads.

**Comment by milindgoel15** [comment] 2021-04-30 12:08
duplicate of #123

**Closed by milindgoel15** 2021-04-30 12:08 UTC
Labels: bug, wontfix
