### ISSUE TITLE
[Bug] When I open Vanced it says I dont have internet but i have it and restarted my phone several times

### ISSUE THREAD

**Issue by GoldyNews** [YTVanced/Vanced#1371] opened 2021-11-07 21:23 UTC
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
Non-Root/Root

**Vance v16.29.39

**Android version**
Replace me with the version of Android your device have. For example, Android 11 

**Device**
Samsung Galaxy S7

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. And theres the warning

**Comment by milindgoel15** [comment] 2021-11-08 15:10
Duplicate of #786

**Closed** 2021-11-08 15:10 UTC
Labels: bug
