### ISSUE TITLE
[Bug] I can't watch my videos. Language: Brazilian Portuguese

### ISSUE THREAD

**Issue by KevynCBR** [YTVanced/Vanced#1225] opened 2021-08-28 19:56 UTC
**Bug description**
Eu alterei a senha da minha conta do Google e quando vou assistir aos meus vídeos no YouTube Vanced, ele me pede para que eu me reconecte, mesmo já estando conectado na internet

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 10

**Device**
Moto G8 Play

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2.  The End

**Expected behavior**
Watch my videos normaly.

Images:
![Screenshot_20210828-165440](https://user-images.githubusercontent.com/89707032/131229557-5d87c7b2-4bf3-4d60-84a8-81ec8c8afa30.png)
![Screenshot_20210828-165450](https://user-images.githubusercontent.com/89707032/131229564-972d55fa-c6a8-43cd-aba3-249bfbaaf183.png)

**Comment by milindgoel15** [comment] 2021-08-29 05:10
Duplicate of #786

**Closed by milindgoel15** 2021-08-29 05:11 UTC
Labels: bug
