### ISSUE TITLE
[Bug] History Not Showing Seen Video

### ISSUE THREAD

**Issue by Chintan8169** [YTVanced/Vanced#797] opened 2021-05-09 06:47 UTC
**Bug description**
Videos that are seen from app are not showing in history section.

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 8.1 - Oreo

**Device**
Redmi Note 5

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Watch any video
3. Head to history
4. The seen video will not shown there even if you seen video.

**Expected behavior**
Should display videos in history after they have seen.

**Comment by milindgoel15** [comment] 2021-05-09 15:05
Duplicate of #301

**Closed** 2021-05-09 15:06 UTC
Labels: bug
