### ISSUE TITLE
[Bug] refresh on main page doesn't work after some time

### ISSUE THREAD

**Issue by PktPete** [YTVanced/Vanced#1492] opened 2021-12-28 22:32 UTC
**Bug description:**
In Vanced on most current version it won't allow me to refresh the home page at all but subscription page will

**Variant:**
Non-Root

**Vanced version:**
v16.29.39

**Link used to download vanced:**
Replace here with the source/link you used to download and install on your device. 

**Android version:**
Android 11 

**Device:**
OnePlus 8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Attempt to refresh home page
3. Gain nothing and navigate to subscriptions to be able to refresh

**Expected behaviour:**
To have the refresh work and not the edge pull show

**Comment by milindgoel15** [comment] 2021-12-29 03:57
Duplicate of #252

**Closed by milindgoel15** 2021-12-29 03:57 UTC
Labels: bug
