### ISSUE TITLE
[Idea] Remove Shorts

### ISSUE THREAD

**Issue by BbayuGt** [YTVanced/Vanced#1744] opened 2022-03-11 08:01 UTC
**Description**
Add an option to redirect you to original player when opening YouTube Shorts Video. Youtube Shorts Suck.

**Comment by milindgoel15** [comment] 2022-03-11 08:02
Duplicate of #334

**Closed by milindgoel15** 2022-03-11 08:02 UTC
Labels: enhancement

**Comment by BbayuGt** [comment] 2022-03-11 08:07
Im not requesting to remove the explore button tho, i just doesn't like it when you click a shorts video, the UI will fill your screen

Instead of https://youtube.com/shorts/roAJd7C64Q8?feature=share
Redirect it to original https://youtube.com/?v=roAJd7C64Q8

**Comment by milindgoel15** [comment] 2022-03-11 08:12
Your title says remove shorts & ur description says convert to a regular page. 

Perhaps u should decide what exactly you want. And even if you want the other, that feature suggestion is tracked at #316
