### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by lordsweet1** [YTVanced/Vanced#1242] opened 2021-09-03 14:27 UTC
**Bug description**
every time that I open the app it shows me that I'm offline even though I'm connected to the internet
![WhatsApp Image 2021-09-03 at 5 25 44 PM](https://user-images.githubusercontent.com/90052009/132021556-b0848487-eece-4b11-8de4-dcc10b251712.jpeg)

**Variant**
Non-Root/Root

**Vanced version**
 v16.29.39

**Android version**
V 10

**Device**
 Samsung Galaxy S9

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._
![A photo](https://user-images.githubusercontent.com/90052009/132021714-e432af72-7dab-40ce-80f1-1177fc22aa5f.jpeg)

**Comment by milindgoel15** [comment] 2021-09-03 14:34
Duplicate of #786

**Closed by milindgoel15** 2021-09-03 14:34 UTC
Labels: bug
