### ISSUE TITLE
[Idea] Increase Maximum Playback Speed

### ISSUE THREAD

**Issue by TempUser13** [YTVanced/Vanced#238] opened 2020-11-28 12:14 UTC
My request is to increase the Maximum Playback Speed from 2x to 3x via increases of 0.25x. My second request is to be able to type in a numerical value for the payback speed which would be between 0 and 3. Thank you.

**Comment by surajkumarbehera09** [comment] 2020-12-09 12:51
I also need this.....

**Comment by Vasilich1234** [comment] 2021-02-02 19:55
I vote for this

**Comment by gghhkm** [comment] 2021-02-03 01:51
#82

**Comment by milindgoel15** [comment] 2021-04-30 08:57
duplicate of #82

**Closed by milindgoel15** 2021-04-30 08:57 UTC
Labels: enhancement, wontfix
