### ISSUE TITLE
[Bug] Refresh Feed breaks after activating shorts shelf in ad settings

### ISSUE THREAD

**Issue by deniscerri** [YTVanced/Vanced#1439] opened 2021-12-03 22:11 UTC
**Bug description**
When i try to activate shorts shelf options in Vanced Settings -> Ad Settings, to turn off the shorts tab in the main screen, i cannot refresh the feed anymore. Turning shorts shelf back off, fixes the issue.

**Variant**
Non-Root

**Vanced version**
16.29.39 Build 01.54.00

**Android version**
Android 11

**Device**
Samsung Galaxy S10 Snapdragon

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Go to Settings
3. Go to Vanced Settings
4. Go to Ad Settings
5. Turn on Shorts Shelf
6. Try to refresh the main feed

**Expected behavior**
It is supposed to show the loading circle and refresh the feed.

[Video](https://streamable.com/em6251)

**Comment by milindgoel15** [comment] 2021-12-04 02:30
Duplicate of #252

**Closed by milindgoel15** 2021-12-04 02:30 UTC
Labels: bug
