### ISSUE TITLE
[Idea] Integration with Wavelet

### ISSUE THREAD

**Issue by DW01** [YTVanced/Vanced#1569] opened 2022-02-01 23:42 UTC
**Description**
Add built-in support for Wavelet.

**What is Wavelet?**
Wavelet is a background audio processing app for Android, primarily used as a system-wide equalizer. It intercepts broadcast events from music and video players (notable among them, first-party YouTube Music) and applies real-time DSP. The first-party terrible YouTube app doesn't support it, so this could be a great set-apart feature for Vanced.

I personally use Wavelet to provide rudimentary headphone calibration on Android via its use of the wonderful AutoEQ headphone EQ curve library, but it also supports some more advanced effects like surround virtualization.

![The Wavelet interface.](https://user-images.githubusercontent.com/2569291/152069776-a5bbff24-9e04-4376-9d00-f1721d63e252.jpg)

![Poweramp, a music player with support for Wavelet.](https://user-images.githubusercontent.com/2569291/152069864-f3ce4e50-e9f0-466c-b19d-20da3ecef1a4.jpg)

**Comment by milindgoel15** [comment] 2022-02-03 09:20
Duplicate of #1143

**Closed by milindgoel15** 2022-02-03 09:20 UTC
Labels: enhancement
