### ISSUE TITLE
[Idea] increase playback speed to 4×

### ISSUE THREAD

**Issue by Isssuemaker** [YTVanced/Vanced#993] opened 2021-06-21 13:15 UTC
Please increase playback speed to 4×

**Comment by milindgoel15** [comment] 2021-06-21 13:59
Duplicate of #82

**Closed by milindgoel15** 2021-06-21 13:59 UTC
Labels: enhancement

**Comment by Isssuemaker** [comment] 2021-07-25 15:34
The #82 has been closed without any good reason please open it it is very requested feature

**Comment by Isssuemaker** [comment] 2021-07-25 15:34
> Duplicate of #82

Please open it
