### ISSUE TITLE
[Bug] replacemeI try to update my youtube vanced, and it says the database was corrupt, and i cant download it anymore

### ISSUE THREAD

**Issue by Agent9104** [YTVanced/Vanced#144] opened 2020-11-03 23:04 UTC
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
NonRoot: Yes
Root: Yes 

**Vanced version**
15.43.32 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on 'update'
3. Now the bug get started 

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment] 2021-04-30 08:51
Please update to the latest vanced manager v2.6.0 if you haven't already. We are closing this issue. Feel free to reopen if you still face any issues.

**Comment by milindgoel15** [comment] 2021-04-30 08:52
duplicate of #142

**Closed by milindgoel15** 2021-04-30 08:52 UTC
Labels: bug
