### ISSUE TITLE
Video playback defaulting to 480p for 1080p60 videos

### ISSUE THREAD

**Issue by gokulpoovalliyil** [YTVanced/Vanced#499] opened 2021-02-27 09:13 UTC
Even though the preferred video quality is set to 1080p, the playback will always default to 480p. Regular 1080p videos do not have this issue and will automatically playing the video at 1080p from the start. The same happens when the selected quality is 1440p.

**Expected Behaviour**
If the video quality is set to 1080p or above, videos with higher frame rate should default to the equivalent higher frame rate version of the selected video quality

![Screenshot_20210227-143407](https://user-images.githubusercontent.com/62756931/109383034-dfb85c00-7909-11eb-8d4a-1ef89af9df73.jpg)
![Screenshot_20210227-143443](https://user-images.githubusercontent.com/62756931/109383036-e0e98900-7909-11eb-8dc3-fe1d822650d6.jpg)
![Screenshot_20210227-143523](https://user-images.githubusercontent.com/62756931/109383037-e21ab600-7909-11eb-878a-25aa5c1e46ca.jpg)

**Comment by milindgoel15** [comment] 2021-04-30 12:22
duplicate of #261

**Closed by milindgoel15** 2021-04-30 12:22 UTC
Labels: bug
