### ISSUE TITLE
[Idea] Remove automatically playing the next video from a playlist via settings

### ISSUE THREAD

**Issue by SquidsuneMiku** [YTVanced/Vanced#1552] opened 2022-01-27 05:33 UTC
Whenever I play a video from a playlist, I always have to pause near the end of the video before the next video plays. It would be nice if there was a setting to turn this feature off.

**Comment by milindgoel15** [comment] 2022-01-27 06:20
Duplicate of #1079

**Closed by milindgoel15** 2022-01-27 06:20 UTC
Labels: enhancement
