### ISSUE TITLE
[Bug] YouTube can't open this link

### ISSUE THREAD

**Issue by Tschadow** [YTVanced/Vanced#983] opened 2021-06-17 20:19 UTC
**Bug description**
Links in the app, regardless if they are in video descriptions, posts, channel descriptions, all external links will not open

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
Android 11 

**Device**
Samsung Galaxy S20 Ultra

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any video, post, or channel
3. Attempt to open any link in video description, post description, or channel description

**Expected behavior**
Link should seamlessly open default browser or respective app from link.

**Comment by milindgoel15** [comment] 2021-06-18 03:48
Duplicate of #774

**Closed by milindgoel15** 2021-06-18 03:48 UTC
Labels: bug
