### ISSUE TITLE
[Bug] Android 12 - YouTube hyperlink send to Chrome not YT Vanced 

### ISSUE THREAD

**Issue by Vivimagic** [YTVanced/Vanced#868] opened 2021-05-24 16:32 UTC
**Bug description**
When clicking on a YouTube hyperlink it does not redirect me to YouTube, it loads a new tab in Chrome. 

**Variant**
Non-Root

**Vanced version**
16.16.38 - Build - 01.51.00

**Android version**
Android 12 - Beta 1

**Device**
Pixel 5

**Steps to Reproduce**
Steps to reproduce the error:
1. Press a YouTube hyperlink 
2. Opens Chrome 
3.  Video link is open in Chrome. 

**Expected behavior**
YouTube Hyperlinks  don't redirect to YouTube Vanced

![Screenshot_20210520-202709](https://user-images.githubusercontent.com/20373216/119377663-48b73200-bcb5-11eb-840c-6b458f7a9c47.png)

**Comment by Vivimagic** [comment] 2021-05-24 16:32
When digging into settings the open link options are greyed out.

**Comment by milindgoel15** [comment] 2021-05-24 16:56
Duplicate of #418

If you cant able to set it, use the root version.

**Closed by milindgoel15** 2021-05-24 16:56 UTC
Labels: bug
