### ISSUE TITLE
[Idea] Completly disable Shorts

### ISSUE THREAD

**Issue by leodoi3** [YTVanced/Vanced#947] opened 2021-06-10 20:23 UTC
**Description**
Please remove the shorts tab from the homepage and completely disable the feature. I feel my brain rotting even more every time I open youtube now. My history is filled with bullshit videos that I shouldn't even be spending my time watching in the first place.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment] 2021-06-11 02:20
Duplicate of #334

**Closed by milindgoel15** 2021-06-11 02:20 UTC
Labels: enhancement
