### ISSUE TITLE
[Idea] Hide video recommendations (optional toggle)

### ISSUE THREAD

**Issue by triplenman** [YTVanced/Vanced#912] opened 2021-06-03 16:31 UTC
### I would really like to be able to hide all video recommendations under a video
**I only watch my playlists and only use the Library section, so I’m very distracted by the video recommendations and another unnecessary sections.**
Because of this I have to use YouTube through the browser and block unnecessary sections through extensions =(
This is really necessary! In the survey, my friends and familiars also confirmed this. Such things have been repeatedly discussed on some forums and discussed ways to get rid of unnecessary in the interface.
It would be ideal **to add the ability to hide "Video recommendations under a video" together with sections "Home", "Explore", "Subscription"** [in the settings where it is possible to hide the "Cast button" and "Create button"]. With these changes, the application would be perfect and there will be no need for a browser with extensions!
Thank you very much for your work!

**Comment by milindgoel15** [comment] 2021-06-04 03:11
Duplicate of #352

**Closed by milindgoel15** 2021-06-04 03:11 UTC
Labels: enhancement
