### ISSUE TITLE
[Bug] Shows old and read notifications

### ISSUE THREAD

**Issue by mathmakgakpak** [YTVanced/Vanced#1138] opened 2021-08-04 08:15 UTC
**Bug description**
Shows old and read notifications.

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
11

**Device**
Huawei P20

**Steps to Reproduce**
Wait

**Expected behavior**
Show notification only once

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._
https://user-images.githubusercontent.com/44949126/128146453-1d3c1f24-b966-4b5e-a6dd-c89644ff6f2b.mp4

**Comment by milindgoel15** [comment] 2021-08-04 08:18
Duplicate of #1107

**Comment by mathmakgakpak** [comment] 2021-08-04 08:18
i cant stop vanced from doing that so i need to uninstall it

**Closed by milindgoel15** 2021-08-04 08:18 UTC
Labels: bug

**Comment by mathmakgakpak** [comment] 2021-08-04 08:21
sorry for duplicating issues i searched for open issues only cuz it still happened for me so i thought that it should be opened

**Comment by milindgoel15** [comment] 2021-08-04 08:25
It's caused by microG latest updates and hence, it's not under our control because it's not made by us. microG belongs to microG team(marvin is the dev of it). Vanced microG just pulls and rebase commits from head repo.
