### ISSUE TITLE
[Idea] Customize the tab bar

### ISSUE THREAD

**Issue by leodoi3** [YTVanced/Vanced#1017] opened 2021-06-27 02:51 UTC
**Description**
Please add a feature to customize the tab bar and remove certain items , like the Shorts, Explore, etc. 

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

Cercube for iOS (hacked Youtube iOS version) has a feature that lets you hide the tabs.
![image](https://user-images.githubusercontent.com/46114199/123531430-66632700-d6b9-11eb-8e08-7bfe61233242.png)

**Comment by milindgoel15** [comment] 2021-06-27 08:15
Duplicate of #334

**Closed by milindgoel15** 2021-06-27 08:15 UTC
Labels: enhancement
