### ISSUE TITLE
[Bug] no internet

### ISSUE THREAD

**Issue by ryanboothforever** [YTVanced/Vanced#1401] opened 2021-11-18 17:58 UTC
**Bug description**
 Getting a "Connect to internet" error even though wifi is on and working on other apps.
App: YouTube Vanced & YouTube Music Vanced
Android 11

**Variant**
Non-Root

**Vanced version**
 v16.29.39

**Android version**
Android 11 

**Device**
  Samsung Galaxy S10E

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Instantly see "Connect to internet" error

**Expected behavior**
Load YouTube home screen

![Screenshot_20211118-083533.jpg](https://user-images.githubusercontent.com/68827179/142470661-e6d4a2e2-eeab-44dc-8dfc-fa59b998e39d.jpg)

**Comment by milindgoel15** [comment] 2021-11-18 18:27
Duplicate of #786

**Closed by milindgoel15** 2021-11-18 18:27 UTC
Labels: bug
