### ISSUE TITLE
[Bug] casting videos yo the TV doesn't work

### ISSUE THREAD

**Issue by infinitylirycs** [YTVanced/Vanced#711] opened 2021-04-27 21:08 UTC
**Bug description**
I can't send videos to the tv in the youtube banged app, when I use the normal app it works fine. When I try to use connection by code also the tv show a connection error.

**Variant**
Non-Root

**Vanced version**
16.14.34 - Build - 01.50.01

**Android version**
Android 10.0

**Device**
Moto G9 Play

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on the casting logo or any video and try to cast to the tv

**Expected behavior**
The option should send the video to the tv and it's only loading.
![Screenshot_20210427-174046](https://user-images.githubusercontent.com/83312867/116312733-38c63400-a783-11eb-9c73-efffdb211037.png)
![Screenshot_20210427-175838](https://user-images.githubusercontent.com/83312867/116312737-3a8ff780-a783-11eb-9e2f-1244c921050d.png)

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by vaguerant** [comment] 2021-04-28 07:10
Duplicate of pinned issue #688.

**Closed** 2021-04-28 16:01 UTC
Labels: bug
