### ISSUE TITLE
[Idea] Remove or disable Subsribe, Notification and like buttons to avoid accidental subscribes to unwanted channels.

### ISSUE THREAD

**Issue by Spamm00r** [YTVanced/Vanced#1521] opened 2022-01-10 11:50 UTC
**Description**
Please add an option to remove or disable at least the Subscribe, Notification Bell buttons and if possible also the like buttons from the UI.

Reason: My older relative uses youtube vanced on her phone and the buttons are tiny and she accidentally subscribes to dozens of channels, just because she accidentally touches on the subscribe button. I then have to unsubscribe from hundreds of channels manually to avoid unwanted recommendations. Therefore it would be good if it was possible to disable or hide the button from the UI.

**Comment by milindgoel15** [comment] 2022-01-10 11:51
Suggestion: better use vanced without Google account.

**Comment by milindgoel15** [comment] 2022-01-10 11:52
Duplicate of #1153

**Comment by milindgoel15** [comment] 2022-01-10 11:52
By mistake, tapped on lock button instead of close button. Lmao

**Closed** 2022-01-10 11:52 UTC
Labels: enhancement
