### ISSUE TITLE
[Bug] swipe down to reload not working after using using for awhile

### ISSUE THREAD

**Issue by ijontan** [YTVanced/Vanced#1539] opened 2022-01-18 18:20 UTC
**Bug description:**
Scroll down to reload stops working after using for awhile

**Have you read vanced guides already? (YES/No)**
No 

**Variant:**
Non-Root

**Vanced version:**
v16.29.39

**Link used to download vanced:**
From Vanced Manager from https://vancedapp.com/

**Android version:**
Android 11 

**Device:**
Huawei nova 5t

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Using the app (sometimes just scrolling the feed, sometimes after playing some videos
3. going back to top (either by scrolling of by pressing home button)

**Expected behaviour:**
Scroll to reload fails, even though scrolling down still works

**Comment by milindgoel15** [comment] 2022-01-19 05:15
Duplicate of #252

**Closed by milindgoel15** 2022-01-19 05:15 UTC
Labels: bug
