### ISSUE TITLE
[Idea] Option to revert back to using old UI and icons. (Vanced 15.43.32 and below) 

### ISSUE THREAD

**Issue by Michael82548** [YTVanced/Vanced#622] opened 2021-04-05 16:00 UTC
This is similar to the following issue (mostly for image reference) https://github.com/code4charity/YouTube-Extension/issues/840

I want an option to switch back to seeing the older UI which uses these icons and UI:
![image](https://user-images.githubusercontent.com/53535277/113594678-01da8380-9606-11eb-8c38-3581e3c30aee.png)

These are the newer icons that I personally don't like and other people probably don't either. If you don't, then please react with a heart.
![image](https://user-images.githubusercontent.com/53535277/113594889-45cd8880-9606-11eb-8f3a-3f300c769e83.png)

Please consider adding this option to vanced because right now, I am stuck using version 15.43.32 and I don't want to update to newer versions.

**Comment by GreenRabbits** [comment] 2021-04-17 18:00
I agree with you, older icons are much better. 
But why don't you stay on version 15.43.32 forever ?

**Comment by Michael82548** [comment] 2021-04-17 18:13
> I agree with you, older icons are much better.
> But why don't you stay on version 15.43.32 forever ?

The icons were just forced on the older version

**Comment by AinzTheSupremeOne** [comment] 2021-04-19 18:40
Please instead of creating issue threads after issues, look for previously opened threads. Keep the discussion in one place instead of splitting into multiple threads. Not doing so makes it harder to track them. This is a duplicate of #187 .

**Closed** 2021-04-30 00:05 UTC
Labels: enhancement
