### ISSUE TITLE
[Idea] Detox mode

### ISSUE THREAD

**Issue by Mesum-Hussain** [YTVanced/Vanced#1207] opened 2021-08-21 08:01 UTC
I was wondering if we can have a detox mode in youtube vanced?

Problem: 
We are getting addicted to youtube day by day and waste hours watching mindless videos. The main reason behind this is the awesome social engineering done by YouTube exactly for hooking us to the app. But I genuinely think that the users should have an option to disable all this social engineering attempts just by clicking a single toggle button.

Solution:
Detox mode should
1) hide all the feeds on the home page
2) hide all the recommended videos below the running video
3) disable the notifications.

The only way to watch any video should be by specifically searching for it, because almost 90 percent of the videos we watch on youtube are not something we actually searched for..... They are all suggested by youtube..... If we have to search for a video to watch it then probably be well watch less videos.

Example:
There is a wonderful [chrome extension](https://chrome.google.com/webstore/detail/unhook-remove-youtube-rec/khncfooichmfjbepaaaebmommgaepoid?hl=en) which does precisely this. I am linking a video demonstrating this functionality using that extension in youtube website.

https://user-images.githubusercontent.com/64641670/130315177-bee788a3-2d2b-4ee4-9836-efdb9059893e.mp4

**Comment by milindgoel15** [comment] 2021-08-21 09:59
Duplicate of #1189 and #334.

**Closed by milindgoel15** 2021-08-21 09:59 UTC
Labels: enhancement

**Comment by Mesum-Hussain** [comment] 2021-08-21 16:30
Neither #1189 nor #1207 is duplicate of #334

**Comment by milindgoel15** [comment] 2021-08-21 16:47
go use newpipe if are so distracted with these social apps or just uninstall youtube. since you can't understand any difference between those 2 issues, it's useless for us to waste 1 sec of our precious time on you. or another option would be to buy nokia 3310..

**Comment by Mesum-Hussain** [comment] 2021-08-21 17:02
You are very rude and close minded.
I really think it's more of your opinion that it's similar to #334 than it is actually similar to #334. I bet if more than 5 people from diverse backgrounds see this issue, they would not consider it as duplicate of #334.
You are probably trying to avoid work in the name of marking it as duplicate.

Anyways I expected this from you. 
This was my last attempt..... I was going to mod your YouTube mod just in case you try to ruin this great feature again.

But honestly YouTube Vanced should either add more people at your job or replace you entirely. You are so bad at judgement. Sorry for you dude. I hope you improve soon 🙂.

**Comment by Mesum-Hussain** [comment] 2021-08-21 17:11
> go use newpipe if u are so distracted with these social apps or just uninstall youtube.

I have already uninstalled YouTube and was using YouTube website in Kiwi browser for a while.
I definitely have plans to eventually fork it to make it more awesome and add wonderful features like Detox mode. But for the time being I am going to mod your YouTube mod.
Thanks!

**Comment by danilo-alm** [comment] 2021-11-05 22:14
That's exactly what I wanted :/
I hope they implement this on the app

**Comment by srghma** [comment] 2021-12-31 08:05
More images of unhook extension in kiwi browser (but this browser often crashes)

![Screenshot_20211222-144202_Kiwi Browser](https://user-images.githubusercontent.com/7573215/147094791-9ab87868-a576-4bc5-8e11-4331087a9c00.jpg)
![Screenshot_20211222-144147_Kiwi Browser](https://user-images.githubusercontent.com/7573215/147094797-2f3659e0-ea13-43b3-8e14-cb2b0f65a076.jpg)
