### ISSUE TITLE
[Idea] Options for hiding Feed and Video Suggestions

### ISSUE THREAD

**Issue by AB285** [YTVanced/Vanced#992] opened 2021-06-21 12:43 UTC
I think these options would help a lot of people that get hooked by the feed and suggestions to be more productive and also to be more mindful about what they search on youtube, making them give the platform more meaningful use and maybe learn something important.

**Comment by milindgoel15** [comment] 2021-06-21 13:58
Really bruh? Please stop creating duplicates of duplicates for god's sake

Duplicate of #988 and #338

**Closed** 2021-06-21 13:59 UTC
Labels: enhancement

**Comment by AB285** [comment] 2021-06-21 17:09
I'm new to git hub and they weren't showing up. I tried deleting the others but couldn't find how.
