### ISSUE TITLE
[Idea] Don’t Google Translate video titles.

### ISSUE THREAD

**Issue by JapanYoshi** [YTVanced/Vanced#1523] opened 2022-01-11 02:17 UTC
**Description**
YouTube translates some (but mercifully, not all) video titles from another language into the language of the YouTube app. Unfortunately, there is no way to turn this “feature” off (and I’m using the word “feature” *extremely* loosely), whether it be for all languages, specific languages, or even for a single video.

This is a major annoyance for bilingual users like me, who has had video titles mangled from grammatically correct English into broken Japanese, or from perfectly good Japanese into nearly unintelligible English. Others have reported the same problem with English and Finnish.

![](https://i.imgur.com/IkWQ6hf.jpg)
As an example, here is a screenshot on YouTube Vanced 16.29.23 non-Root for Android, where the title of the video [“How to Watch Youtube Videos Spyware Free!!”](https://www.youtube.com/watch?v=jfyt5ueyWN8) got mangled into “How to watch Youtube videos with free spyware”.

This is also a hindrance for people in multilingual countries such as Papua New Guinea, India, or even Switzerland, who may not speak the “one official language” as determined by arbitrary geolocation data. Take [this poster on YouTube “Help”](https://support.google.com/youtube/thread/108141426/how-to-stop-auto-translation-of-youtube-video-titles)’s word for it that not every Indian speaks Hindi.

There are numerous locked thread about this automatic title translation bug (I’m done calling it a “feature”) dating back to 2019, and YouTube has been continually denying wrongdoing, and blaming it on the video uploaders themselves, even though in some threads the original uploader confirms that they didn’t enable or tolerate it.

* [2019-01-22: ¿ Como desactivar la traducción de títulos automática en youtube ?](https://support.google.com/youtube/thread/1193792/%C2%BF-como-desactivar-la-traducci%C3%B3n-de-t%C3%ADtulos-autom%C3%A1tica-en-youtube)
* [2019-02-23: Wie kann ich die automatische Übersetzung von Videotiteln bei Youtube deaktivieren?](https://support.google.com/youtube/thread/1805695/wie-kann-ich-die-automatische-%C3%9Cbersetzung-von-videotiteln-bei-youtube-deaktivieren)
* [2019-02-14: How do I switch off youtube's automatically translated video titles and discriptions?](https://support.google.com/youtube/thread/1625690/how-do-i-switch-off-youtube-s-automatically-translated-video-titles-and-discriptions)
* [2019-02-26: Disable title translation?](https://support.google.com/youtube/thread/1878493/disable-title-translation)
* [2019-03-31: Comment désactiver la traduction des titres des vidéos ?](https://support.google.com/youtube/thread/3296684/comment-d%C3%A9sactiver-la-traduction-des-titres-des-vid%C3%A9os)
* [2019-05-19: Youtube still auto translating titles! STOP IT!!!](https://support.google.com/youtube/thread/47496564/youtube-still-auto-translating-titles-stop-it)
* [2019-06-18: Please make title/description translation optional.](https://support.google.com/youtube/thread/8232937/please-make-title-description-translation-optional)
* [2019-07-04: Why does YouTube auto translate titles, and most importantly, how do I make it stop?](https://support.google.com/youtube/thread/9180784/why-does-youtube-auto-translate-titles-and-most-importantly-how-do-i-make-it-stop)
* [2019-07-09: How to disable the automatic title translation from Youtube?](https://support.google.com/youtube/thread/9496902)
* [2019-07-15: why u translate description and titles in YT ??!?! pls stop](https://support.google.com/youtube/thread/9875073/why-u-translate-description-and-titles-in-yt-pls-stop)
* [2019-07-24: How can I stop this utterly stupid auto totle translate?](https://support.google.com/youtube/thread/10492461/how-can-i-stop-this-utterly-stupid-auto-totle-translate)
* [2019-08-15: translate title](https://support.google.com/youtube/thread/11988002/translate-title)
* [2019-08-29: Stop Youtube from translating video titles automatically](https://support.google.com/youtube/thread/13080274/stop-youtube-from-translating-video-titles-automatically)
* [2019-09-07: How to disable the automatic title translation from Youtube?](https://support.google.com/youtube/thread/9496902/how-to-disable-the-automatic-title-translation-from-youtube)
* [2019-11-17: How can I turn off that English titles automatically translate into the language I speak?](https://support.google.com/youtube/thread/9609176/how-can-i-turn-off-that-english-titles-automatically-translate-into-the-language-i-speak)
* [2020-03-17: auto translate](https://support.google.com/youtube/thread/33838745/auto-translate)
* [2020-05-30: Where's the real Translate video title and description option?](https://support.google.com/youtube/thread/49927120/where-s-the-real-translate-video-title-and-description-option)
* [2020-07-24: Wrong and unprofessional translation](https://support.google.com/youtube/thread/60601158/wrong-and-unprofessional-translation)
* [2021-04-11: 自動翻訳された動画のタイトルを表示しない（元の言語か、手動で追加された言語のみで表示したい）](https://support.google.com/youtube/thread/105695405/%E8%87%AA%E5%8B%95%E7%BF%BB%E8%A8%B3%E3%81%95%E3%82%8C%E3%81%9F%E5%8B%95%E7%94%BB%E3%81%AE%E3%82%BF%E3%82%A4%E3%83%88%E3%83%AB%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%97%E3%81%AA%E3%81%84%EF%BC%88%E5%85%83%E3%81%AE%E8%A8%80%E8%AA%9E%E3%81%8B%E3%80%81%E6%89%8B%E5%8B%95%E3%81%A7%E8%BF%BD%E5%8A%A0%E3%81%95%E3%82%8C%E3%81%9F%E8%A8%80%E8%AA%9E%E3%81%AE%E3%81%BF%E3%81%A7%E8%A1%A8%E7%A4%BA%E3%81%97%E3%81%9F%E3%81%84%EF%BC%89)
* [2021-04-19: Deaktivieren von Automatischer Übersetzung von Video titeln.](https://support.google.com/youtube/thread/106671513/deaktivieren-von-automatischer-%C3%9Cbersetzung-von-video-titeln)
* [2021-04-29: WHEN YOUTUBE IS GOING TO FIX THE AUTO TRANSLATE OPTION?](https://support.google.com/youtube/thread/107932674/when-youtube-is-going-to-fix-the-auto-translate-option)
* [2021-05-01: How to stop auto translation of youtube video titles?](https://support.google.com/youtube/thread/108141426/how-to-stop-auto-translation-of-youtube-video-titles)
* [2021-08-03: How to prevent YouTube from automatically translating english video titles?](https://support.google.com/youtube/thread/119703409/how-to-prevent-youtube-from-automatically-translating-english-video-titles)

As for how to implement a fix, I suggest that, if Vanced recognizes that a title is automatically mangled by Google Translate, it tries to query the servers for the video title/description from a spoofed geolocation or language setting (ideally using the list of languages set in the Android device itself), and if it finds a non-translated response, it replaces the title and description with that..

**Comment by milindgoel15** [comment] 2022-01-11 10:56
Duplicate of #908

**Closed** 2022-01-11 10:56 UTC
Labels: enhancement
