### ISSUE TITLE
[Bug] The community tab doesn't work

### ISSUE THREAD

**Issue by Abonity** [YTVanced/Vanced#720] opened 2021-04-28 21:05 UTC
**Bug description**
When i go to the community tab on YouTube vanced, does show nothing, only a blank space.

**Variant**
Non-Root

**Vanced version**
16.14.34

**Android version**
Android 9.0 - Pie

**Device**
Lenovo z6 lite

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any Channel with community posts
3. you Will not ser nothing, only a blank space

**Expected behavior**
Should show community posts, but not shows

![Screenshot_2021-04-28-18-04-46-1214082701](https://user-images.githubusercontent.com/83374077/116472411-43003500-a84c-11eb-93a6-1247f8bc0649.png)

**Comment by KevinX8** [comment] 2021-04-28 21:09
duplicate of #678

**Closed by KevinX8** 2021-04-28 21:09 UTC
Labels: bug
