### ISSUE TITLE
[Idea] Can you add dislikes based on API and user estimations after December 13th

### ISSUE THREAD

**Issue by adamlahbib** [YTVanced/Vanced#1416] opened 2021-11-24 08:14 UTC
**Description**
Replace me with a clear and detailed description of the idea.

To be exact, can you implement something like this browser extension, for Vanced? https://github.com/Anarios/return-youtube-dislike

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment] 2021-11-24 08:19
Duplicate of #1394 

cant u all just look at previous issues before making a new one? is it too hard?

**Closed by milindgoel15** 2021-11-24 08:19 UTC
Labels: enhancement
