### ISSUE TITLE
[Bug] Homepage isnt refreshing 

### ISSUE THREAD

**Issue by Kobewaxman** [YTVanced/Vanced#849] opened 2021-05-21 17:33 UTC
**Bug description**
On YTvanced often when I try refreshing my homepage (not the explore/trending pages) it does not refresh.

**Variant**
Non-Root

**Vanced version**
16.16.38 - Build - unknown 

**Android version**
Android 10 

**Device**
Samsung Galaxy S20 fe

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Try refreshing page
3. Click on a video
4. Return to homepage
5. Repeat steps 2-4 until you get my results. (Usually within 5 tries)

**Expected behavior**
Expected the homepage to refresh but it did not.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by Kobewaxman** [comment] 2021-05-21 17:35
Sry actually I have android 11

**Comment by milindgoel15** [comment] 2021-05-21 17:43
Duplicate of #252

**Closed by milindgoel15** 2021-05-21 17:43 UTC
Labels: bug
