### ISSUE TITLE
[Bug] the Sponsorblock segment adding button, sometimes is covered by the close button X, when in landscape mode and for example the playlist section is shown on the right 

### ISSUE THREAD

**Issue by GitExploraa** [YTVanced/Vanced#1700] opened 2022-03-01 13:48 UTC
**Bug description:**
the Sponsorblock segment adding button, sometimes is covered by the close button X, when in landscape mode and the comment section for example is shown on the right 

**Have you read vanced guides already? (YES/No)**
Yes

**Variant:**
Non-Root

**Vanced version:**
17.03.38

**Link used to download vanced:**
from the official website

**Android version:**
Android 12

**Device:**
Google Pixel 4

**Steps to Reproduce**
as described on the title

**Expected behavior:**
as described on the title

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._
![image](https://user-images.githubusercontent.com/44654056/156180763-266de01e-fbc3-4a23-8526-0319ce085fdf.png)

**Comment by milindgoel15** [comment] 2022-03-01 17:52
Duplicate of #1653

**Closed by milindgoel15** 2022-03-01 17:52 UTC
Labels: bug
