### ISSUE TITLE
[Bug] Audio not controlled from BT TWE if phone first locked.

### ISSUE THREAD

**Issue by zulu625** [YTVanced/Vanced#953] opened 2021-06-11 19:01 UTC
**Bug description**
If start playing video and lock the phone without without doing any BT control, after the phone is locked BT controlls don't work. If after starting the video at least one control is used before locking, the controls will work even if the phone is locked (following at least one control used with the screen unlocked)

**Variant**
Non-Root

**Vanced version**
 v16.16.38

**Android version**
Android 11 

**Device**
Pixel 5

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Have earbuds connected BT
2. Play video.'
3. **Don't** try BT controls
3. Lock phone
4.  try BT controls 
5. Controls don't work.

**Expected behavior**
1. Open the app
2. Have earbuds connected BT
2. Play video.'
3. **Don't** try BT controls
3. Lock phone
4.  try BT controls 
5. Controls should work.

Workaround:

1. Open the app
2. Have earbuds connected BT
2. Play video.'
3.  Try any of the BT controls from earbuds
3. Lock phone
4.  try BT controls 
5. Controls work.

Not a biggy with the workaround.

**Comment by milindgoel15** [comment] 2021-06-12 03:27
Duplicate of #873

**Closed by milindgoel15** 2021-06-12 03:28 UTC
Labels: bug
