### ISSUE TITLE
[Bug] SponsorBlock segments at the end of videos in playlists causes playback on the next video to start where the previous one ended.

### ISSUE THREAD

**Issue by bigyihsuan** [YTVanced/Vanced#1726] opened 2022-03-06 20:03 UTC
**Bug description:**
SponsorBlock segments at the end of videos in playlists causes playback on the next video to start where the previous one ended. In general, SponsorBlock/Vanced does the following:

1. Playback reaches the end-of-video segment.
1. SponsorBlock skips the segment, putting playback at the end of the video.
1. Since the playback is at the end of the video, the playlist advances to the next video.
1. *However*, playback moves to the time of the end of the *current* video in the *next* video, i.e. if the current video's end is 2:34 and the next video is 10:23 long, playback in the next video begins at 2:34.
1. If the next video is shorter than the current video, it stops playback and auto-advance and brings up the "end of video" screen.

This doesn't happen with the SponsorBlock extension in Google Chrome, so this makes me think it's Vance's implementation that is the problem.

**Have you read vanced guides already? (YES/No)**
Yes.

**Variant:**
Root

**Vanced version:**
Vanced 17.03.38 - Build 01.55.00

**Link used to download vanced:**
https://github.com/YTVanced/VancedManager/releases/latest/download/manager.apk

**Android version:**
Android 10 (Oxygen OS 10.3.8.GM57AA)

**Device:**
OnePlus 7 (GM1700)

**Steps to Reproduce**
* Find two videos, one with a SponsorBlock segment at the end of it.
* Put both videos into a playlist.
* Let the video with the segment finish and skip the segment.
* See as playback in the next video start at where the first video should have ended.

**Expected behaviour:**
SponsorBlock segments at the end of videos in a playlist should end the video, then move on to the beginning of the next video rather than somewhere in the middle/end depending on the length of the previous one.

**Additional Videos**
Here are two videos of this bug in action, both for the 'long to short' and 'short to long' cases.

* [Long to short](https://www.youtube.com/watch?v=UNNnsG_yWU8)
* [Short to long](https://www.youtube.com/watch?v=Ic69u8J1gXc)

Forum post here: https://forum.xda-developers.com/t/app-mod-root-nonroot-youtube-vanced-edition.3758757/page-998#post-86533051

**Comment by GentlePuppet** [comment] 2022-03-06 22:45
Ah, so this is what's been happening to me. I was trying to figure out what was happening, this is very annoying.

**Comment by milindgoel15** [comment] 2022-03-07 02:26
Duplicate of https://github.com/YTVanced/Integrations/issues/76

**Closed by milindgoel15** 2022-03-07 02:26 UTC
Labels: bug
