### ISSUE TITLE
[Idea] Enable forced selectable text on title, description and comments section

### ISSUE THREAD

**Issue by KyleBroflowski** [YTVanced/Vanced#871] opened 2021-05-25 09:25 UTC
**Description**
I know the stock YouTube doesn't have the feature. It would be absolutely worthy to be able to copy any text from the app without the need of any third party apps to force copying. This especially helps for viewers who view multiple languages. The text selection menu should have options for cut, copy, share, translate and web search if it can be integrated into YouTube vanced. 

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment] 2021-05-25 10:08
Duplicate of #642

**Closed by milindgoel15** 2021-05-25 10:08 UTC
Labels: enhancement
