### ISSUE TITLE
[Bug] Looping after skipping SponsorBlock segment

### ISSUE THREAD

**Issue by b-aaron** [YTVanced/Vanced#1159] opened 2021-08-09 21:02 UTC
**Bug description**
Whenever SponsorBlock skips a segment it falls into a loop, as it doesn't skip to the end of the segment (but rather 1-2 seconds before the end) but still sees the part that I am watching (that it has skipped me to) as a part of the segment, re-skipping me to that same part. To get out of this loop I need to manually skip out of it/move the bottom bar. Similar to this, if the segment is manually skippable, the skip button stays there for a little longer.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 10

**Device**
ZTE Axon 10 Pro

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Have SponsorBlock turned on
3. Open a video with sponsor segment
4. Reach that segment
5. SponsorBlock skips segment
6. Stuck in a loop

**Expected behavior**
I expect to not get stuck in a loop. The SponsorBlock should skip the video to the right moment (not a few seconds before the end of the segment).

**Comment by milindgoel15** [comment] 2021-08-10 03:25
It's enough now. I am closing this issue because the issue is related to vanced sponsorblock hence it should be created in vanced sponsorblock repository, not vanced repository.

**Closed by milindgoel15** 2021-08-10 03:25 UTC
Labels: bug
