### ISSUE TITLE
[Bug] cannot connect with ‘update your google play service’ message

### ISSUE THREAD

**Issue by acedialife** [YTVanced/Vanced#706] opened 2021-04-27 13:22 UTC
**Bug description**
cannot casting to chromcast with google tv, with ‘update your google play service’ message

**Variant**
Non-Root

**Vanced version**
16.14.34 - Build - 01.50.01

**Android version**
Android 10, 11

**Device**
Samsung Galaxy S10e
Blackshark 2
Xiaomi redmi 5 plus

**Steps to Reproduce**
Steps to reproduce the error:
1. install vanced
2. casting to chromecast(this time working well)
3. close vanced(not to go home)
4. casting to chromecast again
5. cannot connect with message

**Comment by bakatek** [comment] 2021-04-29 09:23
Same for me on a S7. No updates available, when i click on message it open Play store on a white screen with an infinite loading Roll.

**Comment by mpenguin** [comment] 2021-04-29 11:46
Experiencing the same issue following the same set of steps (Cast to Chromecast, get message).

Variant
Non-Root

Vanced version
16.14.34 - Build - 01.50.01

Android version
Android 10

Device
Samsung Note 9

**Comment by vemfanvet** [comment] 2021-04-29 16:10
Same issue when casting to chromecast 
Non root 
16.14.34
Ansroid 10
Oneplus 7t

**Comment by Gamerx007** [comment] 2021-04-29 20:13
Same Issue when trying to cast to my google Chromecast UHD and Chromecast 2nd and 3rd Gen

Non Root
Vanced version:
16.14.34 - Build - 01.50.01

Android 11 
Samsung Galaxy S10 Plus
and
Android 9
Samsung Galaxy S8 Plus

**Comment by KevinX8** [comment] 2021-04-30 00:03
duplicate of #688

**Closed by KevinX8** 2021-04-30 00:03 UTC
Labels: bug
