### ISSUE TITLE
[Idea] A video queuing functionality 

### ISSUE THREAD

**Issue by GeniusNerd695** [YTVanced/Vanced#1026] opened 2021-06-29 04:43 UTC
**Description**
A video queque feature like in the desktop youtube website where you can create a temporary collection of videos you want to watch with an option of converting the queque into a permanent playlist

**Comment by Nishit-Dua** [comment] 2021-06-30 04:33
I really like this, really hope they implement this

**Comment by CHIUNDA** [comment] 2021-08-21 01:14
Wish Queuing on Android was available

**Comment by hafizmuhmmadismail** [comment] 2021-09-15 11:40
I sometime use another app for Android but that app is total bulshit except add queuing option. I really appreciate if someone add this feature in vanced app

**Comment by milindgoel15** [comment] 2021-09-15 13:11
Duplicate of #333

**Closed by milindgoel15** 2021-09-15 13:11 UTC
Labels: enhancement
