### ISSUE TITLE
[Idea] add hard no to subtitles/captions

### ISSUE THREAD

**Issue by Jurtaani** [YTVanced/Vanced#1505] opened 2022-01-02 08:53 UTC
**Description**
I and many others have been bombarded by the unwanted subtitles on videos, no matter if i put in my profile settings and/or the app settings that I do not want them. YouTube still enables them automatically and sometimes even in the very next video in my Playlist or the next one that I manually open. 
This means that I have to constantly be clicking on the cc button to disable them and that to me is almost as annoying as constant ads would be. 
So would it be possible to add a hard no to subtitles inside the Vanced app settings, so that user doesn't have to constantly be disabling option that they have opted out in all the possible places.

**Comment by milindgoel15** [comment] 2022-01-02 08:57
Duplicate of #1358

**Closed by milindgoel15** 2022-01-02 08:57 UTC
Labels: enhancement
