### ISSUE TITLE
[Bug] Casting fails 100 percent of the time on multiple version of Android

### ISSUE THREAD

**Issue by awesomeferret** [YTVanced/Vanced#1679] opened 2022-02-24 03:35 UTC
**Bug description:**
Casting to Chromecast compatible devices fails, throws a "youtube vanced won't run unless you update GooglePlay Services". There is, of course, no update to update to (latest version of Vanced MicroG) and downgrading Vanced fixes the issue.

**Have you read vanced guides already? (YES)**
If your answer is no, please consider reading before creating this issue. The guides can be found in the readme section of this repository. 

**Variant:**
nonroot
**Vanced version:**
Replace me with the exact version of vanced you are using. It is mandatory to report issues from the latest available versions only. For example, v17.03.38. This is 100 percent reproducible on Android 8 and 9.

**Link used to download vanced:**
Vanced manager

**Android version:**
8, 9 

**Device:**
LG V20, LG V40

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Attempt to cast

**Expected behaviour:**
Video casts to Chromecast device.

I would share logs, but I can't for the life of me find out where they are stored.

Please, do not close this issue with a "ROM issue" comment. This is a serious bug that is 100 percent reproducible on 100 percent stock ROMs, so, PLEASE think very hard about the optics of saying "ROM issue" and immediately closing it like my fullscreen bug report was. At least, tell me what the heck "ROM issue" means.

**Comment by milindgoel15** [comment] 2022-02-24 03:57
Duplicate of #688

**Closed by milindgoel15** 2022-02-24 03:57 UTC
Labels: bug

**Comment by awesomeferret** [comment] 2022-02-24 04:03
Thank you for an explanation. I tried searching for "casting" but nothing came up, so I thought it was new. Very disappointing that I basically have to use an old version of Vanced to cast, but it is what it is. I suggest putting a little blurb under the "cast button" option in the layout so that it's very obvious that the vast majority of Vanced users won't be able to use casting features. Franky, it should probably be disabled by default.
