### ISSUE TITLE
[Bug] Pull to refresh only works once

### ISSUE THREAD

**Issue by Pr0x1mas** [YTVanced/Vanced#1525] opened 2022-01-13 00:41 UTC
**Bug description:**
When pulling down to refresh on the main home feed, it will work once. After this, it will show the overscroll animation (and not refresh) when you pull down. By closing the app from the recents menu, it will allow me to refresh again when I open the app, however once more after a refresh I'm stuck.

**Have you read vanced guides already? (YES)**

**Variant:**
Root

**Vanced version:**
16.29.39

**Link used to download vanced:**
Through Vanced Manager sourced through the official site.

**Android version:**
LineageOS 18.1 (Android 11)

**Device:**
Pixel 3A

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Scroll up past top in order to refresh
3. Do this again

**Expected behaviour:**
Home feed can be refreshed as many time as the user wants without reloading app.

**Comment by milindgoel15** [comment] 2022-01-13 03:24
Duplicate of #252

**Closed by milindgoel15** 2022-01-13 03:24 UTC
Labels: bug
