### ISSUE TITLE
[Bug] General Layout ad removal breaks pull to refresh and hides chips

### ISSUE THREAD

**Issue by Lycerion** [YTVanced/Vanced#1152] opened 2021-08-08 20:05 UTC
**Bug description**
This seems to be caused by the app thinking it is scrolled down below the ad as it is hidden even when it is as far up as possible. It causes pull to refresh to break and causes chips to auto hide on load and not come back. This is only a guess, though.

**Variant**
Non-Root

**Vanced version**
16.20.35 build 1.53.00

**Android version**
10, May kernel, June patch, one UI 2.5

**Device**
Samsung Note 9

**Steps to Reproduce**
Setting is enabled by default. Intended behavior can be restored by disabling it at the cost of having ad blocks.

**Expected behavior**
Swiping down when at the top of the home feed should cause it to refresh. Chips should be shown when window is scrolled upward and hidden when scrolling down, as in regular app.

**Comment by milindgoel15** [comment] 2021-08-09 03:41
For real? Can't you all read changelogs? Or previous issues?

Duplicate of #252

**Closed by milindgoel15** 2021-08-09 03:41 UTC
Labels: bug

**Comment by Lycerion** [comment] 2021-08-09 03:53
I did scroll through the open issues but I didn't see that one since it's closed. Does that mean a fix is already in the works?

Also the chips issue is not mentioned by that but it is likely caused the same thing.

**Comment by milindgoel15** [comment] 2021-08-09 03:58
It's closed because it's not vanced bug. Although, disabling home ads if it's enabled does fix it for certain users hence I am not quite sure if it could be causing the issue. I have to ask this from xfile.

Chips issue? What's that?

**Comment by Lycerion** [comment] 2021-08-09 04:13
In the original submission it's noted that changing to 1 px from 0 px resolves the issue, can this be done in the meantime?

The suggested categories/tags at the top that google calls chips are also permanently hidden when hiding the ads is enabled since it thinks it's scrolled down.

**Comment by milindgoel15** [comment] 2021-08-09 04:22
That has to be done by Google as it's related to litho and litho isn't our product/feature.
