### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by lukamacha** [YTVanced/Vanced#1047] opened 2021-07-03 17:39 UTC
**Bug description**
when i opening app its just closeing or saying no internet if crashing for 1 sec seeung videos

**Variant**
Non-Root

**Vanced version**
v16.20.35

**Android version**
 Android 10

**Device**
xiaomi note 8 pro

**Steps to Reproduce**
Steps to reproduce the error:
  can't LOL

**Expected behavior**
its shoud open and possible to watch video but its closed or sayed no internet

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment] 2021-07-04 01:53
Duplicate of #1043

**Closed by milindgoel15** 2021-07-04 01:53 UTC
Labels: bug
