### ISSUE TITLE
[BUG] Can't sign in to Google Account after Password change.

### ISSUE THREAD

**Issue by Kess-Apps** [YTVanced/Vanced#1717] opened 2022-03-05 09:27 UTC
**Bug description:**
A few weeks ago, I changed the password of one of my Google Accounts while I was logged in YT Vanced. Then I could not log in into the normal YT App. I updated it, and I was able to log back in.
In YT Vanced, it says something like 'Please check your Network connection'. But removed the account from my Phone complete and tried again, but still the same error. So I have no chance to use my main Google account in YT Vanced. (I also reinstaled YT Vanced in three different versions. Also, Vanced Manager :D)

**Have you read vanced guides already? (YES/No)**
YES

**Variant:**
Root

**Vanced version:**
I tried it in the last 3 Versions. Now I have v17.03.38

**Link used to download vanced:**
Vanced Manager

**Android version:**
9

**Device:**
Motorola One Action

![Screenshot_20220305-101424](https://user-images.githubusercontent.com/72557998/156877302-fb42f39b-4c45-439c-bb3d-078a7e483253.png)

**Comment by milindgoel15** [comment] 2022-03-05 09:29
Duplicate of #786

**Closed by milindgoel15** 2022-03-05 09:29 UTC
Labels: bug

**Comment by Kess-Apps** [comment] 2022-03-05 10:07
https://telegra.ph/Troubleshooting-for-vanced-03-19#A:-Please-check-your-internet-connection-error
It looks like this on my phone. But I don't have an account with a microG Icon.

**Comment by milindgoel15** [comment] 2022-03-05 10:25
Your issue is kinda confusing as well. You wrote that you are using "root" in the variant section but at the same time, you are able to use both stock and vanced at the same time because you tried logging in on yt after password change.

First confirm that you are really using a root version. Because the root version shouldn't be having such login issue in the first place.

**Comment by Kess-Apps** [comment] 2022-03-05 10:26
I am not sure. How can I see which version I have?

**Comment by milindgoel15** [comment] 2022-03-05 10:30
> I am not sure. How can I see which version I have?

Then why did you wrote root in the variant section when you don't even know what you are using? 

Show the screenshot of vanced manager and the application info of ytvanced.

**Comment by Kess-Apps** [comment] 2022-03-05 10:31
![Screenshot_20220305-113108](https://user-images.githubusercontent.com/72557998/156879480-6673616b-8a2d-496c-9fdd-3a16667774d7.png)

**Comment by Kess-Apps** [comment] 2022-03-05 10:36
I think I have thought about the rights on the phone and not the version... Sry

**Comment by milindgoel15** [comment] 2022-03-05 10:38
So are you rooted in real? Or you just thought you are rooted and running the root version of vanced?

Because as far as your screenshot, you are having a non-root version which requires microG for sign-in. So you also have an microG account added into your device. Go to your device settings > accounts > find vanced microG.

Then perform all the steps given in the troubleshooting.

**Comment by Kess-Apps** [comment] 2022-03-05 10:42
I don't see a microG account...

![Screenshot_20220305-114054](https://user-images.githubusercontent.com/72557998/156879782-4c09067b-b511-41c1-bf93-fe171cca5aff.png)

**Comment by milindgoel15** [comment] 2022-03-05 10:46
![IMG_20220305_161433.jpg](https://user-images.githubusercontent.com/45682747/156879842-10e0d195-3731-48a3-94df-54224326a225.jpg)

The account with blue background and small g are microG accounts. (You are seeing such icon because you were using old version of microG)

Remove the one on which password was changed and re-add it from vanced.

**Comment by Kess-Apps** [comment] 2022-03-05 11:14
ah. THANKS!!!
