### ISSUE TITLE
[Bug] Picture in picture malfunction

### ISSUE THREAD

**Issue by phenylphart** [YTVanced/Vanced#851] opened 2021-05-22 07:32 UTC
**Bug description**
Everytime I have a video playing and I press the home button or overview button, the video is in a small window on the bottom right. If I try to move it anywhere else, it gets dragged offscreen through the bottom of the phone. Mode does not work in landscape orienation.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11

**Device**
Samsung Galaxy Note 10+

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Press home or overview button
3. Move picture in picture window

**Expected behavior**
Should stay to the left or right of the phone screen near where I leave the window.

**Comment by milindgoel15** [comment] 2021-05-22 08:56
Duplicate of #197

**Closed by milindgoel15** 2021-05-22 08:56 UTC
Labels: bug
