### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by hJDajn99** [YTVanced/Vanced#914] opened 2021-06-04 00:30 UTC
**Bug description**
I have close to one year since I started to use this app, I never had any problem. Meanwhile I changed my phones and still worked, but recently I changed again and I have a Samsung Galaxy S10+, after 1 month (yesterday), I opened the app and it shows " no Internet connection/connect to Internet , I tried to switch to data, I used another WiFi and still nothing,  then I tried also to delete cache, uninstall/reinstall the app and still doesn't work. 

**Variant**
Non-Root 

**Vanced version**
4.29.50- Build 

**Android version**
Android 11 - UI 3.1 

**Device**
Samsung Galaxy S10+ 

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app 'Vanced manager'
2. Click on 'the icon to open "YouTube vanced" / or directly from the home screen - 'YouTube vanced'
3.  The app shows " no Internet connection/connect to Internet 

**Expected behavior**
I'd like to know what I can do to use again the app.
![Screenshot_20210604-012555_Vanced Manager](https://user-images.githubusercontent.com/52925473/120728204-5306d680-c4d4-11eb-948b-c59daa2b3b84.jpg)
![Screenshot_20210604-012324](https://user-images.githubusercontent.com/52925473/120728207-539f6d00-c4d4-11eb-9f4d-4da2b0aca690.jpg)
![Screenshot_20210604-012316](https://user-images.githubusercontent.com/52925473/120728208-54380380-c4d4-11eb-89c0-a86beab06d10.jpg)

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment] 2021-06-04 03:16
Duplicate of #786

**Closed by milindgoel15** 2021-06-04 03:16 UTC
Labels: bug
