### ISSUE TITLE
[Bug] YouTube and YouTube Music all say that they can not connect to my WiFi

### ISSUE THREAD

**Issue by Kalmai221** [YTVanced/Vanced#794] opened 2021-05-08 20:00 UTC
**Bug description**
Whenever I go onto YouTube Vanced and YouTube Music, it always shows "Unable to connect to the Internet" when I always try to turn on and off my WiFi to get it to work. When I do it, still didn't work.

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 9.0 - Pie

**Device**
Huawei Y6 2019

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the apps
2. Click on 'Retry'
3. Internet wouldn't retry to work

**Expected behavior**
They should try and fix it.

**Comment by milindgoel15** [comment] 2021-05-09 02:27
Duplicate of #724

**Comment by milindgoel15** [comment] 2021-05-09 02:27
Update to v16.16.38

**Closed by milindgoel15** 2021-05-09 02:27 UTC
Labels: bug

**Comment by Kalmai221** [comment] 2021-05-09 06:16
![Screenshot_20210509_070520_com.vanced.manager.jpg](https://user-images.githubusercontent.com/67641154/117562367-628e2d80-b096-11eb-86df-5adc60692a6d.jpg)

Always been that version
