### ISSUE TITLE
Would it be possible to add a way to block channels?

### ISSUE THREAD

**Issue by duradara** [YTVanced/Vanced#1632] opened 2022-02-17 23:58 UTC
In PC I use [Blocktube](https://github.com/amitbl/blocktube) to block chanels I have no interest in or are annoying. Would it be possible to add something like it to the app or is it too difficult?  
Sorry if my english is bad

**Comment by milindgoel15** [comment] 2022-02-22 04:07
Duplicate of #1016

**Closed by milindgoel15** 2022-02-22 04:07 UTC
Labels: enhancement
