### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Nihilus1** [YTVanced/Vanced#1098] opened 2021-07-21 08:35 UTC
**Bug description**
I can't log in to my google account anymore, as it says I must be connected to the network (I am), after that the app shuts down automatically.

**Variant**
Non-Root

**Vanced version**
16.20.35

**Android version**
Android 11

**Device**
Samsung Galaxy A21s

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on the User icon in the top right corner to log in
3. Choose login
4. Choose your Profile
5. Wait for it to log in and see the notification, that you can't log in because I'm apparentely not connected to the network.

**Expected behavior**
I thought i could log in to my YouTube Account, but it wouldn't let me, even after reinstalling.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment] 2021-07-21 08:54
Duplicate of #786

**Closed by milindgoel15** 2021-07-21 08:54 UTC
Labels: bug
