### ISSUE TITLE
[Bug] Notifications go crazy

### ISSUE THREAD

**Issue by UnzenSekai** [YTVanced/Vanced#1176] opened 2021-08-14 00:18 UTC
Soooo no matter how many times I erase the YouTube Vanced notifications, they still always come back, and still the exact same notifications. Also, even uninstall, re-download then re-install does nothing, help me please it's lagging so much

Also, I can't send videos of the problem with GitHub so please contact me by email so I Can sens it to you

**Variant**
Non-Root

**Vanced version**
Version v16.29.39

**Android version**
Android 7.0

**Device**
Blackview BV6000 and Samsung Galaxy Tab A

**Steps to Reproduce**
Steps to reproduce the error:
I don't know, it just does it, the first Time sometimes immidatly, sometimes after months !

**Expected behavior**
I still want to see new videos that Comes out from my favorite youtubers, so disactivate notifications are out of the way... I just want them to work as normal ;-;

**Comment by milindgoel15** [comment] 2021-08-14 01:53
Duplicate of #1107

**Closed by milindgoel15** 2021-08-14 01:53 UTC
Labels: bug
