### ISSUE TITLE
[Bug] Random videos not loading in the latest Vanced version.

### ISSUE THREAD

**Issue by DolanD2** [YTVanced/Vanced#1694] opened 2022-02-27 16:02 UTC
**Bug description:**
Whether i am scrolling through shorts or watching videos from the Home page there is a chance that a video/livestream won't load, the loading wheel just spins infinitely, cleaning the cache doesn't help. 

**Have you read vanced guides already? (YES/No)**
YES

**Variant:**
Non-Root

**Vanced version:**
17.03.38

**Link used to download vanced:**
https://vancedapp.com

**Android version:**
Android 11

**Device**
Samsung Galaxy A30s

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on the videos until one won't load.

**Expected behaviour:**
I expected the video to load but it didn't.

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._
Example random videos:
![Screenshot_20220227-165737](https://user-images.githubusercontent.com/84463839/155889796-5dbd4d26-6c42-48cb-b369-e4551d8a255a.png)
![Screenshot_20220227-165841](https://user-images.githubusercontent.com/84463839/155889802-35f3f3f7-4498-4ba6-a4e8-24d81899b655.png)
![Screenshot_20220227-173516](https://user-images.githubusercontent.com/84463839/155891015-0bf93e01-3d65-4715-8a74-c7787db1488b.png)

**Comment by milindgoel15** [comment] 2022-02-28 04:27
Duplicate of #1685

**Closed by milindgoel15** 2022-02-28 04:27 UTC
Labels: bug

**Comment by DolanD2** [comment] 2022-02-28 17:28
So it's not fixable? Is this Google or Vanced issue? I disabled private dns setting and these videos work now but it's not comfortable to turn off that setting everytime a video doesn't load. I can't keep it disabled because it blocks ads in the whole system.  :'/

**Comment by DolanD2** [comment] 2022-02-28 17:30
> Duplicate of #1685

So it's not fixable? Is this Google or Vanced issue? I disabled private dns setting and these videos work now but it's not comfortable to turn off that setting everytime a video doesn't load. I can't keep it disabled because it blocks ads in the whole system.  :'/

**Comment by milindgoel15** [comment] 2022-02-28 17:33
It's neither google issue not vanced. Your private DNS whatever you are using seems to be blocking YouTube altogether so you need to fix your DNS host sources that you are using in it. 

Also, if you use some well known DNS, you will have no issues whatsoever. I, myself use nextdns and have no issues. If you want, i can share the sources i am using in it.

**Comment by DolanD2** [comment] 2022-02-28 17:36
Thanks!
