### ISSUE TITLE
[Bug] Can't Pause location-based recommendations

### ISSUE THREAD

**Issue by GuilhermePiorno** [YTVanced/Vanced#1705] opened 2022-03-02 14:11 UTC
**Bug description:**
The option for pausing location-based recommendations can be turned on, but if you back out and go there again it's kept unchecked.

**Have you read vanced guides already? (YES/No)**
No.

**Variant:**
Non-Root

**Vanced version:**
 v4.64.51

**Link used to download vanced:**
vancedapp.com

**Android version:**
Android 11

**Device:**
Galaxy A71

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app.
2. Click on your profile picture on top right.
3. Click on Settings.
4. Click on Privacy & Location.
5. Turn Pause Location-based recommendations ON.
6. Back out of this menu by any method.
7. Enter the Privacy & Location again and it will be turned OFF instead of ON.

**Expected behaviour:**
When you turn it ON and back out and go in there to check, it should remain ON like it does in the Original Youtube App.

**Comment by milindgoel15** [comment] 2022-03-03 03:12
Duplicate of #1256

**Closed by milindgoel15** 2022-03-03 03:12 UTC
Labels: bug
