### ISSUE TITLE
[Idea] VolumeBooster

### ISSUE THREAD

**Issue by JohnuuDev** [YTVanced/Vanced#1509] opened 2022-01-02 16:40 UTC
A volume booster for Youtube, will be a nice feature.

**Comment by milindgoel15** [comment] 2022-01-02 16:42
Duplicate of #1143

**Closed by milindgoel15** 2022-01-02 16:42 UTC
Labels: enhancement

**Comment by PuNiShEr202** [comment] 2022-01-03 09:55
My vanced youtube wont connect to my internet it keeps saying no internet connection

**Comment by milindgoel15** [comment] 2022-01-03 09:59
And why the hell are u saying this in an issue irrelevant to yours. Please create or read issues concerning your problem only.

The solution to your problem is in vanced troubleshooting which can be found in the readme section of this repository.
