### ISSUE TITLE
[Bug] the app disappears and i have to re install it

### ISSUE THREAD

**Issue by eyad-elghareeb** [YTVanced/Vanced#1365] opened 2021-10-31 14:36 UTC
**Bug description**
The app gets deleted for some reason without doing any thing , happens A LOT like twice a day

**Variant**
Root

**Vanced version**
16.29.39

**Android version**
Android 12

**Device**
Realme 3 pro

**Steps to Reproduce**
Steps to reproduce the error:
It happens suddenly 

**Expected behavior**
I guess to stay installed

**Comment by milindgoel15** [comment] 2021-11-01 05:29
Duplicate of #303

**Closed by milindgoel15** 2021-11-01 05:29 UTC
Labels: bug
