### ISSUE TITLE
Cannot open links, refreshing is very unreliable and gardly works

### ISSUE THREAD

**Issue by scumz94** [YTVanced/Vanced#888] opened 2021-05-28 19:22 UTC
Cannot oopen any links at all on Vanced. This used to be possible. Also, cannot redtesh home page most of the time, must restart app to get latest vids etc.

Non-Root
**Vanced versi
on**
16.16.38
Build -

**Android version**
Latest one

**Device**
Samsung Galaxy note 20 ultra

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment] 2021-05-29 02:54
Duplicate of #774 and #252

**Closed by milindgoel15** 2021-05-29 02:54 UTC
Labels: bug
