### ISSUE TITLE
[Bug] Ads displaying in the main video list

### ISSUE THREAD

**Issue by Vianns** [YTVanced/Vanced#1544] opened 2022-01-21 10:13 UTC
**Bug description:**
Ads are displayed (not at every app launch) on the main video list.

**Have you read vanced guides already? (YES/No)**
Yes

**Variant:**
Non-Root

**Vanced version:**
YT Vanced ver. 16.29.39

**Link used to download vanced:**
https://github.com/YTVanced/VancedManager/releases/latest/download/manager.apk

**Android version:**
11 RKQ1.200826.002

**Device:**
Poco F3

**Steps to Reproduce**
1- Open the app
2- See that ads are displayed on the main video list.

**Expected behaviour:**
When opening the app, I expect no ads to be displayed anywhere in the application.

Logcat log: https://www.toptal.com/developers/hastebin/nupobaduge.yaml

Thanks !

**Comment by milindgoel15** [comment] 2022-01-21 11:09
Duplicate of #1314

**Closed by milindgoel15** 2022-01-21 11:09 UTC
Labels: bug
