### ISSUE TITLE
[Bug] max buffer size

### ISSUE THREAD

**Issue by uterus-blower** [YTVanced/Vanced#837] opened 2021-05-18 17:37 UTC
**Bug description**
Max buffer size is not working

**Variant**
Root

**Vanced version**
16.16.38

**Android version**
Android 11

**Device**
Xiaomi redmi note 6 pro

**Comment by milindgoel15** [comment] 2021-05-19 05:48
Duplicate of #729

**Closed by milindgoel15** 2021-05-19 05:48 UTC
Labels: bug
