### ISSUE TITLE
[Bug] YT Vanced notification issues

### ISSUE THREAD

**Issue by SaberAkiyama** [YTVanced/Vanced#1546] opened 2022-01-22 01:18 UTC
**Bug description:**
When I slide down to notification panel, clear all and suddenly it's back in the same video.

I try to force stop and/or clear all the data, but it doesn't work. Even when I restart my phone, it's the same thing. If I try to hard reset, I don't know if I'm going to risk it. 

You should update from the original YouTube app to Vanced app, and fix the notification as soon as possible.

**Have you read vanced guides already? (YES)**

**Variant:**
Non-Root

**Vanced version:**
 v16.29.38 (Latest)

**Android version:**
Android 7.0 (Nougat)

**Device:**
Leagoo M6

**Comment by milindgoel15** [comment] 2022-01-22 04:03
Duplicate of #1107

**Closed by milindgoel15** 2022-01-22 04:03 UTC
Labels: bug
