### ISSUE TITLE
[Idea] A Feature of Removing Shorts icon from the navigation Bar.

### ISSUE THREAD

**Issue by Jainsatyam** [YTVanced/Vanced#1060] opened 2021-07-06 09:03 UTC
We Humbly Request YouTube vanced team to add an option for removing YouTube Shorts from the Feed section and from the navigation Bar .

![IMG_20210706_143142](https://user-images.githubusercontent.com/86193648/124573203-f4cc6b00-de66-11eb-93ad-e9c9640a6fd1.jpg)

**Comment by milindgoel15** [comment] 2021-07-06 10:34
Duplicate of #334

**Closed by milindgoel15** 2021-07-06 10:34 UTC
Labels: enhancement
