### ISSUE TITLE
[Bug] Client Sending Repeating Notifications

### ISSUE THREAD

**Issue by ThePixelPolygon** [YTVanced/Vanced#1193] opened 2021-08-17 23:38 UTC
**Bug description**
The Vanced client seems to be in a loop where the same notifications will constantly send.

**Variant**
Non-Root

**Vanced version**
v16.29.39

**Android version**
Android 9.0 Pie

**Device**
Samsung Galaxy Note 8

**Steps to Reproduce**
Steps to reproduce the error:
1. Pull down the notifications shade
2. Attempt to dismiss a Vanced notification or clear all notifications

**Expected behavior**
Any cleared notifications should not appear again.

**Comment by milindgoel15** [comment] 2021-08-18 01:37
Duplicate of #1107

**Closed by milindgoel15** 2021-08-18 01:37 UTC
Labels: bug
