### ISSUE TITLE
[Bug] Vanced don't save videos on history

### ISSUE THREAD

**Issue by nik2143** [YTVanced/Vanced#1069] opened 2021-07-09 15:09 UTC
**Bug description**
When I see a video using youtube vanced it isn't saved on account history

**Variant**
Root

**Vanced version**
v16.20.35

**Android version**
Android 9

**Device**
Samsung Galaxy S8+

**Steps to Reproduce**
1 Open a video
2 Open youtube history
3 Video isn't showed there

**Expected behavior**
Video seen should be shown on youtube history instead it isn't shown

**Comment by milindgoel15** [comment] 2021-07-09 15:11
Duplicate of #301

**Closed by milindgoel15** 2021-07-09 15:11 UTC
Labels: bug
