### ISSUE TITLE
[Idea] disable Shorts tab

### ISSUE THREAD

**Issue by Hasan-01** [YTVanced/Vanced#1645] opened 2022-02-19 13:54 UTC
**Description**
Ability to disable/enable Shorts tab on home page. Many people don't use shorts tab. Because it's addictive just like TikTok. So it will be great if it get removed.

**Comment by milindgoel15** [comment] 2022-02-19 13:55
Duplicate of #334

**Closed by milindgoel15** 2022-02-19 13:55 UTC
Labels: enhancement
