### ISSUE TITLE
[Idea] option to remove the create short button under videos

### ISSUE THREAD

**Issue by Oregan0** [YTVanced/Vanced#1301] opened 2021-09-28 23:02 UTC
I never use the button and it makes the area under video titles look really cluttered and gets in the way of hitting the save button easily.

**Comment by Oofman1062** [comment] 2021-09-29 01:39
Click Account Icon > Settings > Vanced Settings > Layout Settings > Create Button

**Comment by madgoatz** [comment] 2021-09-29 02:21
duplicate of #1153

**Closed** 2021-09-29 02:36 UTC
