### ISSUE TITLE
[Bug] PiP mode not working properly.

### ISSUE THREAD

**Issue by ansariahmad01** [YTVanced/Vanced#1007] opened 2021-06-24 19:36 UTC
**Bug description**
IN my phone Android 11 the pip mode is not working properly and the playback function in notification bar is also not showing rapidly.. please look into this.. MY vanced is also updated 

**Variant**
Non-Root

**Vanced version**
Replace me with the exact version of vanced you are using. It is mandatory to report issues from the latest available versions only. For example, v16.16.38

**Android version**
Replace me with the version of Android your device have. For example, Android 11 

**Device**
Replace with the name of the device on which you faced the bug. For example, Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by milindgoel15** [comment] 2021-06-25 13:15
Duplicate of #197

**Closed** 2021-06-25 13:15 UTC
Labels: bug
