### ISSUE TITLE
New age verification process for european users

### ISSUE THREAD

**Issue by kineci** [YTVanced/Vanced#613] opened 2021-04-02 17:04 UTC
**Description**
Apparently, there is a new process European users (EU) need to do to watch videos with an age restriction. You have to either make a copy of your ID-Card or type in your credit card information. I'm not even thinking about giving Google this sensitive information. Can or have you implemented a feature on YouTube Vanced to bypass this.
Google Source:
https://support.google.com/youtube/answer/10070779?hl=en#zippy=%2Cif-youre-in-the-european-union-eu-european-economic-area-eea-switzerland-or-united-kingdom

PS: Strangely only happens on the original YouTube App and the Vanced App. On Browsers it's working with the same Account logged in. Maybe got something to do with AdBlockers I have installed? 🤔
![Screenshot_20210401-023046~2](https://user-images.githubusercontent.com/78767752/113436991-17716280-93e6-11eb-87f2-0159eacd3b6c.jpg)

Thanks

**Comment by Krafting** [comment] 2021-04-09 12:45
I won't give google, anymore info, ever, as of for now, I downgraded to the 15.33.34 version or youtube vanced, it doesn't show the age verif. and it still have SponsorBlock Integration,so that's the best compromise I can recommend for now!

**Comment by Akip25** [comment] 2021-04-14 23:38
any chance you can implement an extension similar to sponsor block? 
https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass

**Comment by Player4u** [comment] 2021-04-30 07:51
Try now VancedPlayer v16.x.x.x
Last update had fix some major issues, including with a loging in, casting etc. I had install it regularly and app works great as i can see

**Comment by Player4u** [comment] 2021-04-30 13:45
Oouuu booy, EU users is wide global expression, since we using it here..
I haven't heard for that age issue you mentioned.
As I can see in the link you posted mentioning UK and Switzerland economic area, so, UK is no long member of EU, so it's economic is discounted from Europe Economic, Trade, and Monetary Area, since UK is leave EU by it self from almost two year ago. Thats the reason why UK have some different regulations with google when compared with rest of EU members - countryes. That incude from taxes especially when its about export-import policy, etc. But those age regulations mess, Im surprised too..
And about Switzerland, its high standing economy leader, so advanced so it has abilities to determine in which part exacly wanna cooperate with EU in trading policy. So, Switzerland is there from the begining in EU, but never engaged as a full member, and thats the reason for same difference in regulations with google and rest of the EU countries.
I hope we can now better understand those "device issue" ;))
Best regards!

**Comment by milindgoel15** [comment] 2021-04-30 15:55
Duplicate of #173

**Closed by milindgoel15** 2021-04-30 15:55 UTC
Labels: enhancement
