### ISSUE TITLE
Youtube vanced sey that im offiline but my interent is on 

### ISSUE THREAD

**Issue by andrian1233** [YTVanced/Vanced#872] opened 2021-05-25 21:59 UTC
**Description**
When i open youtube vanced is getting the you are offline text i tryed to reinstall youtube but doesn't work

_Attach images/videos if possible. These can be helpful in figuring out what the 
![Screenshot_20210525-234815](https://user-images.githubusercontent.com/84815796/119573886-27d60600-bdb5-11eb-9579-69fd4cc77184.jpg)
question is about._

**Comment by andrian1233** [comment] 2021-05-25 22:01
In on the last version of youtube vanced 16.16.38

**Comment by milindgoel15** [comment] 2021-05-26 02:59
Duplicate of #786

**Closed by milindgoel15** 2021-05-26 02:59 UTC
Labels: question

**Comment by Welton311** [comment] 2021-05-26 03:39
I have the same problem on the galaxy S8, I have WiFi enabled, and on Youtube Vanced it appears that I am Offline.
