### ISSUE TITLE
[Idea] Option to hide recommend videos and home page feeds.

### ISSUE THREAD

**Issue by Mesum-Hussain** [YTVanced/Vanced#1189] opened 2021-08-17 10:18 UTC
Please implement an option to disable home page feeds and recommend videos below the playing video. 

This feature will helps the users get de-addicted to YouTube. I personally prefer searching for the thing I want to watch and not get trapped into the rabbit hole and waste hours watching useless videos which the algorithm feeds me to keep me hooked. 

'Unhook YouTube' chrome extension has implemented this feature very well. I have been using it for my desktop YouTube progressive webapp and wanted similar experience in my Phone. I was able to download Unhook YouTube extension on my phone using Kiwi browser but wasn't able to download a YouTube progressive webapp. I prefer apps over websites.

Attaching a video of Unhook YouTube on my phone:

**Comment by milindgoel15** [comment] 2021-08-17 10:34
Duplicate of #334

**Closed by milindgoel15** 2021-08-17 10:34 UTC
Labels: enhancement

**Comment by Mesum-Hussain** [comment] 2021-08-17 11:00
> Duplicate of #334

Thanks for pointing out, I checked #334. However it seemed a little different to me. #334 is asking for an option to hide un-useful tabs, but I am asking for an option to disable feeds to de-addict the users from YouTube.

**Comment by milindgoel15** [comment] 2021-08-17 11:02
How are feeds different from tabs?

**Comment by Mesum-Hussain** [comment] 2021-08-17 13:11
> How are feeds different from tabs?

Tabs are the buttons at the bottom of the app which lets you use a feature or to navigate through the app.

On the other hand, feeds are the content that you are consuming, the videos that you are getting suggested to watch on the home page and in the recommendations section. These are not some buttons which let you access some feature or help you navigate through the app.

Hope you get it now.

I want to disable feeds so that I don't get addicted to watching videos.

#344 is asking for disabling useless tabs who's features are rarely used by the majority.

**Comment by Mesum-Hussain** [comment] 2021-08-17 13:31
> How are feeds different from tabs?

Alright I understand your concern for marking my request as duplicate and closing it. But #334 doesn't cover my concern of getting de-addicted to YouTube, adequately. And if I let you close this issue, it will never be implemented or even seen by people. If #334 had covered my issue adequately, I wouldn't have reopened this one. 
So, we have two options over here:

1) modify #334 to adequately cover my issue.

2) let my issue be open.

**Comment by Mesum-Hussain** [comment] 2021-08-17 14:11
> According to your statement, you wanna disable your feeds. So suppose you remove all your feeds from home tab, what would left on your home tab? A blank tab? Would you use vanced with a blank tab? 

Yes that's right! I want a blank screen on my home tab. I don't want any feeds on my home screen, not even ones from the channels I am subscribed to. I just want to be able to search for the video I want to watch at the moment without getting distracted by the clickbait feeds. 

> Because ultimately you want to watch only those videos which u subscribe 

Well I am perfectly fine even if I don't get to watch videos from the channels I subscribed to (because ultimately this is the way YouTube get u hooked..... By showing videos from the channels you like. But I will watch videos from those channels whenever I want, I don't need YouTube to suggest me to watch them).
The only reason I want to keep the subscriptions is that I want to keep an account of my favourite channels.

Anyways if there is a toggle button which disables home page feeds and recommended videos, then it will be very easy to switch back and watch videos in your leisure time.

I actually have a video of Unhook YouTube extension on my phone which I wanted to upload here but it is a big file apparently. That video demonstrate my point perfectly.

I will try to upload it over here somehow.

**Comment by milindgoel15** [comment] 2021-08-17 14:13
So basically the original issue fits ur purpose. No point in making duplicate for same stuff.

**Comment by Mesum-Hussain** [comment] 2021-08-17 14:27
> So basically the original issue fits ur purpose. No point in making duplicate for same stuff. 

Can you please explain how is that? I don't understand how.

**Comment by milindgoel15** [comment] 2021-08-17 14:30
See, you want to disable all distractions, toggling off the tabs will give you the same result as it will with disabling feeds. 

When u disable tab, you won't have any blank spaces either. Hence you saved your time that way

**Comment by Mesum-Hussain** [comment] 2021-08-17 14:40
> When u disable tab, you won't have any blank spaces either. Hence you saved your time that way

Ok I trying to understand your point. What do you propose I will have on my screen if I don't even have a black screen? And disabled all the tabs?

I don't want to offend you but by your arguments it seems like you don't actually e want to resolve this issue and rather shut me up by explaining me something or the other which convinces me.

You can change my mind by giving a rock-solid counter argument.

**Comment by milindgoel15** [comment] 2021-08-17 14:44
> What do you propose I will have on my screen if I don't even have a black screen? And disabled all the tabs?

The library tab that you showed in your own video. Instead of keeping a home blank tab left to it.

**Comment by Mesum-Hussain** [comment] 2021-08-17 15:18
> The library tab that you showed in your own video. Instead of keeping a home blank tab left to it. 

Why can't we have a feature to simply disable the feeds? 
I am sure people will appreciate it a lot. 

I don't understand why you want to catagorise all the issues which looks even very slightly similar into one issue which poorly represent all of them?
I have seen some people complaining that their issue was removed because #334 poorly resemble it. 

I don't know if it is only you who is doing that. But if you are doing it, I would say it's not right..... At least modify the resembling issue to address the concerns of the person whose issue you are closing on this basis.

It is like calling a donkey a duplicate of a zebra. They both just resemble each other but they are completely different animals.

**Comment by milindgoel15** [comment] 2021-08-17 15:23
You are so wrong in so many ways. Good luck with your issue which basically means the same thing as the original, just in a different way.

**Comment by Mesum-Hussain** [comment] 2021-08-17 15:56
> You are so wrong in so many ways. Good luck with your issue which basically means the same thing as the original, just in a different way. 

One thing is is clearly apparent: you are a one big idiotic community manager if you are one at all.

I even told you to close my issue and simply requested you to modify single sentence it the issue #334 is. But you prefer wasting your hours discussing dumb arguments me a writting 10 baseless sentences.

I don't know on what basis you qualify to become a community manager if you don't have the skill to analyse the sentiments off comment. If you cannot understand that #334 was posted because some tabs where idle in the poster's app and it would be good to have them removed but didn't cause any significant inconvenience, on the other hand in my case it is necessary for me to not have feed in order to use YouTube at all because I am getting so much addicted to YouTube and YouTube is one of the necessary apps in my phone unlike Instagram or Facebook (so I cannot remove it).

But no point in explaining you man. You are too stupid to understand it.

I guess I should make my own YouTube client instead of begging for features to some stupid head developers.

**Comment by srghma** [comment] 2021-12-22 12:45
More images of unhook extension in kiwi browser (but this browser often crashes)

![Screenshot_20211222-144202_Kiwi Browser](https://user-images.githubusercontent.com/7573215/147094791-9ab87868-a576-4bc5-8e11-4331087a9c00.jpg)
![Screenshot_20211222-144147_Kiwi Browser](https://user-images.githubusercontent.com/7573215/147094797-2f3659e0-ea13-43b3-8e14-cb2b0f65a076.jpg)

**Comment by Mesum-Hussain** [comment] 2021-12-30 19:59
> More images of unhook extension in kiwi browser (but this browser often crashes)
> 
> ![Screenshot_20211222-144202_Kiwi Browser](https://user-images.githubusercontent.com/7573215/147094791-9ab87868-a576-4bc5-8e11-4331087a9c00.jpg)
> ![Screenshot_20211222-144147_Kiwi Browser](https://user-images.githubusercontent.com/7573215/147094797-2f3659e0-ea13-43b3-8e14-cb2b0f65a076.jpg)
> 

Thanks for sharing! If you would like this feature too then please open #1207 again and request the maintainers in the comments. It would be better if you share these images in the comments of #1207 too. 
I want to promote #1207 more because it's better phrased and properly explains the idea. I wasn't able to explain my reasoning while I was writing this issue though.

**Comment by milindgoel15** [comment] 2021-12-31 11:07
extensions don't work on android clients. they are only made for browsers.
