### ISSUE TITLE
[Idea] Remove age restriction in newer versions of Vance's 

### ISSUE THREAD

**Issue by 002llZeroTwo** [YTVanced/Vanced#1651] opened 2022-02-19 17:00 UTC
I have been using the oldest version of YouTube Vanced because it didn't have age restriction, but now that I updated it because of the dislikes being returned i noticed that I couldn't watch videos that are age restricted. I request that the age restriction will be removed (if possible), there is a code on GitHub that bypasses the age restriction but it's only on tampermonkey for pc. It is made by zerodytrash link: https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/

**Comment by milindgoel15** [comment] 2022-02-19 17:07
Duplicate of #173

**Closed by milindgoel15** 2022-02-19 17:07 UTC
Labels: enhancement
