### ISSUE TITLE
[Bug] replaceme

### ISSUE THREAD

**Issue by Zeromix9** [YTVanced/Vanced#905] opened 2021-05-31 09:26 UTC
**Bug description**
Nothing does load, no subscriptions, no video direct links, nothing.
The only workaround I found was to start the normal YouTube App first, then switch back to Vanced YT, because then I can use this App just as it´s supposed to be used.

**Variant**
Non-Root

**Vanced version**
16.16.38

**Android version**
Android 10

**Device**
Doogee N30

**Steps to Reproduce**
Steps to reproduce the error:
1. Don´t have the normal YouTube App opened or running.
2. Open the app

**Expected behavior**
That the App shows the videos, well acting normaly.

![photo5305489194723947156](https://user-images.githubusercontent.com/21269784/120172179-10f34180-c203-11eb-8a2b-e3dbc6ee615b.jpg)

**Comment by milindgoel15** [comment] 2021-05-31 10:01
duplicate of #786

**Closed by milindgoel15** 2021-05-31 10:01 UTC
Labels: bug
