### ISSUE TITLE
[Idea] Disable autoplay in playlist?

### ISSUE THREAD

**Issue by kaushiksv** [YTVanced/Vanced#1434] opened 2021-12-02 00:14 UTC
**Requesting option to disable auto-advance in playlists.**
It is often desirable to stop after just one video, in a playlist. This is especially true when tapping on a video in Watch History. End of a soothing song, I'm supposed to be calm, but then auto-advance spoils that. Another scenario is YouTube recommending a 'Mix', which is essentially a playlist, whose first song and the thumbnail draws our attention. It could have been just a video suggestion instead of playlist. We all know why Google does these. Hence requesting this feature here.

Best regards,
Kaushik

**Comment by milindgoel15** [comment] 2021-12-02 02:20
Duplicate of #1079

**Closed** 2021-12-02 02:20 UTC
Labels: enhancement
