### ISSUE TITLE
[Bug] I have a problem with youtube vanced I can no longer connect my google account I have changed my password there can be and since youtube vanced considers me offlineCan somebody help me please

### ISSUE THREAD

**Issue by Kadet37** [YTVanced/Vanced#1407] opened 2021-11-21 09:39 UTC
**Bug description**
Replace me with a clear and detailed description of the bug.

**Variant**
Non-Root/Root

**Vanced version**
Replace me with the exact version of vanced you are using. It is mandatory to report issues from the latest available versions only. For example, v16.16.38

**Android version**
Replace me with the version of Android your device have. For example, Android 11 

**Device**
Replace with the name of the device on which you faced the bug. For example, Samsung Galaxy S8

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

**Comment by TheAmazingBen100** [comment] 2021-11-21 11:49
1: Go to Device Settings > Accounts
2: Remove the MicroG account
3: Go back to MicroG settings
4: Re-add your account.

**Comment by milindgoel15** [comment] 2021-11-21 14:00
Duplicate of #786

**Closed by milindgoel15** 2021-11-21 14:00 UTC
Labels: bug
