### ISSUE TITLE
[Bug] Youtube Music Vanced cannot play anymore music from playlist

### ISSUE THREAD

**Issue by TitaneBoy** [YTVanced/Vanced#1404] opened 2021-11-19 04:20 UTC
Hello there. First of all, thank you a lot for this awsome apps..
Now, since today, I don't know why but my Youtube Music Vanced cannot play any song/tune from personal playlist. It seems the "Radio" button is activated but the "Play" button is disabled. So there is only random music, kind of related to what I want to listen on my playlist, that is playing...but not my selected songs in my list.. :-(

I'm using YouTube Music Vanced v4.39.50, with Vanced microG v0.2.22.212658
Android: 8.0.0, on LG V20

Do you think it's a bug from Vanced or it's somehow related from the true Youtube Music app ?

Thanks a lot for your help

**Comment by milindgoel15** [comment] 2021-11-19 04:34
Duplicate of #1397

**Closed by milindgoel15** 2021-11-19 04:34 UTC

**Comment by HarshSPatel** [comment] 2021-12-08 00:02
Hello,

Was facing the same issue. Uninstalped everything. Reinstalled manager, yt vanced and microg and reverted back on yt music to 4.18.50 and now it seems to work like previously 


[ Note 20 Ultra, Android 11, Canada ]
