### ISSUE TITLE
[Idea] Swiping gestures(Brightness & Volume) support for YTM in Landscape mode (Music Video)

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#1441] opened 2021-12-04 00:58 UTC
I think it would be a great experience for the user to have the same swiping gestures in landscape mode of YTM Vanced, which are already present in Vanced. When your watching the music video, Brightness gestures & Volume gestures would be an awesome addition. 

![Screenshot_20211204-015204031.png](https://user-images.githubusercontent.com/73917917/144690359-4be19181-3c65-4606-bc96-4a95796021d3.png)

Would also spare the volume buttons of our phone from breaking too early. 
Wish every app had those swiping brightness & volume gestures.

It would be highly appreciated if the Devs implement this idea 🙏🏻🙂

**Comment by milindgoel15** [comment] 2021-12-04 02:32
Don't spam this repo now.

**Comment by milindgoel15** [comment] 2021-12-04 02:33
Duplicate of #1246

**Closed by milindgoel15** 2021-12-04 02:33 UTC
Labels: enhancement

**Comment by Harmonie666** [comment] 2021-12-04 05:52
> Don't spam this repo now.

Sorry, I forgot that I made such request. But apparently it hasn't been answered yet :/

**Comment by milindgoel15** [comment] 2021-12-04 12:10
It doesn't need any answer. When xfile feel like he is free to implement it, he will do it. 

Any further spam will lead to serious actions.

**Comment by Harmonie666** [comment] 2021-12-04 12:12
> It doesn't need any answer. When xfile feel like he is free to implement it, he will do it. 
> 
> Any further spam will lead to serious actions.

Got it. I was thinking when nobody replied it that the Devs perhaps didn't see it.

Please stop threatening me. I don't know what kind of personal issue you got against me, but I'm in no way spamming this place.

**Comment by milindgoel15** [comment] 2021-12-04 12:17
You have already done it enough by making this new one for no reason despite knowing busy life of devs and vanced being a hobby project, not a job and what not or you are proving you don't care about anyone's life except yourself.

**Comment by Harmonie666** [comment] 2021-12-04 12:26
> You have already done it enough by making this new one for no reason despite knowing busy life of devs and vanced being a hobby project, not a job and what not or you are proving you don't care about anyone's life except yourself. 

I already told you, that I did not remember my first duplicate post about this request. If you make a months old post, you sometimes can forget about it, you know. I should've checked first.

Everybody has a busy life. Are you implying that every other humanbeing is sitting on his ass his whole life, and doing nothing? I'm always friendly with everybody involved in these projects, but as a return I'm greeted with this hostility. And it's always by you. No other Dev has treated me/other users this way. Not that I've seen it. 
I've also reported many bugs and errors in this page, isn't that a sign of my appreciation and care for Vanced? I don't know if you are bipolar person, or abuse victim, but please stop abusing the users of these projects. 
If I didn't want these projects to succeed and thrive, I wouldn't bother reporting bugs, and making suggestions.
You don't need to be abusive in your responses to my posts, you can just aswell ignore them if they bother you so much. It's not like I'm posting here every day.
