### ISSUE TITLE
[Bug] App says I cannot connect to internet 

### ISSUE THREAD

**Issue by GeneralPanicGP** [YTVanced/Vanced#1650] opened 2022-02-19 16:44 UTC
App says It doesn't have a connection to the internet, I've tried reinstalling and updating it but to no effect. All other apps work normally. 
Any help?

**Comment by TheAmazingBen100** [comment] 2022-02-19 16:45
#786

**Comment by milindgoel15** [comment] 2022-02-19 16:45
Duplicate of #786

**Comment by milindgoel15** [comment] 2022-02-19 16:46
Very fast lol

**Closed by milindgoel15** 2022-02-19 16:45 UTC
Labels: bug
