### ISSUE TITLE
[Bug] Ads appear on YouTube Vanced home screen

### ISSUE THREAD

**Issue by rughksu** [YTVanced/Vanced#1396] opened 2021-11-17 23:20 UTC
**Bug description**
Ads appear on the app when they shouldn't appear in the first place.

**Variant**
Root

**Vanced version**
v19.29.39

**Android version**
Android 10

**Device**
Samsung Galaxy S8 SM-G950F

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Look at the home screen
3. See an ad

**Expected behavior**
An ad appeared, but the ad shouldn't even be there.

Logcat: 
[vancedlogcat.txt](https://github.com/YTVanced/Vanced/files/7558592/vancedlogcat.txt)

**Comment by milindgoel15** [comment] 2021-11-18 03:16
Duplicate of #1314

**Closed by milindgoel15** 2021-11-18 03:16 UTC
Labels: bug
