### ISSUE TITLE
[Idea] Make that we can copy text from comments/video descriptions

### ISSUE THREAD

**Issue by Likver** [YTVanced/Vanced#1687] opened 2022-02-25 01:53 UTC
Make that we can copy the text of comments, video description easily like in browser, selecting the text or maybe tapping the 3 dots of a comment and tapping an option called "Copy to clipboard" or "Copy". But i personally prefer the same way as in the browser

**Comment by milindgoel15** [comment] 2022-02-25 03:22
Duplicate of #642

**Closed by milindgoel15** 2022-02-25 03:22 UTC
Labels: enhancement
