### ISSUE TITLE
[Bug] video corruption at 480p

### ISSUE THREAD

**Issue by mafs77** [YTVanced/Vanced#1699] opened 2022-03-01 11:50 UTC
**Bug description:**
Generally all videos on my device, P40 lite, open at 480p and there are video corruption at this resolution.
Not all videos have this but it is happening 50/50.
Changing to 720p ou higher image is OK. 
Started happening on last vanced version 17.03.38

**Have you read vanced guides already? (YES/No)**
No

**Variant:**
Non-Root

**Vanced version:**
17.03.38

**Link used to download vanced:**

**Android version:**
Android 10

**Device:**
Huawei P40 lite

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on one video 
3. Video corruption, pixelated, green artifacts 

**Expected behaviour:**

![Screenshot_20220301_115037](https://user-images.githubusercontent.com/99656072/156164245-0d8601cf-4eee-4d48-a33b-faa1ef4ed8d1.jpg)

**Comment by milindgoel15** [comment] 2022-03-01 17:46
Duplicate of #1664

**Closed by milindgoel15** 2022-03-01 17:46 UTC
Labels: bug
