### ISSUE TITLE
[Idea] add a button to cancel skip by sponsorblock

### ISSUE THREAD

**Issue by Soudini** [YTVanced/Vanced#1482] opened 2021-12-19 11:47 UTC
**Description**

In some videos, sponsored content is something that is worthwhile to watch because the creators put effort in them. So I sometimes want to watch them. To do so, I have to disable autoskip for sponsorblock because with it enable i cannot even go back to see the content because it will be skipped immediately again. I know that I can just have the button  "skip" on, but it adds interaction and I think it is less convenient as there is much more content flagged that i do not wish to see than content that I do.

What would be the best in my opinion is a third option (like on the desktop) where it autoskip but with a button to undo the skip and watch the segment. That way most of the time we have the expected behaviour (ignoring boring content) but when we want to act against it, it is convenient.

**Comment by milindgoel15** [comment] 2021-12-20 04:10
Duplicate of https://github.com/YTVanced/SponsorBlock/issues/6

**Closed by milindgoel15** 2021-12-20 04:10 UTC
Labels: enhancement
