### ISSUE TITLE
[Idea] Allow users to bypass age verification

### ISSUE THREAD

**Issue by MKCOOL142** [YTVanced/Vanced#570] opened 2021-03-19 21:19 UTC
**Description**
Allow european users to bypass YouTube's/Google's age verification pop-up, especially since this is easily avoided by using a american VPN (but just more complicated and I also don't trust VPN services tbh) where the user can just press "continue" instead of being asked to send google pictures of their ID or credit card

I heard newpipe bypasses this completely as well but I know that it might be way to hard to modify something like that simply cuz there's no yt app source code

**Comment by HRudyPlayZ** [comment] 2021-03-20 11:47
Agreed. This requirement is possibly illegal in the first place and i don't want to give Google an easy access to that kind of stuff.

**Comment by Oizaro** [comment] 2021-03-20 17:53
> Agreed. This requirement is possibly illegal in the first place and i don't want to give Google an easy access to that kind of stuff.

No, it is not. NewPipe (for example) allows viewing of videos protected by this verification, and was not bothered by Google.

In every case @KevinX8 there is a chance of get this feature on next Vanced version? Because I don't want to send credentials of my identity card to Google.

**Comment by milindgoel15** [comment] 2021-04-30 15:55
Duplicate of #173

**Closed by milindgoel15** 2021-04-30 15:55 UTC
Labels: enhancement, wontfix
