### ISSUE TITLE
[Idea] Add option to return the dislike counter

### ISSUE THREAD

**Issue by IveMalfunctioned** [YTVanced/Vanced#1467] opened 2021-12-12 21:16 UTC
**Description**
YouTube made the lousy decision of removing video dislikes, so maybe [this code](https://github.com/Anarios/return-youtube-dislike) could be implemented (as was SponsorBlock's) to re-add dislikes

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment] 2021-12-13 04:33
Duplicate of #1394

**Closed by milindgoel15** 2021-12-13 04:33 UTC
Labels: enhancement
