### ISSUE TITLE
[Idea] Returning dislikes

### ISSUE THREAD

**Issue by 460N1** [YTVanced/Vanced#1444] opened 2021-12-05 10:55 UTC
As you're probably well aware, YouTube has removed the dislike count and that has also affected Vanced. There are some users that made a 'return dislikes' addon for various browsers.

They currently use a YouTube API that still has the dislike count enabled - this will also soon get disabled, but they're hosting a database instead where they're trying to save as many videos' dislike count, so that once that API goes down, we'll still have the dislike numbers as well as a way to now update that number. Dislikes would be effectively independent of YouTube itself.

You could add this feature to Vanced too. One more thing to make Vanced stand out as the far better YouTube app than the YouTube app itself 😂

I talked to the devs while they were developing it and they said they'd be up to help in any way with its integration in Vanced if necessary.

https://www.returnyoutubedislike.com/

My apologies if you're already working on this, just wanted to bring it to your attention.

Love what you're doing, by the way, and have been a user from when you were only on XDA.

**Comment by milindgoel15** [comment] 2021-12-05 11:00
Just for God sake, look out for already existing issues on the repo before creating another one.

**Comment by milindgoel15** [comment] 2021-12-05 11:01
Duplicate of #1394

**Closed by milindgoel15** 2021-12-05 11:01 UTC
Labels: enhancement
