### ISSUE TITLE
[Bug] Black bar in all videos

### ISSUE THREAD

**Issue by troglorrules** [YTVanced/Vanced#857] opened 2021-05-22 23:27 UTC
**Bug description**
There is a narrow vertical black bar in all videos I view. In the center, from the bottom to the top. In both views. Non rooted 

**Variant**
Non-Root

**Vanced version**
16.02.35 - Build - 01.47.00

**Android version**
Android 11

**Device**
Samsung Galaxy s20

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Play a video. 
3. ....

**Expected behavior**
Should be no black bar.
![Screenshot_20210522-192429](https://user-images.githubusercontent.com/84647030/119243322-9ad04a00-bb33-11eb-9f64-271e7e2a8367.jpg)
![Screenshot_20210522-192425](https://user-images.githubusercontent.com/84647030/119243323-9b68e080-bb33-11eb-93dd-492470994ed2.jpg)
![Screenshot_20210522-192515](https://user-images.githubusercontent.com/84647030/119243324-9c017700-bb33-11eb-9b5d-a0224c68af39.jpg)

_Attach images/videos if possible. These can be helpful in solving the issue._

**Comment by troglorrules** [comment] 2021-05-22 23:39
Vanced Manager 2.6.0 crimsom

**Comment by milindgoel15** [comment] 2021-05-23 03:41
Duplicate of #741

**Closed by milindgoel15** 2021-05-23 03:41 UTC
Labels: bug

**Comment by troglorrules** [comment] 2021-05-26 04:25
Thanks for asking me. Black bar still there.
