### ISSUE TITLE
[Idea] Configurable Playback Speed

### ISSUE THREAD

**Issue by sixhex** [YTVanced/Vanced#1147] opened 2021-08-08 06:41 UTC
**Description**
Vanced is wonderful allowing an app to play back at 0.25x steps from 0.25x to 2.00x.

Please add an option for extended range on this parameter to around 4.00x if a device is capable. I see this as an advanced option in settings where a user can select maximum allowable playback speed.

_Attach images/videos if possible. Also add any links to possible other applications with the said feature already implemented._

**Comment by milindgoel15** [comment] 2021-08-08 09:41
Duplicate of #82

**Closed by milindgoel15** 2021-08-08 09:41 UTC
Labels: enhancement
