### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by NelviusDMoon** [YTVanced/Vanced#1296] opened 2021-09-26 23:26 UTC
**Bug description**
Youtube vanced keeps spamming notifications that I already dismissed it just keep coming back.

**Variant**
Non-Root/Root

**Vanced version**

16.29.39
**Android version**
Smart android

**Device**
Huawei Y7A

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
3. ....

**Expected behavior**
Replace me with a description of what you expected should happen and what happened instead.

_Attach images or videos or logcats in case of crashes if possible. These can be helpful in solving the issue._

Uploading SVID_20210927_070530_1.mp4…

**Comment by milindgoel15** [comment] 2021-09-27 03:50
Duplicate of #1107

**Closed by milindgoel15** 2021-09-27 03:50 UTC
Labels: bug

**Comment by DaniSheng** [comment] 2021-09-27 14:23
Same problem, deactivating push notifications not working, looping push notifications, same notifications cleared early.

**Comment by NelviusDMoon** [comment] 2021-09-29 05:15
I still want to have notifications but I don't want it to keep spamming
