### ISSUE TITLE
[Bug] having ads in general layout

### ISSUE THREAD

**Issue by Hanzixt** [YTVanced/Vanced#1557] opened 2022-01-27 17:34 UTC
**Bug description:**
having ads in general layout 

**Have you read vanced guides already? (YES/No)**
If your answer is no, please consider reading before creating this issue. The guides can be found in the readme section of this repository. 

**Variant:**
Non-Root

**Vanced version:**
v16.29.39

**Link used to download vanced:**
Replace here with the source/link you used to download and install on your device. 

**Android version:**
Replace me with the version of Android your device have. For example, Android 10

**Device:**
Realme 5i

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Clock on a video
3. below the video or in the general layout the ad wil appear

**Expected behaviour:**
The ads should not appear.

_Attach images or videos or logcats in case of crashes if possible. These can help solve the issue._
![Screenshot_2022-01-27-21-27-26-14_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/85128094/151412238-5c71cb1d-6800-4d3f-889c-812b0a05b595.jpg)
![Screenshot_2022-01-27-21-27-30-14_7a4090f09f6554852d748ee9fd6f40d3](https://user-images.githubusercontent.com/85128094/151412252-4e943ccc-3f53-42b5-91f9-97d61b7b29fd.jpg)

**Comment by milindgoel15** [comment] 2022-01-27 17:49
Duplicate of #1314

**Closed by milindgoel15** 2022-01-27 17:49 UTC
Labels: bug
