### ISSUE TITLE
Watched videos history 

### ISSUE THREAD

**Issue by Jolubeat** [YTVanced/Vanced#1175] opened 2021-08-13 21:17 UTC
**Bug Description**
Using YouTube vanced, the watched videos don't appear in my YouTube watched videos history. Is this an upcoming feature or some bug in my app? 
Thanks

**Variant**
Root

**Vanced version**
2.6.0

**YouTube Vanced Version**
16.29.39

**Android version**
Android 11 

**Device**
Xiaomi mi 9 SE

**Comment by milindgoel15** [comment] 2021-08-14 01:54
Duplicate of #301

**Closed by milindgoel15** 2021-08-14 01:54 UTC
Labels: bug
