### ISSUE TITLE
[Bug] Cant get access to Vanced via chromecast.

### ISSUE THREAD

**Issue by slith-wrist** [YTVanced/Vanced#1470] opened 2021-12-15 05:55 UTC
Hey guys,

On the latest version on yt vanced (16.29.39) on an Samsung s21 with Android 12 I can't get access to the chromecast function anymore. In the older version it worked. The error message is: "Youtube vanced will only run when you update Google Play services." The problem is that there is no update for Google play services, is that really a bug or do I have to wait for an Google play services update, if there will be one? 

Thanks in advance.

**Comment by milindgoel15** [comment] 2021-12-15 08:52
Duplicate of #688

**Closed by milindgoel15** 2021-12-15 08:52 UTC
Labels: bug
