### ISSUE TITLE
[Idea] No 'Explore', 'Shorts' buttons in the bottom line

### ISSUE THREAD

**Issue by Poluatorul** [YTVanced/Vanced#1080] opened 2021-07-12 06:00 UTC
Image 1 (before)- ![1](https://user-images.githubusercontent.com/59789203/125237867-9133b900-e310-11eb-9b4a-99d1ed2035dd.png)
Image 2 (after) - ![2](https://user-images.githubusercontent.com/59789203/125237873-942ea980-e310-11eb-951d-f63950592707.png)

Now in place of the "**Explore**" button is the "**Shorts**" button (image 1), you need them not to be in the bottom line at all. For example, how to forcefully disabled "**Create**" button. My suggestion is to add a function to the settings so that you can leave only 3 buttons in the bottom line: "**Home**", "**Subscriptions**", "**Library**"
This is how my version would look like (image 2)

**Comment by milindgoel15** [comment] 2021-07-12 06:15
Duplicate of #334

**Closed** 2021-07-12 06:15 UTC
Labels: enhancement
