### ISSUE TITLE
[Idea] YTM always resets shuffle button. 

### ISSUE THREAD

**Issue by Harmonie666** [YTVanced/Vanced#830] opened 2021-05-17 10:12 UTC
**Description**
YouTube Music on default always resets the shuffle function, when you tap on a track in both playlist&album. Also happens in "Next" view, etc.
I'm really struggling with this issue, because everytime I tap on a track or change playlists/albums I have to tap on the shuffle button again. It doesn't stay on.
Thus leaving me with being forced to tap shuffle all the time, many times a day.

Here is [proof](https://streamable.com/jbv6ah) 

Can you add a "Enforce Shuffle" feature, the same way you added "Enforce Repeating" feature?
![Screenshot_20210517-121013844 (1)](https://user-images.githubusercontent.com/73917917/118472414-1af84900-b709-11eb-91f1-66761d033ed5.png)

**Comment by Oizaro** [comment] 2021-05-18 00:21
Hi.

I will try to add also this features on the next version.

**Comment by Harmonie666** [comment] 2021-05-18 00:25
> Hi.
> 
> I will try to add also this features on the next version.

God bless you 🙏🏻❤️
I'm looking forward to it, and hopefully YTM Vanced will one day have as many great features, as YT Vanced.

**Comment by Oizaro** [comment] 2021-05-18 00:27
> > Hi.
> > I will try to add also this features on the next version.
> 
> God bless you 🙏🏻❤️
> I'm looking forward to it, and hopefully YTM Vanced will have as many great features, as YT Vanced.

I would try to keep just few high quality mods, instead of 100.000 with just 6/7 useful.

I think this will be the last new mod, if there is nothing else of interest to add.

**Comment by Harmonie666** [comment] 2021-05-18 00:32
Ideas you say? I could come up with hundreds of ideas, and adjustments for the app. Needless to say that Google will probably force Vanced to fix their terrible update decisions with YTM aswell, the same way they ruin stock YT every year. 

But for example; The libraries Playlists, Albums, Subscriptions, etc would definitely need a scrollbar, to navigate quicker in the app. Currently it's really a hassle, if we need to swipe down/up all the time, because there is no scrollbar on the left, that we could use.

**Comment by Oizaro** [comment] 2021-05-18 00:39
> Ideas you say? I could come up with hundreds of ideas, and adjustments for the app. Needless to say that Google will probably force Vanced to fix their terrible update decisions with YTM aswell, the same way they ruin stock YT every year. Please don't abandon YTM. It has so much potential, and deserves as much passion and love as YT Vanced 🙏🏻☺️
> 
> But for example; The libraries Playlists, Albums, Subscriptions, etc would definitely need a scrollbar, to navigate quicker in the app. Currently it's really a hassle, if we need to swipe down/up all the time, because there is no scrollbar on the left, that we could use.

I will not abandon the application, but adding features depends on their availability and the ease of adding. Too complex mods, with a large amount of code, will not be taken into consideration (also for a performance question).

**Comment by Harmonie666** [comment] 2021-05-18 00:42
Gotchu.
I'm happy that we will soon have enforce shuffling feature.
I also hope you can consider adding scrollbar 🙂
*Because there is no scrollbar on the right, I meant.

**Comment by Oizaro** [comment] 2021-05-18 02:53
I will try, there's no guarantee that it will succeed (I want to be honest, without making promises. I hope you understand).

**Comment by Harmonie666** [comment] 2021-06-01 15:21
@Oizaro 
Why has this topic gotten a "wontfix" label?
It's a mistake right? You are planning on implementing a enforce shuffling mod?

**Comment by Oizaro** [comment] 2021-06-01 15:23
> @Oizaro
> Why has this topic gotten a "wontfix" label?
> It's a mistake right? You are planning on implementing a enforce shuffling mod?

No, I won't. Google code logic prevents me from enforce tracks shuffling.

Sorry...

Maybe I'll retry in future, but at the moment this is the situation.

**Comment by Harmonie666** [comment] 2021-06-01 15:26
No, that's so unfortunate 😩😰
Please don't give up. This is terribly annoying if we are forced to press shuffle thousand times a day 😵

**Comment by Oizaro** [comment] 2021-06-01 15:34
> No, that's so unfortunate 😩😰
> Please don't give up. This is terribly annoying if we are forced to press shuffle thousand times a day 😵

Complain to google so... To force the repetition of the tracks it was enough to prevent the reset state of the button, for the shuffle this solution simply not applicable. Plus, Google doesn't save its status in system preferences for the next app load.

The logic behind this button is just "single track" centric. 🤷‍♂️

**Comment by Oizaro** [comment] 2021-06-03 13:51
@Harmonie666 After some newer tries I was able to succesfully force the shuffle mode to every tracks outside of being played playlist.

This mod is under testing now, and will be applied on next public version.

**Comment by milindgoel15** [comment] 2021-06-03 13:53
We will close this issue once it's successfully tested and released to public.

**Comment by Harmonie666** [comment] 2021-06-03 14:29
> @Harmonie666 After some newer tries I was able to succesfully force the shuffle mode to every tracks outside of being played playlist.
> 
> This mod is under testing now, and will be applied on next public version.

Omg. I appreciate you so much! 🙏🏻🤗
Tysm that you kept trying, and as a result managed to do it. 
What do you mean by "played playlist"? 
That shuffle will be forced outside of the current played playlist? On playlists and albums right, and even those "community created playlists" ?

**Comment by Oizaro** [comment] 2021-06-03 14:39
> > @Harmonie666 After some newer tries I was able to succesfully force the shuffle mode to every tracks outside of being played playlist.
> > This mod is under testing now, and will be applied on next public version.
> 
> Omg. I appreciate you so much! 🙏🏻🤗
> Tysm that you kept trying, and as a result managed to do it.
> What do you mean by "played playlist"?
> That shuffle will be forced outside of the current played playlist? On playlists and albums right, and even those "community created playlists" ?

When you shuffle tracks, you get a totally new playlist that you can see below the player with the dedicated button (the name of button is "related results" if I not wrong). Well...what I mean is shuffle is forced just to every tracks outside that already shuffled playlist, in short: on every tracks  manually selected by you (like for repeating mods).

That's all...

**Comment by Harmonie666** [comment] 2021-06-03 14:41
Alright. I can't wait to try out the next version. Thanks again man 🙏🏻
Have a great day!

**Comment by milindgoel15** [comment] 2021-06-03 15:02
@Harmonie666 hi, would you like to be beta tester and also test this new mod by yourself as well? If you are interested, you need to be either on discord or telegram. If you are on telegram, just private message me at @MilindGoel15 . If on discord, ping me with same username in off topic channel.

**Comment by Oizaro** [comment] 2021-06-04 16:37
> Alright. I can't wait to try out the next version. Thanks again man 🙏🏻
> Have a great day!

Version 4.30.50 will be released between today and tomorrow. 👍

**Comment by Oizaro** [comment] 2021-06-04 17:02
@Harmonie666 New version has been released!

**Comment by Oizaro** [comment] 2021-06-04 17:05
@Harmonie666 Try it and let me know if shuffle works properly.

**Comment by Harmonie666** [comment] 2021-06-04 17:55
Thank you 🙏🏻
I've downloaded it immediately and been testing it so far. Shuffle seems to work smoothly without any issues, but I will keep testing it, and report back tomorrow again. Just to make sure.

**Comment by Harmonie666** [comment] 2021-06-05 08:49
@Oizaro So I tested Shuffle thoroughly many hours, and it works just as intended. It's perfect.

But while testing it I noticed another weird issue. If shuffle is on you can't do the swipe right gesture on the cover of a track, only swipe left works (next shuffled track)
But at the same time you can tap the previous track button, which will also shuffle the playlist backwards. Something is blocking the Swipe right gesture on cover to shuffle backwards, on certain tracks.
**But this happens only with some tracks. Other tracks you are able to swipe right on cover to shuffle backwards**
Not sure if you will understand my explanation, but I recorded it for you:
https://streamable.com/c6161v

**Comment by Oizaro** [comment] 2021-06-05 12:22
> @Oizaro So I tested Shuffle thoroughly many hours, and it works just as intended. It's perfect.
> 
> But while testing it I noticed another weird issue. If shuffle is on you can't do the swipe right gesture on the cover of a track, only swipe left works (next shuffled track)
> But at the same time you can tap the previous track button, which will also shuffle the playlist backwards. Something is blocking the Swipe right gesture on cover to shuffle backwards, on certain tracks.
> **But this happens only with some tracks. Other tracks you are able to swipe right on cover to shuffle backwards**
> Not sure if you will understand my explanation, but I recorded it for you:
> https://streamable.com/c6161v

Everytime you select a new track (instead of take it from the playlist "next tracks", accessible from the bottom-left button), this track became the first of the shuffled playlist. So you can't go back to another track.

**Comment by Harmonie666** [comment] 2021-06-05 12:29
@Oizaro I understand. I tested this now and it indeed seems to be the case, if you select a new track from the playlist (instead of "Next playlist view")
However as I said before you can still shuffle back but it only works with the "previous track button" (screenshot below). 
I think in this case it should also work with the swipe right on cover gesture, to shuffle backwards. Otherwise why does one work when selecting a new track, but not the other? Especially since they do the same action.

![Screenshot_20210605-142552474 (1).png](https://user-images.githubusercontent.com/73917917/120891722-569c7980-c60a-11eb-93a9-168285ceef72.png)

**Comment by Oizaro** [comment] 2021-06-05 12:38
> @Oizaro I understand. I tested this now and it indeed seems to be the case, if you select a new track from the playlist (instead of "Next playlist view")
> However as I said before you can still shuffle back but it only works with the "previous track button" (screenshot below).
> I think in this case it should also work with the swipe right on cover gesture, to shuffle backwards. Otherwise why does one work when selecting a new track, but not the other? Especially since they do the same action.
> While it works with previous track button (even with first track of playlist) it doesn't work with swipe right on cover.
> 
> ![Screenshot_20210605-142552474 (1).png](https://user-images.githubusercontent.com/73917917/120891722-569c7980-c60a-11eb-93a9-168285ceef72.png)

You got back button working by selecting the track of your screenshot?

**Comment by Oizaro** [comment] 2021-06-05 12:41
Oh...wait. I totally forgot that back button works always also to reset the current track.

So don't worry if its still usable.

**Comment by Harmonie666** [comment] 2021-06-05 12:45
> Oh...wait. I totally forgot that back button works always also to reset the current track.
> 
> So don't worry if its still usable.

Yes it works always. It's only unavailable in minimized player (swipe left/right for previous/next track in minimized player is a Spotify feature)

I just find it annoying that shuffling and swipe right gesture on track to go back, doesn't work. Makes no sense when it does work with the back button.

**Comment by Oizaro** [comment] 2021-06-05 12:50
> > Oh...wait. I totally forgot that back button works always also to reset the current track.
> > So don't worry if its still usable.
> 
> Yes it works always. It's only unavailable in minimized player (swipe left/right for previous/next track in minimized player is a Spotify feature)
> 
> I just find it annoying that shuffling and swipe right gesture on track to go back, doesn't work with selected tracks. Makes no sense when it does work with the back button.
> Could you also adjust that and make it work with Swipe right on cover?

Mhh...so you would like it to go back from the first track to the last, instead of resetting it, as a sort of loop?

**Comment by Harmonie666** [comment] 2021-06-05 12:54
> Mhh...so you would like it to go back from the first track to the last, instead of resetting it, as a sort of loop?

I'm not sure how to answer that. But from my observation you can shuffle backwards **with the selected track** with the back button, while you can't shuffle backwards with the swipe right gestures on cover. Just test it yourself, you will see what I mean.

**Comment by Oizaro** [comment] 2021-06-05 12:57
> > Mhh...so you would like it to go back from the first track to the last, instead of resetting it, as a sort of loop?
> 
> I'm not sure how to answer that. But from my observation you can shuffle backwards **with the selected track** and the back button, while you can't shuffle backwards with the swipe right gesture on cover. Just test it yourself, you will see what I mean.

In fact its a request that should be investigated and discussed in another feature request thread. Shuffle mode works as intended in this case.

**Comment by Harmonie666** [comment] 2021-06-05 13:01
That is correct. Shuffle mode works as intended. 
It's indeed a additional request. 
But we have all the necessary information already collected in this topic. How should we proceed? 
We can also talk this out in Telegram or Discord, if you want to.

**Comment by Oizaro** [comment] 2021-06-05 13:07
> That is correct. Shuffle mode works as intended.
> It's indeed a additional request.
> But we have all the necessary information already collected in this topic. How should we proceed?
> We can also talk this out in Telegram or Discord, if you want to.

Why don't join on group test on telegram? Milind offers you this possibility (also just for ytmusic testing).

**Comment by Harmonie666** [comment] 2021-06-05 13:13
> Why don't join on group test on telegram? Milind offers you this possibility (also just for ytmusic testing). 

That is not impossible for me, because beta testing doesn't install a seperate YTM app, and instead would overwrite my current one.
I'm a YT premium user, and I have lots of downloaded music in my library. If I were to join test app I would loose all my downloads 😕
Milind confirmed this to me. 
I don't know how difficult it would be to fullfil this new request of mine, but I would appreciate if you could try to implement it for a next version.

**Comment by Harmonie666** [comment] 2021-06-05 13:14
![Screenshot_20210603-171051781.png](https://user-images.githubusercontent.com/73917917/120892918-c0b81d00-c610-11eb-94ad-2e09ce6df649.png)

**Comment by Oizaro** [comment] 2021-06-05 13:15
> > Why don't join on group test on telegram? Milind offers you this possibility (also just for ytmusic testing).
> 
> That is not impossible for me, because beta testing doesn't install a seperate YTM app, and instead would overwrite my current one.
> I'm a YT premium user, and I have lots of downloaded music in my library. If I were to join test app I would loose all my downloads 😕
> Milind confirmed this to me.
> I don't know how difficult it would be to fullfil this new request of mine, but I would appreciate if you could try to implement it for a next version 🙏🏻

This is not a problem i think, kevinx8 can sign the package with the right key and you can install a beta as well

**Comment by Harmonie666** [comment] 2021-06-05 13:21
> This is not a problem i think. kevinx8 can sign the package with the right key, allowing you to install a beta as well.

In that case I would be able to join the YTM beta, and install a second app for it.

**Comment by Oizaro** [comment] 2021-06-05 13:23
> > This is not a problem i think. kevinx8 can sign the package with the right key, allowing you to install a beta as well.
> 
> In that case I would be able to join the YTM beta, and install a second app for it.

Contact milind 👍

**Comment by Harmonie666** [comment] 2021-06-05 13:55
I contacted him. He will get back to me once their is a new beta for YTM.
I hope that I will be able to test my new request of shuffling backwards with the selected track, and swipe right gesture on cover. Don't know if you are already working on it though, but if you need any information just let me know.
I'm glad that Vanced YTM has all these great new mods now, and I'm eternally grateful for the work that you put in it 🙏🏻

**Comment by milindgoel15** [comment] 2021-06-08 09:25
So we can close this issue ig

**Closed by milindgoel15** 2021-06-08 09:25 UTC
Labels: enhancement
