### ISSUE TITLE
[Idea] Move the "Save" button to be next to the "Share" button

### ISSUE THREAD

**Issue by fedew04** [YTVanced/Vanced#1654] opened 2022-02-20 01:11 UTC
*Description*
Move the "Save" button next to the "Share" button. I use the Save button often, and it is annoying going through the Create, Download and Clip buttons (which I NEVER use), just to click it. Yeah it's probably a minor inconvenience but it would be a nice quality of life change.
![image](https://user-images.githubusercontent.com/65686048/154824516-b0214a05-431d-42a4-9b73-cdb602dd904d.png)

**Comment by milindgoel15** [comment] 2022-02-20 01:14
Duplicate of #1153

**Closed by milindgoel15** 2022-02-20 01:14 UTC
