### ISSUE TITLE
[Idea] Save settings 

### ISSUE THREAD

**Issue by Mimicthis** [YTVanced/Vanced#1000] opened 2021-06-23 13:40 UTC
**Description**
An option to export our Vanced settings or somethings like that so we don't have to adjust everything to the last millimeter when it's reinstalled.

**Comment by FBIAgent05** [comment] 2021-06-23 19:01
I like this idea

**Comment by milindgoel15** [comment] 2021-06-26 02:49
Duplicate of #347

**Closed by milindgoel15** 2021-06-26 02:49 UTC
Labels: enhancement
