### ISSUE TITLE
[Bug] "YouTube can't open this link" pops up.

### ISSUE THREAD

**Issue by swastik21** [YTVanced/Vanced#1690] opened 2022-02-26 08:31 UTC
**Bug description:**
Whenever i try to open YouTube links inside vanced YouTube application, it shows me YouTube can't open this link.

**Have you read vanced guides already? (YES/No)**
Yes

**Variant:**
Non-Root

**Vanced version:**
17.03.38

**Link used to download vanced:**
https://vancedapp.com/

**Android version:**
 Android 11 

**Device:**
Vivo z1x

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Click on any YouTube links below any post or video description.

**Expected behaviour:**
It should open the video from the link inside the vanced YouTube application instead it pops up the message "YouTube can't open this link".

![Screenshot_20220226_140121](https://user-images.githubusercontent.com/42748932/155836320-8aeb6b48-5162-43d3-bfd0-3a5fa146254b.jpg)

**Comment by milindgoel15** [comment] 2022-02-26 08:54
Duplicate of #774

**Closed by milindgoel15** 2022-02-26 08:54 UTC
Labels: bug
