### ISSUE TITLE
[Idea] Revert the like/dislike/share/download/save buttons to what they were before

### ISSUE THREAD

**Issue by TikiPlayz** [YTVanced/Vanced#408] opened 2021-01-30 15:45 UTC
The new like/dislike/share/download/save buttons are a super ugly and bright white that seems very low effort and clicking like doesn't even change the icon to a different color, please revert it back to what it was before
![image](https://user-images.githubusercontent.com/20033421/106360668-bd6df700-62e7-11eb-92fa-bc78eb9006e0.png)
![image](https://user-images.githubusercontent.com/20033421/106360738-3d945c80-62e8-11eb-8731-cf4ce51eca4b.png)

**Comment by Hyperboraeer** [comment] 2021-02-03 11:22
It would be a toggle (optional) if the devs implemented that.

**Comment by AinzTheSupremeOne** [comment] 2021-02-05 06:45
No, you guys are too hung up on the past and refuse to adapt to the new design. It may "seem" ugly to you, and may not to a lot others.

Even if you get a button to switch to old icons, it would stop working as soon as Google removes the old icons from the base code. Then people would compain over and over. Mod specific features are hard to maintain as it is; everytime Google releases an update of YouTube, some of them break. If you really that hate it, why not ask Google to rollback to old icons? I am sure they would at least do something if a "lot" of users report that they don't like the change. ~~And by a lot, I mean millions~~ 😉

**Comment by TikiPlayz** [comment] 2021-02-11 20:52
> 
> 
> No, you guys are too hung up on the past and refuse to adapt to the new design. It may "seem" ugly to you, and may not to a lot others.
> 
> Even if you get a button to switch to old icons, it would stop working as soon as Google removes the old icons from the base code. Then people would compain over and over. Mod specific features are hard to maintain as it is; everytime Google releases an update of YouTube, some of them break. If you really that hate it, why not ask Google to rollback to old icons? I am sure they would at least do something if a "lot" of users report that they don't like the change. ~And by a lot, I mean millions~ 😉

Literally everybody on Reddit calls the redesign "bad". I'm ok with it.

**Comment by vrindavan** [comment] 2021-02-17 07:06
-1

**Comment by AinzTheSupremeOne** [comment] 2021-04-19 18:41
Duplicate of #187 .

**Closed** 2021-04-30 11:30 UTC
Labels: enhancement, wontfix
